### ISSUE TITLE
Thread safety issue with HandleRFBServerMessage() in libvncclient/rfbproto.c when TLS used.

### ISSUE THREAD

**Issue by gbdj** [LibVNC/libvncserver#100]
There are two threads in threaded application 
(One for receiving VNC server messages, another for sending). 
Channel is protected by GNUTLS after VeNCrypt auth. 
As stated in http://gnutls.org/manual/html_node/Thread-safety.html
"A gnutls_session_t object can be shared by two threads, one sending, the other receiving."

Here is the problem:
HandleRFBServerMessage() in receiving thread after reading and processing rfbFramebufferUpdate from server trying to SendIncrementalFramebufferUpdateRequest()
If sending thread is trying to send rfbPointerEvent at same time, we get data corruption and link terminated by remote server. Write operation in such case must be protected by mutex.

There are several bad options how to fix thread safety:

1. Wrap entire HandleRFBServerMessage() call and all other write operations in application by mutex. 
It's extremely inefficient, because huge rfbFramebufferUpdate will block any events from mouse and keyboard until rfbFramebufferUpdate received and processed. Half-duplex and latency is bad.
2. Split HandleRFBServerMessage() into reading and writing parts. Give them new names. 
Don't modify original to preserve compatibility. Then mutex lock will be an application problem.
3. Implement callback hooks around SendIncrementalFramebufferUpdateRequest()
4. Add mutex field to rfbClient and function to set it. Wrap write operation by this optional mutex.

That do you think about it? Is it right way to fix this in library? If so, i can write a fix. 
But i really need design review from someone who familiar with library code. =)
Which method is least ugly by your opinion ?

**Comment by bk138** [comment]
Can you point out the code locations for exact reference pls?

**Comment by gbdj** [comment]
[HandleRFBServerMessage()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L1747-L2350)
[rfbFramebufferUpdate message reading and prosessing](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L1788-L2203l)
![](http://libvnc.github.io/doc/html/group__libvncclient__api_gaa9ba8ed8e74e27e9c4095e0190d2aad9_cgraph.png)

**Comment by gbdj** [comment]
In the receiving thread in our case [HandleRFBServerMessage()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L1747-L2350) is doing [rfbFramebufferUpdate message reading and prosessing](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L1788-L2203l). After many ReadFromRFBServer() calls [(definition here)](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/sockets.c#L68-L236) and processing, it does [SendIncrementalFramebufferUpdateRequest() call](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L2196) which is [uses](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L1539) [WriteToRFBServer()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/sockets.c#L239-L293). 
On lower level [ReadFromTLS()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/tls_gnutls.c#L459-L475) and [WriteToTLS()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/tls_gnutls.c#L477-L496) is used from ReadFromTLS() and WriteToRFBServer() accordingly. Here is the map:
![](http://libvnc.github.io/doc/html/group__libvncclient__api_gaa9ba8ed8e74e27e9c4095e0190d2aad9_cgraph.png)
At the same time sending thread is trying to send rfbPointerEvent with [SendPointerEvent()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/rfbproto.c#L1684-L1703) call.
![](http://libvnc.github.io/doc/html/group__libvncclient__api_gaad722bff3748771686f18252296585ea_cgraph.png)
We need to find a least ugly way to protect write access by mutex as close to WriteToTLS() as reasonably possible. Lock on entire HandleRFBServerMessage() in too huge.

P.S. I have hard-to-read debug from additional logging added by me and tcpdump capture of the same session. Please ask if you need one. Forget to say, it's all about TLS with X509 client auth support implementation for [guacd](https://github.com/glyptodon/guacamole-server).

**Comment by gbdj** [comment]
I fixed the problem with minimal modification to the library.
Just wrap around [body of WriteToTLS()](https://github.com/LibVNC/libvncserver/blob/5b322f523faa437d8e7d03736bdb1714e8f84ce5/libvncclient/tls_gnutls.c#L483-L494) by two new hooks.
This way, lib don't need to know about mutexes. Application must care about them.

I can contribute patch, if someone interested.

Just for reference here is some diagnostics for this issue and its solution:

Legend:
```
< 0 : rfbFramebufferUpdate
> 3 : rfbFramebufferUpdateRequest
> 5 : rfbPointerEvent
```
Normal flow: 
```
Feb  3 19:09:56 guac guacd[4090]:       < 0: recived 7845/8192     // rfbFramebufferUpdate received in <Receiving thread>  
Feb  3 19:09:56 guac guacd[4090]: > 3                              // <Receiving thread> is entered in WriteToTLS() to write rfbFramebufferUpdateRequest
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 3: ret == 10     // <Receiving thread> is successfully writes rfbFramebufferUpdateRequest
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 3: offset 10/10. 
Feb  3 19:09:56 guac guacd[4090]: > 5                              // <Sending thread> is entered in WriteToTLS() to write rfbPointerEvent
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 5: ret == 6 
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 5: offset 6/6. 
```
Race condition:
```
Feb  3 19:09:56 guac guacd[4090]:       < 0: recived 4972/8192 
Feb  3 19:09:56 guac guacd[4090]: > 3                              // <Receiving thread> is entered in WriteToTLS()
Feb  3 19:09:56 guac guacd[4090]: > 5                              // <Sending thread> is entered in WriteToTLS()
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 5: ret == 10     // 10 bytes was written to tls
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 5: offset 10/6.  // but must be only 6 bytes in rfbPointerEvent, data is corrupted 
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 3: ret == 10     // same data was written again to tls
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 3: offset 10/10. // traffic analysis shows duplicate TLS record on wire
Feb  3 19:09:56 guac guacd[4090]: ReadFromTLS(): ret == -110       // and remote VNC server terminates connection
Feb  3 19:09:56 guac guacd[4090]: Error reading from TLS: The TLS connection was non-properly terminated.. 
Feb  3 19:09:56 guac guacd[4090]: ReadFromTLS() gnutls error -110: The TLS connection was non-properly terminated.. 
Feb  3 19:09:56 guac guacd[4090]: > 5 
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS()  > 5: ret == -10 
Feb  3 19:09:56 guac guacd[4090]: Error writing to TLS: The specified session has been invalidated for some reason.. 
Feb  3 19:09:56 guac guacd[4090]: WriteToTLS() gnutls error: -10. 
Feb  3 19:09:56 guac guacd[4090]: Client disconnected
```
Fixed behavior in same condition:
```
Feb  9 01:36:06 guac guacd[12998]: ReadFromTLS(): ret == 97 
Feb  9 01:36:06 guac guacd[12998]:       < 0: recived 97/8192 
Feb  9 01:36:06 guac guacd[12998]: > 3      // <Receiving thread> is entered in WriteToTLS() and acquired the lock 
Feb  9 01:36:06 guac guacd[12998]: > 5      // <Sending thread> is entered in WriteToTLS() and waiting for the lock 
Feb  9 01:36:06 guac guacd[12998]: WriteToTLS()  > 3: ret == 10 
Feb  9 01:36:06 guac guacd[12998]: WriteToTLS()  > 3: offset 10/10. 
Feb  9 01:36:06 guac guacd[12998]: WriteToTLS()  > 5: ret == 6 
Feb  9 01:36:06 guac guacd[12998]: WriteToTLS()  > 5: offset 6/6. 
```
This condition arises multiple times in stress testing and i think problem is fixed.
Stress test is youtube video and constant mouse movement. =)

**Comment by bk138** [comment]
Thank you very much, merged now.
