### ISSUE TITLE
max macro in rfbproto.h conflicts with stl_algobase.h

### ISSUE THREAD

**Issue by rdieter** [LibVNC/libvncserver#102]
Applications that use stl_algobase.h and include libvncserver's rfbproto.h can hit this error like I just did trying to compile kde's krfb:

In file included from /usr/include/c++/6.0.0/algorithm:61:0,
                 from /usr/include/qt5/QtCore/qglobal.h:85,
                 from /usr/include/qt5/QtCore/qnamespace.h:37,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:41,
                 from /usr/include/qt5/QtCore/qobject.h:40,
                 from /usr/include/qt5/QtCore/QObject:1,
                 from /builddir/build/BUILD/krfb-15.12.1/krfb/framebuffer.h:17,
                 from /builddir/build/BUILD/krfb-15.12.1/krfb/framebuffer.cpp:10:
/usr/include/c++/6.0.0/bits/stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)

The approach other projects have taken in the past to avoid this, is to use a custom/name-spaced macro, instead of generic 'max'.  I'll do the same here preparing a pull-request

**Comment by bk138** [comment]
Merged, thanks!
