### ISSUE TITLE
Android example doesn't work

### ISSUE THREAD

**Issue by mateusz-** [LibVNC/libvncserver#104]
I built the project for an ARM device. Specifically, the device that I am testing on is a Nexus 6 running Android 6.0.1.

Running the example:
```
$ adb shell /data/local/tmp/androidvncserver
WARNING: linker: /data/local/tmp/androidvncserver: unused DT entry: type 0x1d arg 0x349
Initializing framebuffer device /dev/graphics/fb0...
cannot open fb device /dev/graphics/fb0
```

I don't have su and I can't cd or ls the graphics directory to change/verify permissions.

If I try ```adb pull /dev/graphics/fb0 fb0```, adb responds with ```remote object '/dev/graphics/fb0' does not exist```.

If I try to pull a known existing file with only read root privileges, adb responds with ```failed to copy '/fstab.shamu' to 'fstab.shamu': Permission denied```.

So, it looks like this is not a file permission issue, correct?

**Comment by bk138** [comment]
Dunno, maybe your fb device is somewhere else?

**Comment by mateusz-** [comment]
Thanks.

I used ```find``` to figure out the location of the framebuffer device.

```
$ find -name "fb0" 2>/dev/null
./sys/devices/virtual/graphics/fb0
./sys/class/graphics/fb0
```

I adjusted fbvncserver.c accordingly and then...

```
$ ./androidvncserver                             
WARNING: linker: ./androidvncserver: unused DT entry: type 0x1d arg 0x349
Initializing framebuffer device /sys/devices/virtual/graphics/fb0...
ioctl error
```

strerror reports "not a typewriter". [Google tells me](https://groups.google.com/forum/#!topic/android-ndk/9Li2jizwH2Y) that this may be a permissions issue (no root). Indeed, trying to adb pull fb0 gives me permissions issues.

I'm guessing if I got that resolved everything would work.
