### ISSUE TITLE
How to built server and client on Windows machine.? Can you please give some step by step instructions..

### ISSUE THREAD

**Issue by subratpn** [LibVNC/libvncserver#106]
Vnc

**Comment by josej69** [comment]
i'm also interested in get libvncserver/libvncclient dll's compiled for win32, i want to use this dll's under visual basic 6 but i have no idea of use mingw, tried but no success. there is no place for get this dll's compiled?

**Comment by bk138** [comment]
Unless someone builds them, not yet.

**Comment by AhmedDeif** [comment]
Did anybody succeed ?

**Comment by bk138** [comment]
Fixed by df9986ea439cb0afc0701b67561c8813237a84a7
