### ISSUE TITLE
MAX_ENCODINGS value too small

### ISSUE THREAD

**Issue by zbierak** [LibVNC/libvncserver#112]
Hi, 

the current MAX_ENCODINGS value is set to 21, which means that in the most "luxurious" settings (with both libz and libjpeg) it leaves a place only for one or two custom client encodings retrieved from rfbClientExtensions. 

Do you think that it would be ok to increase MAX_ENCODINGS to some larger value (like for instance 32, which would make place for 10+ client encodings; or even some larger value?). Alternatively, perhaps the maximum number of encodings should somehow be retrieved from the library client?

I can code it up, just let me know whether you see that as an issue and would welcome a respective pull request.

**Comment by bk138** [comment]
Yeah that should be safe to increase. If you look at line 1303 of rfbproto.c, a value of 128 or 256 should do no harm.
