### ISSUE TITLE
How to build it on mac? Can I use it for iOS Devices?

### ISSUE THREAD

**Issue by JohnnySheng** [LibVNC/libvncserver#113]
How to build it on mac? 

Can I use it in an iOS project?

**Comment by bk138** [comment]
https://libvnc.github.io/#building. 

And yes, that *should* work.

**Comment by ysnnzlcn** [comment]
I did not understand anything from this link, is there any documentation or example about using this library in iOS? If i use it in my app do i have to pay for license? Any help would be appreciated.

**Comment by bk138** [comment]
Build instructions are here: https://github.com/LibVNC/libvncserver#how-to-build 
The license is GPL. And Google can help you.
