### ISSUE TITLE
VNC Client Framebuffer update on SCROLL -- not working

### ISSUE THREAD

**Issue by velasta** [LibVNC/libvncserver#116]
When building the VNC client for the Android app (as an Android VNC Client app), I've noticed

that the Framebuffer doesn't update the screen as the **scrolling** is activated.
When I put my finger down and start moving, it freezes the whole screen and only updates after I lift my finger off.

Based of this: https://github.com/bk138/multivnc it's in the VNCConn.java file where the MESSAGETYPE in the while loop stops when a finger is down and scrolling is activated. I tried many ways of "hacking" around it but with no luck of getting the Framebuffer to update.

while (maintainConnection) {

            bitmapData.syncScroll();

            // This is where the code stops when we put a finger touch on screen
            // Read message type from the server.
            int msgType_2 = rfb.readServerMessageType();

            //int msgType_2 = 0;
            bitmapData.doneWaiting();

            // Process the message depending on its type.
            switch (msgType_2) {

            case it..RfbProto.FramebufferUpdate:

                rfb.readFramebufferUpdate();

                for (int i = 0; i < rfb.updateNRects; i++) {

**Comment by bk138** [comment]
Then you should report the issue over at MultiVNC.
