### ISSUE TITLE
Next release of libvncserver

### ISSUE THREAD

**Issue by cinemast** [LibVNC/libvncserver#119]
Hi!

I was wandering if you have any upcoming release planned within the next few weeks? If not I would have to cherry-pick bugfixes from master individually, which is ok, but if there will be a release soon, I would like to avoid the duplicate work.

**Comment by bk138** [comment]
I think I can roll a release within the next 3 weeks, but might take 6. Would that be okay for you?

**Comment by cinemast** [comment]
Yes, of course. Thank you.
