### ISSUE TITLE
LibVNCClient Documentation: Error 404

### ISSUE THREAD

**Issue by flederwiesel** [LibVNC/libvncserver#126]
Trying to view the sample code in **LibVNCClient Documentation**, _SDLvncviewer.c_ links to "https://libvnc.github.io/doc/html/_s_d_lvncviewer_8c.html", which is not found.

**Comment by bk138** [comment]
Thanks for reporting! Do you have an idea how to fix this?

**Comment by flederwiesel** [comment]
Sorry for the late reply. Compiling the documentation, the link is working and the target seems to be the same: ".../doc/html/_s_d_lvncviewer_8c.html". Maybe the file is gone missing on the server, although I cannot imagine how this should have happened. Hmm...

**Comment by bk138** [comment]
Seems related to https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by bk138** [comment]
Fixed by https://github.com/LibVNC/LibVNC.github.io/commit/8d3d75ade9c58484a308a8ee41b0dce3925decd5
