### ISSUE TITLE
build issue with CentOS

### ISSUE THREAD

**Issue by kayechica** [LibVNC/libvncserver#127]
I tried to compile it using linux based on:
LSB Version:  :core-3.1-ia32:core-3.1-noarch:graphics-3.1-ia32:graphics-3.1-noarch
Distributor ID: CentOS
Description:    CentOS release 5.5 (Final)
Release:        5.5
Codename:       Final

But I always get an error during build.
Here is the build error:

`make  all-recursive

make[1]: Entering directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10'

Making all in libvncserver

make[2]: Entering directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10/libvncserver'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10/libvncserver'

Making all in examples

make[2]: Entering directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10/examples'

make[3]: Entering directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10/examples'

/bin/sh ../libtool --tag=CC   --mode=link gcc  -g -O2 -Wall -I/m/mls/pkg/ix86-Linux-RHEL5/include -I/m/mls/pkg/ix86-Linux-RHEL5/include     -o example example.o ../libvncserver/libvncserver.la  -lnsl -lpthread -lz -ljpeg -lresolv  -L/m/mls/pkg/ix86-Linux-RHEL5/lib -Wl,-R/m/mls/pkg/ix86-Linux-RHEL5/lib -lgcrypt -lgpg-error -Wl,-R/m/mls/pkg/ix86-Linux-RHEL5/lib -L/m/mls/pkg/ix86-Linux-RHEL5/lib -lgnutls  

gcc -g -O2 -Wall -I/m/mls/pkg/ix86-Linux-RHEL5/include -I/m/mls/pkg/ix86-Linux-RHEL5/include -o .libs/example example.o -Wl,-R/m/mls/pkg/ix86-Linux-RHEL5/lib -Wl,-R/m/mls/pkg/ix86-Linux-RHEL5/lib  ../libvncserver/.libs/libvncserver.so -L/m/mls/pkg/ix86-Linux-RHEL5/lib -lnsl -lpthread /m/mls/pkg/ix86-Linux-RHEL5/lib/libjpeg.so -lresolv /m/mls/pkg/ix86-Linux-RHEL5/lib/libgnutls.so /m/mls/pkg/ix86-Linux-RHEL5/lib/libtasn1.so /m/mls/pkg/ix86-Linux-RHEL5/lib/libz.so /m/mls/pkg/ix86-Linux-RHEL5/lib/libgcrypt.so /m/mls/pkg/ix86-Linux-RHEL5/lib/libgpg-error.so /m/mls/pkg/ix86-Linux-RHEL5/lib/libintl.so /m/mls/pkg/ix86-Linux-RHEL5/lib/libiconv.so -lc  -Wl,--rpath -Wl,/usr/local/lib -Wl,--rpath -Wl,/m/mls/pkg/ix86-Linux-RHEL5/lib

../libvncserver/.libs/libvncserver.so: undefined reference to `htobe16'

../libvncserver/.libs/libvncserver.so: undefined reference to `htobe64'

collect2: ld returned 1 exit status

make[3]: **\* [example] Error 1

make[3]: Leaving directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10/examples'

make[2]: **\* [all-recursive] Error 1

make[2]: Leaving directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10/examples'

make[1]: **\* [all-recursive] Error 1

make[1]: Leaving directory `/bonus/scratch/kborja/src/libvncserver-LibVNCServer-0.9.10/libvncserver-LibVNCServer-0.9.10'

make: **\* [all] Error 2`

**Have you encountered same problem?
Is this compatible with a CentOS Linux machine?**

**Comment by bk138** [comment]
What's your ./configure output?

**Comment by kayechica** [comment]
After extracting the source code (zip file), I performed ./autogen.sh
Output logs attached.
Thank you.
[autogen_output.txt](https://github.com/LibVNC/libvncserver/files/395041/autogen_output.txt)

**Comment by bk138** [comment]
Does https://stackoverflow.com/questions/26713198/undefined-reference-to-htole32 help you?

**Comment by bk138** [comment]
Altenatively, you can build without websockets support, see ./configure --help

**Comment by kayechica** [comment]
I need the websockets support so I cannot opt to take it out.
This will be resolved if I update gclib to a later version (I currently have v2.5), unfortunately I cannot do that. 
Do you have suggestions on any alternative ways to implement these functions?
htobe64, htobe32, htobe16, htobe64, htobe16

Thanks

**Comment by bk138** [comment]
Well you could code them from scratch. the pattern should be the same for all bit widths. 

Am 4. August 2016 04:08:45 MESZ, schrieb kayechica <notifications@github.com>:
>I need the websockets support so I cannot opt to take it out.
>This will be resolved if I update gclib to a later version (I currently
>have v2.5), unfortunately I cannot do that. 
>Do you have suggestions on any alternative ways to implement these
>functions?
>htobe64, htobe32, htobe16, htobe64, htobe16
>
>Thanks
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LibVNC/libvncserver/issues/127#issuecomment-237432448

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by The-42** [comment]
CentOS 5.5 carries the ancient glibc 2.5, and endian functions were not provided until glibc 2.9 which is 9 years old by now. If you really need to build on prehistoric systems, I think you could use [this gist](https://gist.github.com/panzi/6856583) to get around that linker error, but who knows what it'll run into next...

@bk138 CMake should check for glibc >= 2.9 (maybe newer) or linking against endian functions. With autotools you'd already have a pull request by now, but I don't know much about cmake :)
