### ISSUE TITLE
'(keysym) macro redefined' warnings when building with FLTK

### ISSUE THREAD

**Issue by willbprog127** [LibVNC/libvncserver#130]
Greetings,

While working on a VNC multi-client viewer based on libvncclient and FLTK, I have been facing hundreds of warnings during building.  An example follows:

```
In file included from /usr/local/include/FL/fl_draw.H:27:
In file included from /usr/local/include/FL/x.H:49:
In file included from /usr/local/include/X11/Xutil.h:54:
In file included from /usr/local/include/X11/keysym.h:73:
/usr/local/include/X11/keysymdef.h:1333:9: warning: 'XK_Greek_switch' macro redefined
#define XK_Greek_switch                  0xff7e  /* Alias for mode_switch */
        ^
/usr/local/include/rfb/keysym.h:1154:9: note: previous definition is here
#define XK_Greek_switch         0xFF7E  /* Alias for mode_switch */
        ^
654 warnings generated.
Compilation finished successfully.
```

While it's not affecting my overall build, it's very hard to wade through 654 warnings to find other warnings related to *my* code.

Are there any preprocessor directives or other things I could try to get rid of these warnings?  I have posted on the FLTK forums about this issue as well.

Thank you! :-)

**Comment by bk138** [comment]
Seems your keysym definitions don't contain XK_0. Judging from the first line of rfb/keysym.h, this serves as a kind of header guard.

**Comment by willbprog127** [comment]
@bk138 Thank you.  I had just broken my project up into separate .h and .cxx files, so I had to juggle the position of some of the includes.  All better now. :+1:
