### ISSUE TITLE
How to properly terminate / clean up after calling rfbInitClient with the -listen parameter ?

### ISSUE THREAD

**Issue by willbprog127** [LibVNC/libvncserver#131]
Greetings,

Currently I'm calling `rfbInitClient` with the '-listen' parameter in a thread, then if the user wants to terminate listening, my program calls `rfbClientCleanup` then cancels the thread.  I do notice, however, that the program is still listening on the port (5500) until the whole program exits.

Is there something more I need to do to stop the listening on the listening port besides quitting the whole program?

Thank you! :smile:

**Comment by willbprog127** [comment]
I'm not sure if it was a one-time thing or not, but now the port is no longer listening after `rfbClientCleanup`.  I'll go ahead and close this, then.  Sorry for the noise.

**Comment by bk138** [comment]
Take a look at https://github.com/bk138/multivnc, I implemented a listen function there as well, I think.

**Comment by willbprog127** [comment]
@bk138 Thank you :+1:
