### ISSUE TITLE
Unable to close tkx11vnc window.

### ISSUE THREAD

**Issue by kolorafa** [LibVNC/libvncserver#133]
After clicking Actions > "stop & exit"
i got left with:

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-01-14-17-06.png)

while trying to find "pid" of this window .. i was highly amazed that this window doesn't have any process pid.

xprop _NET_WM_PID > click on the window and got:
_NET_WM_PID:  not found.

I can move this window, i can resize it but it doesn't repaint.

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-01-14-20-24.png)

Is there a way to kill/close it without restarting whole pc?

xprop
XKLAVIER_STATE(INTEGER) = 0, 1951476736
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 27, 1
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_STATE(ATOM) = 
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		program specified minimum size: 598 by 312
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
_NET_WM_ICON_NAME(UTF8_STRING) = "tkx11vnc"
WM_ICON_NAME(STRING) = "tkx11vnc"
_NET_WM_NAME(UTF8_STRING) = "tkx11vnc"
WM_NAME(STRING) = "tkx11vnc"
WM_CLASS(STRING) = "full", "Toplevel"

OS: Arch (Antergos+Cinnamon)

**Comment by bk138** [comment]
As this has to do with x11vnc, can you pls report it over at https://github.com/LibVNC/x11vnc/issues?
