### ISSUE TITLE
[Question] Where is the frame actually sent to client in code?

### ISSUE THREAD

**Issue by dobber1611** [LibVNC/libvncserver#134]
I'm looking for away to generate a digest on the frame data that is sent to the client, before it is sent, but I cant seen to find where the data is stored and/or sent. Any help would be appreciated, Thanks.

**Comment by bk138** [comment]
/*
 * rfbSendFramebufferUpdate - send the currently pending framebuffer update to
 * the RFB client.
 * givenUpdateRegion is not changed.
 */

rfbBool
rfbSendFramebufferUpdate(rfbClientPtr cl,
                         sraRegionPtr givenUpdateRegion)

**Comment by bk138** [comment]
That is in rfbserver.c. HTH!

**Comment by dobber1611** [comment]
Thanks for the recommendation. I see that the frames are sent in rfbWriteExact the socket.c, and that it will send the frame data in pieces, if we understand the method correctly. Is there a place where we can access  the full frame that will be sent across? We are trying to generate a digest on the frame, and need access to the whole frame data.

**Comment by bk138** [comment]
You mean contents of the whole framebuffer? That is almost never sent
completely, only if the client requests it IIRC. Most of the time, partial
updates are sent.

**Comment by dobber1611** [comment]
The partial updates are all I need. Basically, I would like the frame update data that is being sent to the client, whether its an rectangle, full frame, etc. Currently we are looking in rfbWriteExact, which stores the message buffer that will be sent, but that also includes header data. We would like to know where the frame is stored without the header data. Does that make more sense? Sorry for the confusion.

Perhaps an explanation what I'm trying to do will help. I am trying to generate a sha256 digest on the frame data that are being sent to the client. There the client will also generate a digest, and send it back, for verification that the data being displayed on the client are correct. 

Once again, thanks for your help.

**Comment by bk138** [comment]
Am Sun, 23 Oct 2016 15:21:05 -0700
schrieb dobber1611 <notifications@github.com>:

> Thanks for the recommendation. I see that the frames are sent in
> rfbWriteExact the socket.c, and that it will send the frame data in pieces,
> if we understand the method correctly. Is there a place where we can access
> the full frame that will be sent across? We are trying to generate a digest
> on the frame, and need access to the whole frame data.
> 

You mean contents of the whole framebuffer? That is almost never sent
completely, only if the client requests it IIRC. Most of the time, partial
updates are sent.
