### ISSUE TITLE
unable to connect to realVnc on a Pi

### ISSUE THREAD

**Issue by tomchiverton** [LibVNC/libvncserver#135]
Downstream discussion 
https://bugs.kde.org/show_bug.cgi?id=369545
points at a bug here.

**Comment by qraynaud** [comment]
I'm still having this issue!

**Comment by bk138** [comment]
Please provide some more context info :-)

**Comment by bk138** [comment]
Maybe someone wants to fund this issue on https://issuehunt.io/r/LibVNC/libvncserver/issues/135 ...

**Comment by giox069** [comment]
The RealVNC server installed on a RPi, by default only support authentication types `5,6,13,130,192`.
According to [RFC6143](https://tools.ietf.org/html/rfc6143#section-8.1.2), they all are RealVNC reserved values.

As reported [here](https://raspberrypi.stackexchange.com/questions/63586/how-to-set-vnc-security-settings-using-ssh-no-security-types-supported-server), you can configure the RaspberryPi RealVNC server to use VncAuth (2), by editing
/root/.vnc/config.d/vncserver-x11 . This will make the RealVNC server compatible with LibVNC.

RealVNC has a list of their authentication types [here](https://help.realvnc.com/hc/en-us/articles/360002251297-VNC-Server-Parameter-Reference-#Authentication). But I cannot find any protocol documentation/specification on their site.

Which authentication types does libvnc support other than VncAuth (2) ?

Cc: @antenore

**Comment by bk138** [comment]
> Which authentication types does libvnc support other than VncAuth (2) ?

https://github.com/LibVNC/libvncserver/blob/49880e33ee430d50804f46c307bcadce5b3e3be2/rfb/rfbproto.h#L275

**Comment by giox069** [comment]
Then in https://github.com/LibVNC/libvncserver/blob/master/libvncclient/rfbproto.c#L987 only a subset is implemented. I collected InitialiseRFBConnection() supported values in this table:
|#define symbol|value|notes|
|---|---|---|
|rfbNoAuth|1||
|rfbVncAuth|2||
|rfbSASL|20|Only when compiled with SASL||
|rfbMSLogon|0xfffffffa||
|rfbARD|30||
|rfbTLS|18||
|rfbVeNCrypt1|9||

Unfortunately, there is no match with the values supported out of the box by RealVNC Raspberry Pi installation (5,6,13,130,192).

Unfortunately without 5,6,13,130,192 authentication types protocol documentation, nothing can be done.

**Comment by bk138** [comment]
Seems like it :-/. But thanks for the digging and that table!

**Comment by bk138** [comment]
@tomchiverton please try the "downgrading VNC Server's authentication scheme" instructions mentioned in https://www.raspberrypi.org/documentation/remote-access/vnc/ :

>   Open the /root/.vnc/config.d/vncserver-x11 config file.
>    Replace Authentication=SystemAuth with Authentication=VncAuth and save the file.
>   In the command line, run sudo vncpasswd -service. This will prompt you to set a password, and will insert it for you in the right config file for VNC Server running in Service Mode.
>    Restart VNC Server.

**Comment by bk138** [comment]
Tentatively closing, please re-open if the issue persists.
