### ISSUE TITLE
configure: WARNING: ws2tcpip.h: present but cannot be compiled

### ISSUE THREAD

**Issue by Lee-Feng** [LibVNC/libvncserver#136]
When I run  ./autogen.sh for libvncserver-LibVNCServer-0.9.10,I met this WARN:
configure: WARNING: ws2tcpip.h: present but cannot be compiled
configure: WARNING: ws2tcpip.h:     check for missing prerequisite headers?
configure: WARNING: ws2tcpip.h: see the Autoconf documentation
configure: WARNING: ws2tcpip.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ws2tcpip.h: proceeding with the compiler's result
configure: WARNING:     ## -----------------------------------------------------                       ##
configure: WARNING:     ## Report this to https://github.com/LibVNC/libvncserver                       ##
configure: WARNING:     ## -----------------------------------------------------                       ##

**Comment by jiulongw** [comment]
I had same issue and fixed by adding `-D__USE_W32_SOCKETS` into CPPFLAGS.

e.g.
```
CPPFLAGS="-DWINVER=0x0501 -D__USE_W32_SOCKETS" ./autogen.sh
```

**Comment by jiulongw** [comment]
I had same issue and was fixed by adding `-D__USE_W32_SOCKETS` to `CPPFLAGS`.

**Comment by bk138** [comment]
@jiulongw Care to provide a PR?

**Comment by jiulongw** [comment]
@bk138 There's no PR for this... Simply run:

```
CPPFLAGS="-DWINVER=0x0501 -D__USE_W32_SOCKETS" ./autogen.sh
```

Whilst this solves sw2tcpip.h issue, I still have other issues building libvncserver for windows platform (using msys2 with necessary dependencies)...

**Comment by bk138** [comment]
Pls refer to https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml for the time being and feel free to re-open if you have questions
