### ISSUE TITLE
Internet Explorer 11 with noVNC not working

### ISSUE THREAD

**Issue by strgue** [LibVNC/libvncserver#139]
hello,

the latest version (also some older versions) of noVnc is not working with IE11 and libvncserver 0.9.10.
with firefox i had no problems.
please see the attached error messages.

![ie11-konsole](https://cloud.githubusercontent.com/assets/23237020/20591160/6aab67de-b227-11e6-9b17-4e0cb7941a37.png)

**Comment by bk138** [comment]
Well, then pls file a bug over at https://github.com/kanaka/noVNC ;-)

**Comment by strgue** [comment]
they wrote it's a problem of libvncserver :-)

**Comment by bk138** [comment]
Can you post the link of the issue over there pls?

**Comment by strgue** [comment]
https://groups.google.com/forum/#!msg/novnc/BnqUeQOhBz0/z3omqN2EAAAJ

**Comment by strgue** [comment]
another new issue:
https://github.com/kanaka/noVNC/issues/723

**Comment by bk138** [comment]
OK got it. Posting this here for reference: https://groups.google.com/d/msg/novnc/BnqUeQOhBz0/7cpgxtCbAAAJ

**Comment by bk138** [comment]
Can you pls check if 65106d39627499ace4f1ed8701d3ab6c7f97f56f fixes the issue?

**Comment by strgue** [comment]
thx.
i will check it on friday.

**Comment by strgue** [comment]
can you please send me a patch file (guenter.strubreiter@sigmatek.at).
i have to build it with yocto.

**Comment by bk138** [comment]
Here: 65106d39627499ace4f1ed8701d3ab6c7f97f56f

**Comment by samhed** [comment]
> Can you pls check if 65106d3 fixes the issue?

The idea behind it seems to work, but a small mistake (#142) caused the http server to break. With that fix, svg and css files work fine and I don't run into any problems using the latest master of noVNC.

**Comment by strgue** [comment]
in my case the patch is not working.
i got the same result as shown in my first post.
i saw somtimes that we use version 0.9.10-r2.
i think that is an older version...
could that be the problem?
or should the patch also work with version 0.9.10-r2?

**Comment by bk138** [comment]
if it applies...

**Comment by samhed** [comment]
@strgue I'm sure this patch works with the latest master. Should work with Did you rebuild after the changes? Did you clear your browser cache?

Is there any specific reason to why you aren't using newer code?

**Comment by strgue** [comment]
i do not know if there is a reason for using this particular version.
it's an embeded project and i am new to it.
i made a complete build and also deleted the cache and everything else of ie.
