### ISSUE TITLE
How to build for windows? OpenSSL library do not generate Libeay.lib file

### ISSUE THREAD

**Issue by mrsaleh** [LibVNC/libvncserver#143]
I used cmake for building for windows but there are but as the title said openssl library does not generate libeay.lib file. and there were an invalid -W parameter error that i fixed with modifying CMAKEFILE
I want to build with visual studio 2015

**Comment by bk138** [comment]
Pls see  https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml for a build setup that builds with OpenSSL as you can see at https://ci.appveyor.com/project/bk138/libvncserver/build/1.0.99. Feel free to re-open if questions remaining.
