### ISSUE TITLE
may i no how to build to windows 3Q 

### ISSUE THREAD

**Issue by truthhk** [LibVNC/libvncserver#144]
i tried cmake but many error ,so ,who build successful ？ can teach me ?3q very much

**Comment by bk138** [comment]
0.9.12 release will have a super easy build process

**Comment by truthhk** [comment]
0.9.12  hwo to download ? 3Q

**Comment by bk138** [comment]
0.9.12 is future tech ;-) -> https://github.com/LibVNC/libvncserver/milestone/4

**Comment by bk138** [comment]
Please see https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml for how the CI does it. Feel free to re-open if you have questions.
