### ISSUE TITLE
Android cursor movement

### ISSUE THREAD

**Issue by khaustov1** [LibVNC/libvncserver#146]
Everything's okay until client send mouse actions. Freezes while moving cursor on client side if I use normal connection and closes connection if using reverse connection. I'm running server on android device

**Comment by bk138** [comment]
Some logs would be nice ;-)

And: does the server process key events?

**Comment by khaustov1** [comment]
Crash with this log
Pixel format for client 10.10.10.103:
12-13 16:14:42.306 5169-5169/? E/KHAUSTOV VNC:   114 bpp, depth 118, big endian
12-13 16:14:42.306 5169-5169/? E/KHAUSTOV VNC:   uses a colour map (not true colour).
12-13 16:14:42.306 5169-5169/? E/KHAUSTOV VNC: rfbSetTranslateFunction: client bits per pixel not 8, 16 or 32

**Comment by bk138** [comment]
Is that the full server log?

**Comment by khaustov1** [comment]
Nope, I've change client option for displaying cursor to false. And now it falls with this error

12-13 16:43:22.961 22561-22562/? E/KHAUSTOV VNC: buttonMask = 0x1, x=296, y=270, prev_x=311, prev_y=995, clicked=0
12-13 16:43:23.064 22561-22562/? E/KHAUSTOV VNC: buttonMask = 0x0, x=296, y=270, prev_x=296, prev_y=270, clicked=1
12-13 16:43:26.625 22561-22562/? E/KHAUSTOV VNC: buttonMask = 0x1, x=546, y=908, prev_x=296, prev_y=270, clicked=0
12-13 16:43:26.733 22561-22562/? E/KHAUSTOV VNC: buttonMask = 0x0, x=546, y=908, prev_x=546, prev_y=908, clicked=1
12-13 16:43:27.441 22561-22561/? E/KHAUSTOV VNC: buttonMask = 0x0, x=545, y=907, prev_x=546, prev_y=908, clicked=1
12-13 16:43:29.902 22561-22561/? E/KHAUSTOV VNC: buttonMask = 0x1, x=29185, y=24325, prev_x=546, prev_y=908, clicked=0
12-13 16:43:29.902 22561-22562/? E/KHAUSTOV VNC: Pixel format for client 10.10.10.103:
12-13 16:43:29.902 22561-22562/? E/KHAUSTOV VNC:   1 bpp, most sig bit in each byte is leftmost on the screen.
12-13 16:43:29.902 22561-22562/? E/KHAUSTOV VNC: rfbSetTranslateFunction: client has colour map but 32-bit - can only cope with 8-bit colour maps
12-13 16:43:29.903 22561-22562/? E/KHAUSTOV VNC: Client 10.10.10.103 gone
12-13 16:43:29.903 22561-22562/? E/KHAUSTOV VNC: Statistics             events    Transmit/ RawEquiv ( saved)
12-13 16:43:29.903 22561-22562/? E/KHAUSTOV VNC:  FramebufferUpdate   :     83 |         0/        0 (  0.0%)
12-13 16:43:29.903 22561-22562/? E/KHAUSTOV VNC:  LastRect            :     83 |       996/      996 (  0.0%)
12-13 16:43:29.903 22561-22562/? E/KHAUSTOV VNC:  tight               :   5415 |   2876567/204045780 ( 98.6%)
12-13 16:43:29.903 22561-22562/? E/KHAUSTOV VNC:  PointerPos          :      1 |        12/       12 (  0.0%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  RichCursor          :      1 |       255/      255 (  0.0%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  TOTALS              :   5583 |   2877830/204047043 ( 98.6%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC: Statistics             events    Received/ RawEquiv ( saved)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  PointerEvent        :    424 |      2544/     2544 (  0.0%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  FramebufferUpdate   :     83 |       830/      830 (  0.0%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  SetPixelFormat      :      2 |        40/       40 (  0.0%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  SetEncodings        :      1 |        48/       48 (  0.0%)
12-13 16:43:29.904 22561-22562/? E/KHAUSTOV VNC:  TOTALS              :    510 |      3462/     3462 (  0.0%)

**Comment by bk138** [comment]
What's the LibVNCServer version there? 

Does the server process key events?

**Comment by khaustov1** [comment]
>Does the server process key events?
Yes
>What's the LibVNCServer version there?
The last version from github

**Comment by khaustov1** [comment]
So, keyboard runs ok, it happens only if mouse position changed or mouse click produced

**Comment by bk138** [comment]
A working Android VNC server application is now available at https://github.com/bk138/droidVNC-NG and open for contributions!
