### ISSUE TITLE
Bump CMake SOVERSION to 1?

### ISSUE THREAD

**Issue by bk138** [LibVNC/libvncserver#149]

**Comment by bk138** [comment]
@cinemast I saw that autotools use SOVERSION 1 since 344264da2facfd2ffba4e2f567be6d2c14b6d63b, so CMake should use SOVERSION 1 as well?

**Comment by cinemast** [comment]
Yes, please.

**Comment by cinemast** [comment]
Additionally, from a packaging perspective, I would prefer to have only one build system for the project. Keeping both in sync is usually a tedious task.

**Comment by bk138** [comment]
Yes, the plan is to switch to CMake for 0.9.12. FYI :-)
