### ISSUE TITLE
How to build libvncserver for 64bit android6.0

### ISSUE THREAD

**Issue by snow-he** [LibVNC/libvncserver#150]
I found a libvncserver dir in the source code of android6.0. The dir path is "android/external/libvncserver". Can you tell me how to build it?

**Comment by bk138** [comment]
There is some doc at libvnc.github.io, but we will switch to CMake soonish so that'll change.

**Comment by snow-he** [comment]
thank you very much~

**Comment by magicseth** [comment]
Is there any documentation on using CMake for this?

**Comment by bk138** [comment]
@magicseth not yet  - care to try out and create some? http://www.vtk.org/Wiki/CMake_Cross_Compiling could be a good start

**Comment by bk138** [comment]
https://developer.android.com/ndk/guides/cmake.html looks good to me

**Comment by bk138** [comment]
Closed by 80ad74f7613d7d790a5152ee377af361ecd3ff9b
