### ISSUE TITLE
Can't build on Ubuntu

### ISSUE THREAD

**Issue by pmcfernandes** [LibVNC/libvncserver#155]
Hi

I trying to build using master branch and .,/autogen.sh but on shell give me this error:

checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ar... (cached) ar
checking for __b64_ntop... no
checking for __b64_ntop in -lresolv... yes
./configure: line 12250: syntax error near unexpected token `LIBSYSTEMD,'
./configure: line 12250: `PKG_CHECK_MODULES(LIBSYSTEMD, libsystemd, with_systemd=1, with_systemd=0)'

Some help please.

**Comment by bk138** [comment]
pls try
`
mkdir build
cd build
cmake ..
make
`

**Comment by pmcfernandes** [comment]
Yes. It works after upgrade to cmake 3.4

Thanks

**Comment by bk138** [comment]
Then you can push the "Close" button? ;-)
