### ISSUE TITLE
error: invalid conversion from ‘void*’ to ‘ClientData*’ [-fpermissive]     ClientData* cd=cl->clientData;                        ^

### ISSUE THREAD

**Issue by molavy** [LibVNC/libvncserver#157]
on compile example.c 
i get this error :
 error: invalid conversion from ‘void*’ to ‘ClientData*’ [-fpermissive]
    ClientData* cd=cl->clientData;
                       ^
in this line:
 ClientData* cd=cl->clientData;

**Comment by The-42** [comment]
I'd guess a missing cast, but your report is a bit lacking ;) What system are you building on? How did you invoke the build system? Which compiler did you use?

**Comment by molavy** [comment]
uname -a
Linux user-desktop 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 

cmake --version
cmake version 3.7.2

**Comment by The-42** [comment]
You don't happen to compile with a C++ compiler, do you? This type of of construct is only illegal in C++, not in C. When using a C compiler, things compile fine - and warnings about those conversions only ever show up when including `-Wc++-compat` in CFLAGS, which should be telling...

**Comment by bk138** [comment]
@molavy can you pls provide a full build log?

**Comment by bk138** [comment]
As there was no answer in 2 weeks, I am closing this. feel free to reopen if issue persists.
