### ISSUE TITLE
Websockets: time to drop Hixie, base64 and the Flash library (and greatly simplify the code)

### ISSUE THREAD

**Issue by kanaka** [LibVNC/libvncserver#162]
The old Hixie protocol was dropped from websockify on Jun 2013: https://github.com/novnc/websockify/commit/264f8fdd7f12bd5b9f6813fb8de81c55b6328d9b

We continued to support base64 encoding in noVNC for a bit longer because some browsers added HyBi support without binary encoding. Base64 (and the flash fallback websocket library) was dropped from noVNC on May 2015: https://github.com/novnc/noVNC/commit/38781d931ec18304f51ed3469faff8387e3cbc55

I would suggest dropping base64 rather than adding additional cross-platform base64 support as suggested in: https://github.com/LibVNC/libvncserver/pull/161

Supporting Hixie and Base64 encoded data in the server adds a lot of complication to the code and the additional browser market share supported by this is probably now less than 1% (http://caniuse.com/#search=websockets)

You might also consider upgrading to a more recent noVNC client (as suggested by this issue:  https://github.com/LibVNC/libvncserver/issues/148). However, note that this will decrease the cross-browser support slightly (probably still less than 5% unsupported) due to our requirement for modern browsers (especially full Typed Array support). However, there are some major improvements to noVNC since it was pulled into libvncserver including performance enhancements and a much better UI.

**Comment by andwei** [comment]
I'm currently working on cleaning up and fixing the websockets part (removing Hixie in the process). Please stay tuned.

**Comment by bk138** [comment]
great great! i was about to ask who's up for a PR ;-) thanks to @andwei

**Comment by bk138** [comment]
@kanaka would removing base64 support mean ignoring them WS_OPCODE_TEXT_FRAME's ? Do you have some data on which browsers do *not* support HyBi with binary payloads?

**Comment by kanaka** [comment]
@bk138 I wouldn't ignore them. If you get a text frame that's a network protocol error and it should terminate the connection and log an error. caniuse.com has pretty good data for this sort of thing. All modern browser releases support binary data in WebSockets. Firefox 4-10, Chrome 15, and Safari 6.x had partial implementations of WebSockets that lacked binary support. The total usage of those browser versions according to caniuse is well under 1%.

**Comment by bk138** [comment]
@kanaka 2 more questions:

first one: how do you see support for binary websockets from https://caniuse.com/#search=websockets ? can't seem to find it :-/ 

2nd one: can you give me a hint what that sha1-in-base-64 generation is for - I am not so fit in websockets stuff ;-)

**Comment by kanaka** [comment]
@bk138 click on the "Show all" button. The old browsers marked with #2 are the ones that have the modern HyBi protocol without the binary support.

The base64 encoding of a SHA-1 hash is a part of the handshake. Search for SHA-1 in the [IETF WebSockets standard](https://tools.ietf.org/html/rfc6455). It's basically used by the client to verify that the server really is a WebSocket server and is not just some broken web server echoing back requests (or replaying previous sessions). I.e. the client is asking the server to do some computation work that is very specific to the websocket handshake and only if the server responds with the correct (per session) value will the client continue with the connection.

**Comment by bk138** [comment]
@kanaka If a base64-coded sha1 is needed for WebSockets to work, how this relate to your suggestion to remove base64 support entirely in https://github.com/LibVNC/libvncserver/pull/161 ?

**Comment by kanaka** [comment]
@bk138 Ah, I had forgotten about the other use of base64 when I said that. It is in fact necessary for WebSocket support.

**Comment by bk138** [comment]
- [x] remove hixie : a2322e70069b30fb4f86248d6a6bce6d2a9c11e1

- [ ] remove base64: 

- [ ] remove flash
