### ISSUE TITLE
android libvncserver exec error: only position independent executables (PIE) are supported

### ISSUE THREAD

**Issue by Moisi** [LibVNC/libvncserver#166]
Hi, 

Issue:
while executing androidvncserver. I got:
```
$ adb shell /data/local/androidvncserver 
error: only position independent executables (PIE) are supported.
```

Solution:

instead of using the line from the README: `./configure --host=arm-eabi CC=arm-linux-androideabi-gcc`

use the following(added ccflags and ldflags):
```
./configure --host=arm-eabi CC=arm-linux-androideabi-gcc CCFLAGS=-fPIE
 LDFLAGS=-pie
```

**Comment by bk138** [comment]
Hi @Moisi did you try with CMake? This is the only officially support build system as of now but needs some love: https://github.com/LibVNC/libvncserver/issues/150

**Comment by bk138** [comment]
Also, your issue got a solution, it seems. Closing this one. Thank you!
