### ISSUE TITLE
(fastdriod-vnc) rfbCheckFds: select: Invalid argument

### ISSUE THREAD

**Issue by sandeep-0511** [LibVNC/libvncserver#167]
Hi,
issue:
while executing androidvncserver. I got 
error: only position independent executables (PIE) are supported.
Added the Follwing Flags in Android.mk
LOCAL_CFLAGS += -fPIE
LOCAL_LDFLAGS += -fPIE -pie
After that when i run 

 adb shell /data/landroidvncserver

rfbCheckFds: select: Invalid argument
rfbCheckFds: select: Invalid argument
rfbCheckFds: select: Invalid argument
rfbCheckFds: select: Invalid argument
rfbCheckFds: select: Invalid argument
above error throwing Continuously.
** Compiling For Lollipop5.1

Thanks and Regards,
Sandeep v

**Comment by bk138** [comment]
@sandeep-0511 can you elaborate on how you're building for Android and maybe help with https://github.com/LibVNC/libvncserver/issues/150 so we can tackle this issue together?

**Comment by bk138** [comment]
As there was no answer in 2 weeks, I am closing this. feel free to reopen if issue persists.

**Comment by jiaochuandong** [comment]
Hi bk138
I have some error, like this:
cat fbvncserver.c
/* default input device paths */
static char KBD_DEVICE[PATH_MAX] = "/dev/input/event2";
static char TOUCH_DEVICE[PATH_MAX] = "/dev/input/event1";




root@rk3288_box:/data/local # ./fastdroid-vnc
...
02/02/2018 13:01:12 rfbCheckFds: select: Invalid argument
02/02/2018 13:01:12 rfbCheckFds: select: Invalid argument
02/02/2018 13:01:12 rfbCheckFds: select: Invalid argument

after that: 
I use the  commends
 root@rk3288_box:/data/local # ./fastdroid-vnc -t /dev/input/event1 &
root@rk3288_box:/data/local # Found input device /dev/input/event1 by keyword key
Found input device /dev/input/event4 by keyword touch
Initializing framebuffer device /dev/graphics/fb0...
xres=720, yres=1280, xresv=720, yresv=3840, xoffs=0, yoffs=0, bpp=32
Initializing keyboard device /dev/input/event1 ...
Initializing touch device /dev/input/event1 ...
cannot get ABS_X info, Invalid argument

I search ABS_X on google, but I don't know what's wrong with fastdroid-vnc. even I don't know what's mean with ABS_X.

could you give me some advice?
os is android5.1.1 (Lollipop5.1)

Thank you 
chuandong
