### ISSUE TITLE
some one can build successed with cmake use mingw in win7-64? It  also depends on what libraries?

### ISSUE THREAD

**Issue by lfjking** [LibVNC/libvncserver#168]
I add the zlib and libjepg Source code here.
and use cmake gui build with codeblocks_minGW.
but can't build successed too.
 It  also depends on what libraries?

cmake configure log:
The C compiler identification is GNU 4.9.2
The CXX compiler identification is GNU 4.9.2
Check for working C compiler: D:/CodeBlocks/MinGW/bin/gcc.exe
Check for working C compiler: D:/CodeBlocks/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: D:/CodeBlocks/MinGW/bin/g++.exe
Check for working CXX compiler: D:/CodeBlocks/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find ZLIB (missing:  ZLIB_INCLUDE_DIR) 
Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR) 
Performing Test FOUND_LIBJPEG_TURBO
Performing Test FOUND_LIBJPEG_TURBO - Failed
CMake Warning at CMakeLists.txt:89 (message):
  *** The libjpeg library you are building against is not libjpeg-turbo.
  Performance will be reduced.  You can obtain libjpeg-turbo from:
  https://sourceforge.net/projects/libjpeg-turbo/files/ ***

Could NOT find ZLIB (missing:  ZLIB_INCLUDE_DIR) 
Could NOT find PNG (missing:  PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - found
Found Threads: TRUE  
Could NOT find SDL (missing:  SDL_LIBRARY SDL_INCLUDE_DIR) 
Could NOT find GnuTLS (missing:  GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) 
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Looking for endian.h
Looking for endian.h - not found
Looking for fcntl.h
Looking for fcntl.h - found
Looking for netinet/in.h
Looking for netinet/in.h - not found
Looking for sys/endian.h
Looking for sys/endian.h - not found
Looking for sys/socket.h
Looking for sys/socket.h - not found
Looking for sys/stat.h
Looking for sys/stat.h - found
Looking for sys/time.h
Looking for sys/time.h - found
Looking for sys/types.h
Looking for sys/types.h - found
Looking for sys/wait.h
Looking for sys/wait.h - not found
Looking for unistd.h
Looking for unistd.h - found
Looking for sys/uio.h
Looking for sys/uio.h - not found
Looking for vfork.h
Looking for vfork.h - not found
Looking for ws2tcpip.h
Looking for ws2tcpip.h - found
Looking for arpa/inet.h
Looking for arpa/inet.h - not found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Looking for sys/types.h
Looking for sys/types.h - found
Looking for gettimeofday
Looking for gettimeofday - found
Looking for vfork
Looking for vfork - not found
Looking for vprintf
Looking for vprintf - found
Looking for __b64_ntop
Looking for __b64_ntop - not found
Looking for __b64_ntop
Looking for __b64_ntop - not found
Check size of pid_t
Check size of pid_t - done
Check size of size_t
Check size of size_t - done
Check size of socklen_t
Check size of socklen_t - failed
Check size of in_addr_t
Check size of in_addr_t - failed
Check if the system is big endian
Searching 16 bit integer
Check size of unsigned short
Check size of unsigned short - done
Using unsigned short
Check if the system is big endian - little endian
Configuring done

------------------------------------------------------------------------------------
Whether I need  build  alone each one with libjpeg. libpng. libzib 
Can be used only after compilation?

**Comment by lfjking** [comment]
Now, I follow the method of using documents.
Use the VS2010 cmake command line.
Still unable to build success.

**Comment by bk138** [comment]
Really, pls post some log files. It's hard guessing by looking into the magic glass ball.

**Comment by lfjking** [comment]
# @bk138 

i  pause the log  on  #1 
Trouble help look, thanks

**Comment by bk138** [comment]
Looks okay to me. What do the build logs say?

**Comment by bk138** [comment]
No response within 2 weeks, closing now. Feel free to re-open if the issue persists!

**Comment by TianLuhua** [comment]
I also encountered the same problem 
Compiler Environment：
    ubuntu 14.04
    cmake version：3.4.1Performing C SOURCE FILE Test FOUND_LIBJPEG_TURBO failed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c0adc/fast"
/usr/bin/make -f CMakeFiles/cmTC_c0adc.dir/build.make CMakeFiles/cmTC_c0adc.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c0adc.dir/src.c.o
/usr/bin/cc    -DFOUND_LIBJPEG_TURBO -IJPEG_INCLUDE_DIR-NOTFOUND   -o CMakeFiles/cmTC_c0adc.dir/src.c.o   -c /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/src.c
/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/src.c:5:23: fatal error: jpeglib.h: No such file or directory
compilation terminated.
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
make[1]: *** [CMakeFiles/cmTC_c0adc.dir/src.c.o] Error 1
make: *** [cmTC_c0adc/fast] Error 2

Return value: 1
Source file was:


  #include <stdio.h>

  #include <jpeglib.h>

  int main(void) {

    struct jpeg_compress_struct cinfo;

    struct jpeg_error_mgr jerr;

    cinfo.err=jpeg_std_error(&jerr);

    jpeg_create_compress(&cinfo);

    cinfo.input_components = 3;

    jpeg_set_defaults(&cinfo);

    cinfo.in_color_space = JCS_EXT_RGB;

    jpeg_default_colorspace(&cinfo);

    return 0;

  }
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b49d5/fast"
/usr/bin/make -f CMakeFiles/cmTC_b49d5.dir/build.make CMakeFiles/cmTC_b49d5.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b49d5.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_b49d5.dir/CheckSymbolExists.c.o   -c /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_b49d5
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b49d5.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_b49d5.dir/CheckSymbolExists.c.o  -o cmTC_b49d5 
CMakeFiles/cmTC_b49d5.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: ld returned 1 exit status
make[1]: *** [cmTC_b49d5] Error 1
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
make: *** [cmTC_b49d5/fast] Error 2

File /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_02c54/fast"
/usr/bin/make -f CMakeFiles/cmTC_02c54.dir/build.make CMakeFiles/cmTC_02c54.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_02c54.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_02c54.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.4/Modules/CheckFunctionExists.c
Linking C executable cmTC_02c54
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_02c54.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_02c54.dir/CheckFunctionExists.c.o  -o cmTC_02c54 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: ld returned 1 exit status
make[1]: *** [cmTC_02c54] Error 1
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
make: *** [cmTC_02c54/fast] Error 2


Determining if the include file sys/endian.h exists failed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_360aa/fast"
/usr/bin/make -f CMakeFiles/cmTC_360aa.dir/build.make CMakeFiles/cmTC_360aa.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_360aa.dir/CheckIncludeFile.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_360aa.dir/CheckIncludeFile.c.o   -c /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:24: fatal error: sys/endian.h: No such file or directory
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_360aa.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
make: *** [cmTC_360aa/fast] Error 2


Determining if the include file vfork.h exists failed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_24193/fast"
/usr/bin/make -f CMakeFiles/cmTC_24193.dir/build.make CMakeFiles/cmTC_24193.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_24193.dir/CheckIncludeFile.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_24193.dir/CheckIncludeFile.c.o   -c /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:19: fatal error: vfork.h: No such file or directory
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_24193.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
make: *** [cmTC_24193/fast] Error 2


Determining if the include file ws2tcpip.h exists failed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_48a06/fast"
/usr/bin/make -f CMakeFiles/cmTC_48a06.dir/build.make CMakeFiles/cmTC_48a06.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_48a06.dir/CheckIncludeFile.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_48a06.dir/CheckIncludeFile.c.o   -c /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:22: fatal error: ws2tcpip.h: No such file or directory
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_48a06.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
make: *** [cmTC_48a06/fast] Error 2


Determining if the system is big endian passed with the following output:
Change Dir: /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_aa0b7/fast"
/usr/bin/make -f CMakeFiles/cmTC_aa0b7.dir/build.make CMakeFiles/cmTC_aa0b7.dir/build
make[1]: Entering directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_aa0b7.dir/TestEndianess.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_aa0b7.dir/TestEndianess.c.o   -c /home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp/TestEndianess.c
Linking C executable cmTC_aa0b7
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_aa0b7.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_aa0b7.dir/TestEndianess.c.o  -o cmTC_aa0b7 
make[1]: Leaving directory `/home/tianluhua/work/sc9832_m/sc9832_m/external/libvncserver-master/CMakeFiles/CMakeTmp'

TestEndianess.c:
/* A 16 bit integer is required. */
typedef unsigned short cmakeint16;

/* On a little endian machine, these 16bit ints will give "THIS IS LITTLE ENDIAN."
   On a big endian machine the characters will be exchanged pairwise. */
const cmakeint16 info_little[] =  {0x4854, 0x5349, 0x4920, 0x2053, 0x494c, 0x5454, 0x454c, 0x4520, 0x444e, 0x4149, 0x2e4e, 0x0000};

/* on a big endian machine, these 16bit ints will give "THIS IS BIG ENDIAN."
   On a little endian machine the characters will be exchanged pairwise. */
const cmakeint16 info_big[] =     {0x5448, 0x4953, 0x2049, 0x5320, 0x4249, 0x4720, 0x454e, 0x4449, 0x414e, 0x2e2e, 0x0000};

#ifdef __CLASSIC_C__
int main(argc, argv) int argc; char *argv[];
#else
int main(int argc, char *argv[])
#endif
{
  int require = 0;
  require += info_little[argc];
  require += info_big[argc];
  (void)argv;
  return require;
}


Looking forward to your help.
