### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by aMASKed** [LibVNC/libvncserver#171]
Hello,

At the whole day I'm trying to build libvncserver - master using VS 2015.  Followed every step (available here: https://ci.appveyor.com/project/bk138/libvncserver/build/1.0.120/job/38qf1ip22e9cfaut) but I have more than 335 errors at the end.
First of them: 

`vncclient.lib(rfbproto.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_std_error rÚfÚrencÚ dans la fonction _
DecompressJpegRect16 [C:\projects\libvncserver\build\client_examples_backchannel.vcxproj]`

However build of libpng and zlib works without issue.

Someone would know or is the problem ? Thank you

**Comment by bk138** [comment]
A full build log would be helpful ;-)

But it seems you're linking to libjpeg and it's not there.

**Comment by aMASKed** [comment]
I think you're right ... Every error talked abou : jpeg 
I just installed libjpeg-turbo-1.5.1-gcc.exe but I've exactly the same errors
Which one I have to install ?

I can not put full build log because I'm limited in number of character, but every error is something like that

`vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_std_error rÚfÚrencÚ dans la fonction
__tjInitCompress [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_CreateCompress rÚfÚrencÚ dans la fonc
tion __tjInitCompress [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_CreateDecompress rÚfÚrencÚ dans la fo
nction __tjInitDecompress [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_destroy_compress rÚfÚrencÚ dans la fo
nction _tjDestroy [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_destroy_decompress rÚfÚrencÚ dans la
fonction _tjDestroy [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_set_defaults rÚfÚrencÚ dans la foncti
on _setCompDefaults [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_set_colorspace rÚfÚrencÚ dans la fonc
tion _setCompDefaults [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_set_quality rÚfÚrencÚ dans la fonctio
n _setCompDefaults [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_start_compress rÚfÚrencÚ dans la fonc
tion _tjCompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_write_scanlines rÚfÚrencÚ dans la fon
ction _tjCompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_finish_compress rÚfÚrencÚ dans la fon
ction _tjCompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_read_header rÚfÚrencÚ dans la fonctio
n _tjDecompressHeader2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_start_decompress rÚfÚrencÚ dans la fo
nction _tjDecompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_read_scanlines rÚfÚrencÚ dans la fonc
tion _tjDecompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_finish_decompress rÚfÚrencÚ dans la f
onction _tjDecompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_abort_compress rÚfÚrencÚ dans la fonc
tion _tjCompress2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_abort_decompress rÚfÚrencÚ dans la fo
nction _tjDecompressHeader2 [C:\projects\libvncserver\build\examples_simple15.vcxproj]
vncserver.lib(turbojpeg.obj) : error LNK2019: symbole externe non rÚsolu _jpeg_resync_to_restart rÚfÚrencÚ dans la f
onction __tjInitDecompress [C:\projects\libvncserver\build\examples_simple15.vcxproj]`

Thank you

**Comment by bk138** [comment]
great great, you can also always close solved issues by yourself ;-)
