### ISSUE TITLE
Can this library to be LGPL? 

### ISSUE THREAD

**Issue by chinlin0924** [LibVNC/libvncserver#180]
Hi sir,

Is it possible to make the software as LGPL-based license?
Your library looks very good, but it can be LGPL, it would be better

**Comment by dscho** [comment]
Hi @chinlin0924,

this question comes up every once in a while, and the answer is always the same: contact all copyright holders (in particular RealVNC, who bought the copyrights from AT&T for the original Xvnc from whose source code LibVNCServer was derived). You have to ask them to relicense the source code as LGPL. Once you have all of their consent, the license can be changed.
