### ISSUE TITLE
please help how could i compile the libvncserver in ARM without using buildroot

### ISSUE THREAD

**Issue by mohammadalnatour** [LibVNC/libvncserver#182]

**Comment by bk138** [comment]
pls provide more info instead of just one sentence

**Comment by mohammadalnatour** [comment]
i have ARM  Linux environment embedded system and i'm trying to compile the libvncserver i don't want to use buildroot because the ARM is really old, so what can i do to compile libvncserver in my environment

**Comment by bk138** [comment]
does your ARM thingy have an OS as well? ;-) pls, it's really easier with some info

**Comment by mohammadalnatour** [comment]
yes it has ARM v5 Linux for BMC (baseboard management controller) we have java applet who connect with server and i want to change it with novnc web browser
