### ISSUE TITLE
rfbProcessClientProtocolVersion: not a valid RFB client: GET /websock 

### ISSUE THREAD

**Issue by mohammadalnatour** [LibVNC/libvncserver#187]
i'm trying to connect to vnc server by novnc and i get this message help please

**Comment by bk138** [comment]
_please_, give us some more detail!

**Comment by mohammadalnatour** [comment]
@bk138 i compiled the libvncserver for armv5 linux and every thing went well except that i wanted to try the (simple) example with novnc but i got this error  rfbProcessClientProtocolVersion: not a valid RFB client: GET /websock

**Comment by mohammadalnatour** [comment]
I think the problem is with websocket
