### ISSUE TITLE
in_addr_t in rfb/rfb.h redefine

### ISSUE THREAD

**Issue by Cordius** [LibVNC/libvncserver#189]
I use MinGW to build libvncserver on windows, and there is a error "in_addr_t is redefined in rfb/rfb.h +57, predefined in rfb/rfbproto.h +114".

**Comment by bk138** [comment]
Are you doing it the way the AppVeyor scripts are doing it? There it builds fine...

**Comment by bk138** [comment]
No response from OP since Sep. Closing for now. Pls re-open if issue persists.
