### ISSUE TITLE
Can't build without crypt junk

### ISSUE THREAD

**Issue by ab1jx** [LibVNC/libvncserver#192]
I configured by
./configure --without-crypt --without-crypto --without-ssl
and still I get:
  CC       libvncserver_la-websockets.lo
  CC       libvncserver_la-rfbssl_gnutls.lo
  CC       libvncserver_la-rfbcrypto_gnutls.lo
rfbcrypto_gnutls.c:25:20: fatal error: gcrypt.h: No such file or directory
 #include <gcrypt.h>
                    ^
compilation terminated.
Makefile:722: recipe for target 'libvncserver_la-rfbcrypto_gnutls.lo' failed

I don't have the dev stuff for the crypto because I never use it, and right now raspberrypi.org is doing some maintenance so I can't fetch it.

**Comment by dscho** [comment]
One word of really sincere advice: you may want to rethink the way you vent frustration at those who you ask to help you. You might be surprised just by how much this decreases your chances to get high quality help. As a rule of thumb, you probably want to be as polite as possible when asking for anything.

In this case, you switched off support for libcrypto (part of OpenSSL IIRC), and the compile error is in a file that requires GNU TLS. OpenSSL != GNU TLS. You may have been looking for `--without-gnutls` for that reason.

**Comment by ab1jx** [comment]
I get frustrated with overuse of security, I wouldn't use VNC except
behind a firewall or through a tunnel anyway.  I'm trying to use it
from upstairs to downstairs in a house in the boonies.  Behind a
firewall on a dynamic IP with NAT.  I probably thought gnutls was
gnuutils.  SSL is overused in places where it shouldn't be in general.
So it takes 4 --withouts to turn it all off?

I managed to get it working by tracking down and installing 3
individual files even though Synaptic wasn't working.  Already
mentioned it one place on Stack Exchange.

I think I also complained about your argc/argv use but I spent at
least an hour grepping your sources trying to figure out what values I
needed to put in there.  It never occurred to me you were just
demonstrating that you could pass argc and argv from the command line
in there.  I had to put in something or it wouldn't compile, except
you don't actually use them for anything so I couldn't figure out what
went in there.  But I got it eventually, played with it until about 2
AM afterwards.

On 7/25/17, Johannes Schindelin <notifications@github.com> wrote:
> One word of really sincere advice: you may want to rethink the way you vent
> frustration at those who you ask to help you. You might be surprised just by
> how much this decreases your chances to get high quality help. As a rule of
> thumb, you probably want to be as polite as possible when asking for
> anything.
>
> In this case, you switched off support for libcrypto (part of OpenSSL IIRC),
> and the compile error is in a file that requires GNU TLS. OpenSSL != GNU
> TLS. You may have been looking for `--without-gnutls` for that reason.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LibVNC/libvncserver/issues/192#issuecomment-317702102


-- 
-------------
No, I won't  call it "climate change", do you have a "reality problem"? - AB1JX
Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach

**Comment by dscho** [comment]
I understand your frustration. I simply think that it is counterproductive to blast it onto those who you ask for, and who want to provide, help. That's simply a hallmark of an ingrate.

> Already mentioned it one place on Stack Exchange.

There was no mention of any SE post prior to this sentence. If you already feel frustrated, maybe you want to avoid to impose the same feeling onto others.

> I also complained about your argc/argv use

You mean in a separate ticket, yes?

In any case, I think that does it for me for now. I hope that others chime in to help you resolve your remaining issues.

**Comment by ab1jx** [comment]
That wasn't blasting, that was just a little perturbed.

No, Stack Exchange was a favorable comment after I got it working.  In
a comment about doing graphics to a frame buffer which I thought were
the same as doing them to a malloced memory area then calling libjpeg
or libtiff or libpng to export as an image file.  Yes, it is the same.
Coming from OpenBSD to Linux I'm not used to having frame buffers.
Now I've built libvncserver under both.  I hadn't heard of it until I
was thinking there should be such a thing and mentioned it in a post
at raspberrypi.org to see if anybody had heard of one.

Yes, there's another ticket, haven't heard anything on that.  Just
something I considered unclear in documentation.  I did figure it out
after an hour or so.  I didn't find much documentation period except
what came out of Doxygen.  Quality of that varies from project to
project.  I usually look in the code first.

I really have no remaining issues, so far anyway.


On 7/25/17, Johannes Schindelin <notifications@github.com> wrote:
> I understand your frustration. I simply think that it is counterproductive
> to blast it onto those who you ask for, and who want to provide, help.
> That's simply a hallmark of an ingrate.
>
>> Already mentioned it one place on Stack Exchange.
>
> There was no mention of any SE post prior to this sentence. If you already
> feel frustrated, maybe you want to avoid to impose the same feeling onto
> others.
>
>> I also complained about your argc/argv use
>
> You mean in a separate ticket, yes?
>
> In any case, I think that does it for me for now. I hope that others chime
> in to help you resolve your remaining issues.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LibVNC/libvncserver/issues/192#issuecomment-317750221


-- 
-------------
No, I won't  call it "climate change", do you have a "reality problem"? - AB1JX
Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach

**Comment by bk138** [comment]
Hmm, so this can  be closed then?

**Comment by ab1jx** [comment]
Oh, yes I guess so.  I can't see how you couldn't take argc and argv
out of your function prototypes and be able to put them back easily if
you want them, it's just not clear that you don't need to use them for
anything.

Does this project have a forum?

I'm trying to figure out your use of 16-bit color, but I'm about to
try 8 bit.  I'm working on a little software defined radio project
which really doesn't need 24 or 32 bits per pixel.  Maybe VNC isn't
the best way to do this, being able to find a screenbuffer widget
would be adequate.  I'm looking for about 5-20 screen updates per
second and I can't predict where on the screen they need to be so
updating a rectangle isn't going to work very well.  I was trying to
figure out whether your 16 bit color was rgb565 or what so I fed a
ramp from 0 to 64k out thinking that would tell me.  I didn't expect
to get 12 greyscale ramps.  Since 65536 isn't evenly divisible by 12
I'm not sure why it happened like this.  I did the ramp on top of the
last frame of my signal.  Colors in the signal plot aren't quite what
I want but I'm using xor to erase old ones and put new ones on.  I've
mostly only done 8 or 24 bit color before, and with still images, not
a framebuffer.  I'm just doing offset = (y*width)+x type graphics to
write into framebuffer memory, clearscreen is a bzero.

On 7/30/17, Christian Beier <notifications@github.com> wrote:
> Hmm, so this can  be closed then?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LibVNC/libvncserver/issues/192#issuecomment-318933652


-- 
-------------
No, I won't  call it "climate change", do you have a "reality problem"? - AB1JX
Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach

**Comment by bk138** [comment]
@ab1jx for the colour question, feel free to open a new issue, there's no forum as of now. closing this one
