### ISSUE TITLE
Why argc and argv?

### ISSUE THREAD

**Issue by ab1jx** [LibVNC/libvncserver#193]
To me this is unclear in the documentation (what documentation?).  I know what argc and argv do well enough but what are you feeding in there?  Mostly I'd rather not use argc and argv at all, or have a good default if no arguments are supplied.

I'm looking at rfbGetScreen() in the headers and trying to figure out what the first 2 arguments to it do.  I'd set them up for IP address and port maybe but I have no idea what you're doing.

I finally figured out they don't do anything, apparently they're passed along to the user-written process the same way they are for command-line programs.

**Comment by bk138** [comment]
I guess it's historic reasons. And I won't change existing API. If you have a PR improving docs, I'll thankfully merge it.
