### ISSUE TITLE
successfully run on windows

### ISSUE THREAD

**Issue by whm200410** [LibVNC/libvncserver#195]
Dear all.
I made some modification on this project on windows and make it work fine.
1. make a define switch to use SOCKET type on windows
2. replace pthread/ with windows thread/mutex library.

anyone who wants it I can share with you, ping me at whm200410@163.com

**Comment by bk138** [comment]
Am Wed, 23 Aug 2017 01:23:32 +0000 (UTC)
schrieb whm200410 <notifications@github.com>:

> Dear all.
> I made some modification on this project on windows and make it work fine.
> 1. make a define switch to use SOCKET type on windows
> 2. replace pthread/ with windows thread/mutex library.
> 
> anyone who wants it I can share with you, ping me at whm200410@163.com
> 
> 

ping

**Comment by bk138** [comment]
Hi Christian.
What I can do for you




发自网易邮箱大师


On 8/23/2017 14:53，Christian Beier<christian.cb.beier@googlemail.com> wrote：
Am Wed, 23 Aug 2017 01:23:32 +0000 (UTC)
schrieb whm200410 <notifications@github.com>:

> Dear all.
> I made some modification on this project on windows and make it work fine.
> 1. make a define switch to use SOCKET type on windows
> 2. replace pthread/ with windows thread/mutex library.
> 
> anyone who wants it I can share with you, ping me at whm200410@163.com
> 
> 

ping

**Comment by bk138** [comment]
Well I'm referring to you initial message ;-) Please share the code with us :-)!

**Comment by bk138** [comment]
Great, I'll have a look when I've time. Job is eating all coding brain resources.

**Comment by aquawicket** [comment]
whm200410's source fixes my issues with windows.  And also addresses this issue. 
[https://github.com/LibVNC/libvncserver/issues/165](https://github.com/LibVNC/libvncserver/issues/165)

I can now compile a working server with CMake and MSVC :)

I imported **_/CMakelists.txt_** and **_/cmake/Modules_** from the original master branch.
I also commented out **_/rfb/rfbpronto.h line(68)_**   ` //#include <rfb/rfbconfig.h>`
CMake was able to generate build files and most examples compiled and ran just fine.

**OS: Windows 7 UE SP1 build 7601 x64
MSVC: 2015 14.0
CMake: 3.4.1
Viewer: VNC Viewer 6.17.731**

**Comment by whm200410** [comment]
I feel happy my post help you , thanks to the author, I can use it in my project.

**Comment by saurabhverma999** [comment]
![unbenannt1](https://user-images.githubusercontent.com/32668117/31818010-922cc2f8-b596-11e7-9988-a93d81fedaa5.PNG)



After downloading libvnc server for windows and commenting out <rfb/rfbconfig.h ......i am getting the following errors

**Comment by aquawicket** [comment]
I put the _#include <rfb/rfbconfig.h>_ back in, and added right include directory in the VC project.
It looks to me like you might be missing the zlib library.

**Comment by whm200410** [comment]
oh, yes,
 I download and compile the zlib on my own, you can do it also.




发自网易邮箱大师


On 10/24/2017 09:24，aquawicket<notifications@github.com> wrote：

I put the #include <rfb/rfbconfig.h> back in, and added right include directory in the VC project.
It looks to me like you might be missing the zlib library.

**Comment by whm200410** [comment]
when config the CMake project, make sure to config the zlib, png, jpg library path

**Comment by ChongDeng** [comment]
@whm200410  Hi, I wonder which files you have changed.
