### ISSUE TITLE
[Question] : Windows build support libvncserver websockets

### ISSUE THREAD

**Issue by gops4u** [LibVNC/libvncserver#196]
Hello,

Does the cmake windows build support websockets options?

I tried build using minw64-X86_64. The build was successful without web sockets, since i couldn't get the b64 functions and sys/uio.h in mingw64-X86_64.

With cmake as well, websockets are not enabled due to missing sys/uio.h file.

Any sugesstions?

**Comment by bk138** [comment]
No. Websockets support atm requires sys/uio.h which is not included in MSCV but might be in MinGW.
