### ISSUE TITLE
error on make on ubuntu 14.04

### ISSUE THREAD

**Issue by camatthew** [LibVNC/libvncserver#198]
libvncclient.so.0.9.12: undefined reference to `X509_VERIFY_PARAM_set1_host

**Comment by bk138** [comment]
my crystal ball tells me you are using current master? what it cannot tell me is context, so pls pls provide a build log. also, is this meant to be informative or a request or ...?

**Comment by camatthew** [comment]
its a error. im using current master

**Comment by bk138** [comment]
thank you. pls provide the full build log.

**Comment by camatthew** [comment]
close it im using x11vnc instead
