### ISSUE TITLE
Feature request: screenshot capture tool

### ISSUE THREAD

**Issue by FedericoCeratto** [LibVNC/libvncserver#206]
Hello and thank you for developing LibVNC.
It would be useful to have a little CLI tool to connect to a VNC server and grab a screenshot (without having to run X locally).

**Comment by bk138** [comment]
You can already grab videos, see https://github.com/LibVNC/libvncserver/blob/master/client_examples/vnc2mpg.c

**Comment by bk138** [comment]
Please have a look at https://github.com/LibVNC/libvncserver/blob/master/client_examples/ppmtest.c which does what you propose.
