### ISSUE TITLE
configure: WARNING: ws2tcpip.h: present but cannot be compiled

### ISSUE THREAD

**Issue by busche** [LibVNC/libvncserver#207]
Dear all,

I am adding this issue, because the configure script told me to do so, and I might have an uncommon environment.

The message:

```
configure: WARNING: ws2tcpip.h: present but cannot be compiled
configure: WARNING: ws2tcpip.h:     check for missing prerequisite headers?
configure: WARNING: ws2tcpip.h: see the Autoconf documentation
configure: WARNING: ws2tcpip.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ws2tcpip.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/LibVNC/libvncserver ##
configure: WARNING:     ## ----------------------------------------------------- ##

```

My environment is a babun-shell (essentially a cygwin) on Windows.
Steps to reproduce (this should be everything):

1. Install babun as documented
2. run pact install libtool libglib2.0-devel #libglib1.2-devel
3. run ./autogen.sh for libvncserver

**Comment by bk138** [comment]
Hi Andre,
Would you be able to try current master? We switched from autotools to cmake so this does not really apply anymore. 

Are you able to build?

**Comment by busche** [comment]
Hi bk138,

sorry for replying soooo late - github did not sent me a notice that you answered.

I just freshly clone master, did the cmake usual stuff (mkdir build && cd build && cmake .. && make)
and after also installing 

pact install libpng-devel

everything installed fine.

Issue closed. Thanks!
