### ISSUE TITLE
vncserver does not work on macOS 10.12 & 10.13

### ISSUE THREAD

**Issue by vladshekh** [LibVNC/libvncserver#208]
After build libvncserver versions 0.9.11 and the latest 0.9.12 on macOS 10.12 & 10.13 (Sierra and High Sierra) example of server (i.e.: simple) started with the following error: 
/libvncserver0.9.12/BUILD/examples/simple 
04/12/2017 11:11:10 ListenOnTCPPort: Address already in use
I tried all examples and all of them exposed the same error.

**Comment by bk138** [comment]
Well, that means you have some other server running on port 5900. Either stop that or choose another port via `-rfbport`.

**Comment by vladshekh** [comment]
Actually I tried several different not opened ports. See netstat output:
sudo lsof -i -P | grep -i "listen"
launchd       1           root    8u  IPv6 0x7ad1bb7f2ed508d      0t0  TCP *:5900 (LISTEN)
launchd       1           root   10u  IPv4 0x7ad1bb7f2edc26d      0t0  TCP *:5900 (LISTEN)
launchd       1           root   12u  IPv6 0x7ad1bb7f2ed4acd      0t0  TCP *:22 (LISTEN)
launchd       1           root   13u  IPv4 0x7ad1bb7f2edb91d      0t0  TCP *:22 (LISTEN)
launchd       1           root   16u  IPv6 0x7ad1bb7f2ed4acd      0t0  TCP *:22 (LISTEN)
launchd       1           root   17u  IPv4 0x7ad1bb7f2edb91d      0t0  TCP *:22 (LISTEN)
launchd       1           root   22u  IPv6 0x7ad1bb7f2ed564d      0t0  TCP *:445 (LISTEN)
launchd       1           root   26u  IPv6 0x7ad1bb7f2ed508d      0t0  TCP *:5900 (LISTEN)
launchd       1           root   28u  IPv6 0x7ad1bb7f2ed564d      0t0  TCP *:445 (LISTEN)
launchd       1           root   29u  IPv4 0x7ad1bb7f2edc26d      0t0  TCP *:5900 (LISTEN)
launchd       1           root   34u  IPv4 0x7ad1bb7f2edafcd      0t0  TCP *:445 (LISTEN)
launchd       1           root   35u  IPv4 0x7ad1bb7f2edafcd      0t0  TCP *:445 (LISTEN)
launchd       1           root   47u  IPv6 0x7ad1bb7f2ed5c0d      0t0  TCP *:548 (LISTEN)
launchd       1           root   48u  IPv4 0x7ad1bb7f2edcbbd      0t0  TCP *:548 (LISTEN)
launchd       1           root   51u  IPv6 0x7ad1bb7f2ed5c0d      0t0  TCP *:548 (LISTEN)
launchd       1           root   52u  IPv4 0x7ad1bb7f2edcbbd      0t0  TCP *:548 (LISTEN)
httpd       108           root    4u  IPv6 0x7ad1bb7f2ed678d      0t0  TCP *:80 (LISTEN)
kdc         121           root    5u  IPv6 0x7ad1bb7f2ed450d      0t0  TCP *:88 (LISTEN)
kdc         121           root    7u  IPv4 0x7ad1bb7f2edd50d      0t0  TCP *:88 (LISTEN)
httpd       330           _www    4u  IPv6 0x7ad1bb7f2ed678d      0t0  TCP *:80 (LISTEN)
Skype       376   vshekhovtsov   96u  IPv4 0x7ad1bb806d39fcd      0t0  TCP 192.168.252.142:37439 (LISTEN)
cupsd     10132           root    5u  IPv6 0x7ad1bb7f2ed6d4d      0t0  TCP localhost:631 (LISTEN)
cupsd     10132           root    6u  IPv4 0x7ad1bb80558fe5d      0t0  TCP localhost:631 (LISTEN)
ARDAgent  55247         nobody    9u  IPv6 0x7ad1bb7f2ed730d      0t0  TCP *:3283 (LISTEN)
httpd     67122           _www    4u  IPv6 0x7ad1bb7f2ed678d      0t0  TCP *:80 (LISTEN)

And example's output:
MacBook-Pro:BUILD vshekhovtsov$ /Users/vshekhovtsov/Documents/Dev/Infocus.Zoos.Mac/3rdSrc/libvncserver0.9.12/BUILD/examples/simple -rfbport 5993
04/12/2017 12:01:05 Listening for VNC connections on TCP port 5993
04/12/2017 12:01:05 rfbListenOnTCP6Port: error in bind IPv6 socket: Address already in use
^C
MacBook-Pro:BUILD vshekhovtsov$ /Users/vshekhovtsov/Documents/Dev/Infocus.Zoos.Mac/3rdSrc/libvncserver0.9.12/BUILD/examples/simple -rfbport 6001
04/12/2017 12:01:16 Listening for VNC connections on TCP port 6001
04/12/2017 12:01:16 rfbListenOnTCP6Port: error in bind IPv6 socket: Address already in use
^C
MacBook-Pro:BUILD vshekhovtsov$ /Users/vshekhovtsov/Documents/Dev/Infocus.Zoos.Mac/3rdSrc/libvncserver0.9.12/BUILD/examples/simple -rfbport 8831
04/12/2017 12:01:25 Listening for VNC connections on TCP port 8831
04/12/2017 12:01:25 rfbListenOnTCP6Port: error in bind IPv6 socket: Address already in use
^C
MacBook-Pro:BUILD vshekhovtsov$ /Users/vshekhovtsov/Documents/Dev/Infocus.Zoos.Mac/3rdSrc/libvncserver0.9.12/BUILD/examples/simple -rfbport 39148
04/12/2017 12:03:24 Listening for VNC connections on TCP port 39148
04/12/2017 12:03:24 rfbListenOnTCP6Port: error in bind IPv6 socket: Address already in use
^C
MacBook-Pro:BUILD vshekhovtsov$ /Users/vshekhovtsov/Documents/Dev/Infocus.Zoos.Mac/3rdSrc/libvncserver0.9.12/BUILD/examples/simple -rfbport 69719
04/12/2017 12:04:30 Listening for VNC connections on TCP port 69719
04/12/2017 12:04:30 rfbListenOnTCP6Port: error in bind IPv6 socket: Address already in use

**Comment by bk138** [comment]
Well I tried current master on 10.13.1 jsut now and it works fine. Do you have some sort of firewall like Little Snitch running?

**Comment by vladshekh** [comment]
Hi Christian,


I do not have Little Snitch installed. Also, the firewall on my mac is turned off. I'll ask our sysadmin if we have firewall in our ethernet.


Best regards,


Vladimir Shekhovtsov





04 декабря 2017, 15:49:16, от Christian Beier <notifications@github.com>: 


Well I tried current master on 10.13.1 jsut now and it works fine. Do you have some sort of firewall like Little Snitch running?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







--

**Comment by vladshekh** [comment]
More info:


MacBook-Pro:BUILD vshekhovtsov$ /Users/vshekhovtsov/Documents/Dev/Infocus.Zoos.Mac/3rdSrc/libvncserver0.9.12/BUILD/examples/simple -rfbport 30038

04/12/2017 16:22:45 Listening for VNC connections on TCP port 30038

04/12/2017 16:22:45 rfbListenOnTCP6Port: error in bind IPv6 socket: Address already in use









netstat shows that the port has been binded to tcp4:
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)    

tcp4       0      0  *.30038                *.*                    LISTEN   






and the error is still the same with ipv6.




Best regards,
Vlad


04 декабря 2017, 16:11:40, от Vlad Shekhovtsov <shehav@ukr.net>: 


Hi Christian,


I do not have Little Snitch installed. Also, the firewall on my mac is turned off. I'll ask our sysadmin if we have firewall in our ethernet.


Best regards,


Vladimir Shekhovtsov





04 декабря 2017, 15:49:16, от Christian Beier <notifications@github.com>: 


Well I tried current master on 10.13.1 jsut now and it works fine. Do you have some sort of firewall like Little Snitch running?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







-- 







-- 
Best regards,


Vladimir Shekhovtsov

**Comment by vladshekh** [comment]
I made several tests with the latest sources. Look like the socket binds to port with ipv4. And, correspondingly, ipv6 exposes the error with the same port. 
I can achieve the bound port via tcp4.

**Comment by vladshekh** [comment]
Any news on the issue?

**Comment by bk138** [comment]
Not from my side. I can only say it works here :-/

**Comment by vladshekh** [comment]
Hi Christian,

The issue is still unresolved. Do you have paid option for support?
