### ISSUE TITLE
Size issue and crash on Windows

### ISSUE THREAD

**Issue by BastiaanOlij** [LibVNC/libvncserver#216]
Running any of the server examples and trying to connect to them with RealVNC Viewer I get a "RFB protocol error: bad desktop size" followed by a weirdly high resolution value. The example program subsequently crashes.

This is running Windows 10 using Microsoft Visual Studio 2017 and CMake 3.10

**Comment by sfhacker** [comment]
Has this long standing issue been fixed? How can I reproduce this app crash?

**Comment by jeilun** [comment]
@sfhacker 
I have the same problem when I try to connect from vnc viewer .
client error : rfb protocol error  bad desktop size
server error : returning securityresult for client rfb >= 3.8

![virtual](https://user-images.githubusercontent.com/3160679/55673161-55038980-58b9-11e9-8c7d-1639d8a64192.jpg)

![host](https://user-images.githubusercontent.com/3160679/55673169-71072b00-58b9-11e9-97e5-abee12b92dc4.jpg)

**Comment by RubberFeng** [comment]
> @sfhacker
that error of vcruntime,about "close.cpp",I have fix it,look the newest issue.It's server's bug when client closed connection.
But I don't also have the save problem about size'crash.It's a weirdly high resolution value.and I try to change the resolution to 1x1,the error tips change to "String exceed maximum...."!~~Who can fix this problem ,please help!

**Comment by bk138** [comment]
The close.cpp thing is a dupe of #329 . The other issue might have been fixed by #353, please check.

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists!

**Comment by nishant4uster1** [comment]
I got "RFB protocol error: bad desktop size 0x0 " and Apple PC restart, worked for me.
