### ISSUE TITLE
ReadPassword on Windows NOT IMPLEMENTED

### ISSUE THREAD

**Issue by sfhacker** [LibVNC/libvncserver#223]
What is the meaning of this error message?

backchannel.exe

08/03/2018 13:31:06 VNC server supports protocol version 3.8 (viewer 3.8)
08/03/2018 13:31:06 We have 2 security types to read
08/03/2018 13:31:06 0) Received security type 2
08/03/2018 13:31:06 Selecting security type 2 (0/2 in the list)
08/03/2018 13:31:06 1) Received security type 16
08/03/2018 13:31:06 Selected Security Scheme 2
08/03/2018 13:31:06 ReadPassword on Windows NOT IMPLEMENTED
08/03/2018 13:31:06 Reading password failed

There are plenty of open source projects where users can enter passwords on the command line.
Please, take a look at them.

I'm finding really hard to test this project. I'm quite stuck!
Any assistance would be greatly appreciated.

**Comment by bk138** [comment]
It's not implemented for Windows as you can see. This was and still is a UNIX-based and targeted library, Windows support is far from complete.

**Comment by sfhacker** [comment]
Any progress/news on this issue? It is over a month now and I haven't been able to test it all!

**Comment by bk138** [comment]
Dear @sfhacker you can implement it and file a PR to speed up things.

**Comment by bk138** [comment]
@sfhacker Kindly asking if have you been able to implement this in the meantime? if yes, please file a PR :-)
