### ISSUE TITLE
cannot open include file 'windows.h'  on Win 10 when building sasl

### ISSUE THREAD

**Issue by ChongDeng** [LibVNC/libvncserver#227]
C:\F_work\vncserver\libvncserver-master\deps\sasl>C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\bin\nmake /f NTMakefile OPENSSL_INCLUDE=c:\OpenSSL-Win32\include OPENSSL_LIBPATH=c:\OpenSSL-Win32\lib DB_INCLUDE=C:\F_work\vncserver\libvncserver-master\deps\db\build_win32 DB_LIBPATH=C:\F_work\vncserver\libvncserver-master\deps\db\build_win32\release DB_LIB=libdb41.lib install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Applications and libraries should run on any Win32 system.
Default installation directory is C:\CMU.
No configuration specified. Defaulting to Release.
Defaulting GSSAPI Include path to "C:\Program Files\CyberSafe\Developer Pack\ApplicationSecuritySDK\include".
Defaulting GSSAPI library path to "C:\Program Files\CyberSafe\Developer Pack\ApplicationSecuritySDK\lib".
Defaulting SQLITE_INCLUDES includes to /I"C:\work\open_source\sqllite\sqlite\src" /I"C:\work\open_source\sqllite\sqlite\win32".
Defaulting SQLITE library path to "C:\work\open_source\sqllite\sqlite\objs".
Defaulting SQLITE_INCLUDES3 includes to /I"c:\work\sqlite\generated".
Defaulting SQLITE library path to "c:\work\sqlite\objs.NT".
Defaulting LDAP library path to c:\work\open_source\openldap\openldap-head\ldap\Debug.
Defaulting LDAP include path to c:\work\open_source\openldap\openldap-head\ldap\include.
Codegeneration defaulting to /MT.
        cd include && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" /f NTMakefile /                   prefix=C:\CMU install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        xcopy sasl*.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\sasl.h -> C:\CMU\include\sasl\sasl.h
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\saslplug.h -> C:\CMU\include\sasl\saslplug.h
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\saslutil.h -> C:\CMU\include\sasl\saslutil.h
3 File(s) copied
        xcopy hmac-md5.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\hmac-md5.h -> C:\CMU\include\sasl\hmac-md5.h
1 File(s) copied
        xcopy md5.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\md5.h -> C:\CMU\include\sasl\md5.h
1 File(s) copied
        xcopy sasl.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\sasl.h -> C:\CMU\include\sasl\sasl.h
1 File(s) copied
        xcopy saslplug.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\saslplug.h -> C:\CMU\include\sasl\saslplug.h
1 File(s) copied
        xcopy saslutil.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\saslutil.h -> C:\CMU\include\sasl\saslutil.h
1 File(s) copied
        xcopy prop.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\include\prop.h -> C:\CMU\include\sasl\prop.h
1 File(s) copied
        cd sasldb && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" /f NTMakefile /                   prefix=C:\CMU install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        xcopy sasldb*.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\sasldb\sasldb.h -> C:\CMU\include\sasl\sasldb.h
1 File(s) copied
        xcopy sasldb.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\sasldb\sasldb.h -> C:\CMU\include\sasl\sasldb.h
1 File(s) copied
        cd win32\include && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" /f NTMakefile /                   prefix=C:\CMU install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        xcopy md5global*.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\win32\include\md5global.h -> C:\CMU\include\sasl\md5global.h
1 File(s) copied
        xcopy md5global.h C:\CMU\include\sasl /I /F /Y
C:\F_work\vncserver\libvncserver-master\deps\sasl\win32\include\md5global.h -> C:\CMU\include\sasl\md5global.h
1 File(s) copied
        cd lib && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" /f NTMakefile /                   prefix=C:\CMU install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Applications and libraries should run on any Win32 system.
No configuration specified. Defaulting to Release.
Defaulting GSSAPI Include path to "C:\Program Files\CyberSafe\Developer Pack\ApplicationSecuritySDK\include".
Defaulting GSSAPI library path to "C:\Program Files\CyberSafe\Developer Pack\ApplicationSecuritySDK\lib".
Defaulting SQLITE_INCLUDES includes to /I"C:\work\open_source\sqllite\sqlite\src" /I"C:\work\open_source\sqllite\sqlite\win32".
Defaulting SQLITE library path to "C:\work\open_source\sqllite\sqlite\objs".
Defaulting SQLITE_INCLUDES3 includes to /I"c:\work\sqlite\generated".
Defaulting SQLITE library path to "c:\work\sqlite\objs.NT".
Defaulting LDAP library path to c:\work\open_source\openldap\openldap-head\ldap\Debug.
Defaulting LDAP include path to c:\work\open_source\openldap\openldap-head\ldap\include.
Codegeneration defaulting to /MT.
        xcopy /D /Y ..\plugins\plugin_common.h .
..\plugins\plugin_common.h
1 File(s) copied
        xcopy /D /Y ..\plugins\plugin_common.c .
..\plugins\plugin_common.c
1 File(s) copied
        rc /fo"libsasl.res" C:\Users\fqyya\AppData\Local\Temp\nmD63.tmp
Microsoft (R) Windows (R) Resource Compiler Version 6.1.7600.16385
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Users\fqyya\AppData\Local\Temp\nmD63.tmp(1) : fatal error RC1015: cannot open include file 'windows.h'.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\rc.EXE"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

**Comment by bk138** [comment]
You should really report this to cyrus-sasl as this is LibVNCServer.
