### ISSUE TITLE
can't unzip cyrus-sasl-2.1.26.tar.gz 

### ISSUE THREAD

**Issue by ChongDeng** [LibVNC/libvncserver#228]
C:\F_work\vncserver\libvncserver-master\deps>curl -fsSL -o cyrus-sasl-2.1.26.tar.gz ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz

C:\F_work\vncserver\libvncserver-master\deps>7z x cyrus-sasl-2.1.26.tar.gz -so | 7z x -si -ttar > nul

ERROR: The pipe has been ended.

C:\F_work\vncserver\libvncserver-master\deps>

**Comment by bk138** [comment]
Come on. As this works for the AppVeyor builds, the problem most probably is with you setup. Have you checked that the tgz is actually downloaded?
