### ISSUE TITLE
Hextile encoding support?

### ISSUE THREAD

**Issue by ysnnzlcn** [LibVNC/libvncserver#229]
Hi, I read the 'read me' but i couldn't understand if this library supports Hextile or not 😕 

> The following encodings are known to me: Raw, RRE, CoRRE, Hextile, CopyRect from the original AT&T code and Tight, ZLib, LastRect, XCursor, RichCursor from Const Kaplinsky et al.
> 
> If you are using a modem, you want to try the "new" encodings. Especially with my 56k modem I like ZLib or Tight with Quality 0. In my tests, it even beats Tarantella.

The vnc server i would like connect is using these settings >
![screen shot 2018-04-02 at 22 20 08](https://user-images.githubusercontent.com/30194773/38211818-56482dae-36c4-11e8-9d34-f705b0fe1db2.png)

Can i connect it with this library?

**Comment by bk138** [comment]
I reckon you talk about LibVNCClient? Yes, it does support hextile: https://github.com/LibVNC/libvncserver/blob/master/libvncclient/hextile.c
