### ISSUE TITLE
‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’

### ISSUE THREAD

**Issue by DevinXZhou** [LibVNC/libvncserver#231]
Hello! I cannot build this program on Ubuntu 16.04. I have installed everything, I thought it is problem of FFmpeg version?  
libvncserver/client_examples/vnc2mpg.c:155:50: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     ret = avcodec_parameters_from_context(ost->st->codecpar, ost->enc);
How to fix this? should I uninstall libav and keep FFmpeg?

**Comment by bk138** [comment]
Yes it is. Likely it is a version mismatch.You'll have to find a ffmpeg version that has `codecpar`

**Comment by DevinXZhou** [comment]
thanks! 
I fixed the problem by installing FFmpeg-3.

sudo add-apt-repository ppa:jonathonf/ffmpeg-3
//****extra step for ubuntu 14
sudo add-apt-repository ppa:jonathonf/tesseract
//****
sudo apt update && sudo apt upgrade

**Comment by bk138** [comment]
@DevinXZhou which version of ffmpeg did you have before? I'd like to represent this dependency in the build system.

**Comment by DevinXZhou** [comment]
@bk138 I did not actually check it, but I typed in ffmpeg in my terminal and it says it was not installed. I reinstalled my ubuntu 16.04 64bit system, I tried to update libav and everything else. Nothing worked until I tried to install FFmpeg-3 from 
ppa:jonathonf/ffmpeg-3

**Comment by tadam98** [comment]
Hi,

The latest ffmpeg version (from the official ffmpeg site) that also supports nvidia's hardware acceleration reports:
>ffmpeg -version
ffmpeg version N-100445-gab6a56773f Copyright (c) 2000-2020 the FFmpeg developers

How does this comply with > 3.1.0?

Best,
Mickey
