### ISSUE TITLE
Is it possible to use jpeg data in frame buffer, instead of rgb data(from jpeg)?

### ISSUE THREAD

**Issue by uno129** [LibVNC/libvncserver#232]
I convert jpeg data to rgb data using [jpeg library], but it costs too much of cpu resources.(it is a small  cpu)
is it possible to use jpeg data in frame buffer(rfbFrameBuffer), instead of rgb data?

**Comment by bk138** [comment]
Client? Server? Does a01a18df1d44ec875708d5fc9d6c4e0934535974 help?

**Comment by uno129** [comment]
It is server side, client is noVNC.

**Comment by bk138** [comment]
LibVNCServer expects the raw framebuffer as an RGB(A) array with your framebuffer width as stride. You can maybe extend it to eat JPEG data but I don't know enough about JPEG to maintain that encoded blocks are the same size, are in order, etc...

**Comment by eddiejames** [comment]
This is quite possible with https://github.com/LibVNC/libvncserver/pull/235
