### ISSUE TITLE
German and Swedish keymap issue.

### ISSUE THREAD

**Issue by araujobsd** [LibVNC/libvncserver#233]
Hi,

I'm using libvncserver[0] with bhyve Hypervisor and I have some users complaining[1] about German and Swedish keymap issues. I could not find a proper solution to fix this issues.

I'm wondering if this should be solved at libvncserver side or libvncclient. Any input or advice would be very appreciated.

[0] https://github.com/freenas/libhyve-remote
[1] https://redmine.ixsystems.com/issues/24450

**Comment by anderstn** [comment]
As a FreeNAS user I would like to point out that saying the complaint is limited to Swedish and German keyboard layouts is modest at best. Pretty much anyone not in the UK seems to be having issues. I live in Norway and in order to get my Norwegian keyboard recognised I have to change my local input language on the machine running the client to English.

**Comment by bk138** [comment]
As LibVNCServer/LibVNCClient simply send rfbKeysyms (https://github.com/LibVNC/libvncserver/blob/master/rfb/keysym.h) over the wire, I reckon this ought to be tackled in the server and/or client apps. I propose you file an issue over at  https://github.com/freenas/libhyve-remote and close this one.

**Comment by araujobsd** [comment]
@bk138 I pretty much send that over the wire: https://github.com/freenas/libhyve-remote/blob/master/patches/bhyve_vncserver.patch#L557

**Comment by bk138** [comment]
@araujobsd Can you elaborate a bit on what that is and what the functions are supposed to do pls?

**Comment by bk138** [comment]
BTW, https://github.com/freenas/libhyve-remote/blob/master/patches/bhyve_vncserver.patch#L557 does not match theLibVNCServer function signature of https://github.com/LibVNC/libvncserver/blob/master/rfb/rfb.h#L144

**Comment by araujobsd** [comment]
I'm using the console_key_event from the Hypervisor: https://svnweb.freebsd.org/base/head/usr.sbin/bhyve/console.c?view=annotate#l107

Perhaps that is where the issue lives, I will try to integrate rfb/keysym.h on libhyve-remote or, instead to use console_key_event from the Hypervisor, I will try to use rfbKbdAddEventProcPtr from rfb/rfb.h.

**Comment by araujobsd** [comment]
@bk138 Thanks for the idea of using Wireshark on a running session. I didn't think to do that to verify what side the issue happens. But after all this talk. I'm 100% sure the issue lives in that function in the Hypervisor side.

So I'm closing this issue and I will open it on libhyve-remote repo.

Thanks again.
