### ISSUE TITLE
Recommendation for server usage to display (part of the) desktop

### ISSUE THREAD

**Issue by nikoladsp** [LibVNC/libvncserver#236]
Hi,
Sorry if this was already asked but I did not manage to find the answer so far.

I need to create VNC server that will display content of the desktop (whole or just a rectangular region) and I would like to use libvncserver.

Now, I don't have experience of VNC development and I need an advice. Samples demonstrates how to share an image from frame buffer to connected clients, but I would like to know what is the best practice to share images of desktop (region). Shall I poll periodically and store image into the frame buffer or there is a more elegant way of doing this? I guess it depends on OS also (my targets are Linux and Android). Also, when sending image of the desktop, will the libvncserver library send only 'diffs' automatically, or I have to take some steps in order to send only partial updates?

Thank you in advance.

Best regards

**Comment by bk138** [comment]
Hi!
* You can poll the system display or use some system notification of what changed on-screen. See how https://github.com/LibVNC/x11vnc does it for X11 and OSX.
* the library only sends rectangles you mark as dirty, so yes, it sends diffs.

**Comment by bk138** [comment]
I'm closing this to keep the issue list clean, put feel free to re-open if questions remain.

**Comment by nikoladsp** [comment]
Thank you kindly!

Regards
