### ISSUE TITLE
Error to build example

### ISSUE THREAD

**Issue by atpious** [LibVNC/libvncserver#239]
**Hello friends**
I want to design a simple VNC using the RFB protocol
I could not build a project using cmake
And I want to make a simple vnc staircase
But after running example, I encounter this error
Error undefined reference to `rfbScreenCleanup'
please guide me

![pixcture1](https://user-images.githubusercontent.com/42282042/43991863-8a636888-9d8a-11e8-8794-e1609fa353d2.jpg)

**Comment by bk138** [comment]
you should provide the full build log (using CMake) please

**Comment by atpious** [comment]
here is my log file and have some errors describe has below

`The C compiler identification is GNU 6.3.0
The CXX compiler identification is GNU 6.3.0
Check for working C compiler: C:/MinGW/bin/gcc.exe
Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/bin/g++.exe
Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) 
Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) 
Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) 
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
Performing Test FOUND_LIBJPEG_TURBO
Performing Test FOUND_LIBJPEG_TURBO - Failed
CMake Warning at CMakeLists.txt:73 (message):
  *** The libjpeg library you are building against is not libjpeg-turbo.
  Performance will be reduced.  You can obtain libjpeg-turbo from:
  https://sourceforge.net/projects/libjpeg-turbo/files/ ***


Looking for __b64_ntop
Looking for __b64_ntop - not found
Looking for __b64_ntop
Looking for __b64_ntop - not found
Looking for endian.h
Looking for endian.h - not found
Looking for fcntl.h
Looking for fcntl.h - found
Looking for netinet/in.h
Looking for netinet/in.h - not found
Looking for sys/endian.h
Looking for sys/endian.h - not found
Looking for sys/socket.h
Looking for sys/socket.h - not found
Looking for sys/stat.h
Looking for sys/stat.h - found
Looking for sys/time.h
Looking for sys/time.h - found
Looking for sys/types.h
Looking for sys/types.h - found
Looking for sys/wait.h
Looking for sys/wait.h - not found
Looking for unistd.h
Looking for unistd.h - found
Looking for vfork.h
Looking for vfork.h - not found
Looking for ws2tcpip.h
Looking for ws2tcpip.h - found
Looking for arpa/inet.h
Looking for arpa/inet.h - not found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Looking for sys/types.h
Looking for sys/types.h - found
Looking for gettimeofday
Looking for gettimeofday - found
Looking for vfork
Looking for vfork - not found
Looking for vprintf
Looking for vprintf - found
Check size of pid_t
Check size of pid_t - done
Check size of size_t
Check size of size_t - done
Check size of socklen_t
Check size of socklen_t - failed
Check size of in_addr_t
Check size of in_addr_t - failed
Check if the system is big endian
Searching 16 bit integer
Check size of unsigned short
Check size of unsigned short - done
Using unsigned short
Check if the system is big endian - little endian
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SSL_EAY (ADVANCED)
    linked by target "vncclient" in directory C:/Users/Amir/Downloads/Compressed/libvncserver-LibVNCServer-0.9.11/libvncserver-LibVNCServer-0.9.11

Configuring incomplete, errors occurred!
See also "C:/MinGW/bin/CMakeFiles/CMakeOutput.log".
See also "C:/MinGW/bin/CMakeFiles/CMakeError.log".`

**Comment by bk138** [comment]
Please try again with latest master and re-open if issue persists. Works here with MSVC 2015.
