### ISSUE TITLE
Latest LibVNCServer build in Windows. Please Help me.

### ISSUE THREAD

**Issue by AlkesaMitic** [LibVNC/libvncserver#249]
Dear, Sir.

How are you?

My name is William Ding and I'm from China. I'm individual developer and freelancer.

Few days ago, I've got VNC project which is based on your LibVNCServer library.

The project is for Windows platform and Visual Studio 2008 based project.

That project is 5 years old so it is also using old version of LibVNCServer library.

So I want to use your latest LibVNCServer library but it's really hard to build your project on Windows.

The old project include your LibVNCServer library project in Visual Studio 2008 project and also build your library in project well.

But I can't include your new library version into project again.

Could you please help me?

I posted jobs on Freelancer.com to find person to help me but nobody can do it.

I think you can do it.

I can pay you for this work.

Please contact me.

This is my email address and skype id.

williamding131@outlook.com

Please help me.

I'm waiting your response.

Best regards.

**Comment by bk138** [comment]
Please have a look at https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml to see how the library gets built for windows at the moment.

NB that the windows builds are currently not working though due to #165

**Comment by sfhacker** [comment]
@AlkesaMitic I understand your frustration. There are long standing open issues. Yet I can see a ne release. Anyway, we shall be able to help you. Please, contact us as soon as you can.

Regards.

**Comment by bk138** [comment]
Windows builds with MSVC are working with latest commit 7aeeca2b1c5936890ef5c0666f856d63db679e8d, please re-open this issue if problems persist.
