### ISSUE TITLE
SECURITY: null pointer dereference in ultra zip encoding handler in libvncclient

### ISSUE THREAD

**Issue by PaulCher** [LibVNC/libvncserver#254]
Null pointer dereference happens(https://github.com/LibVNC/libvncserver/blob/master/libvncclient/ultra.c#L162) because after allocation of buffer it is not check that `malloc` didn't return NULL, because of the rss memory limits.

https://github.com/LibVNC/libvncserver/blob/79516a6aa3e875c8d9f4c83667076aa070fe5d6e/libvncclient/ultra.c#L162

This security issue is a result of my work at Kaspersky Lab ICS CERT Vulnerability Research Group at position of Security Researcher.

For more information about ICS CERT please contact:
ics-cert@kaspersky.com
https://ics-cert.kaspersky.com/

Best regards,
Pavel Cheremushkin

**Comment by bk138** [comment]
That very much seems like a non-issue to me: if `client->ultra_buffer` is NULL in line 162, https://github.com/LibVNC/libvncserver/blob/master/libvncclient/ultra.c#L166 will be called with NULL and return FALSE, see https://github.com/LibVNC/libvncserver/blob/master/libvncclient/sockets.c#L98.

Please re-open if I am wrong.

**Comment by PaulCher** [comment]
Whoopsie-daisy. The issue still exists, but seems that I have pointed to the wrong like in the code. It was meant to be https://github.com/LibVNC/libvncserver/blob/master/libvncclient/ultra.c#L152

Because allocation of `client->raw_buffer` is not checked, then null pointer could be dereferenced in `lzo1x_decompress_safe` on line https://github.com/LibVNC/libvncserver/blob/master/libvncclient/ultra.c#L171
