### ISSUE TITLE
Release 0.9.12

### ISSUE THREAD

**Issue by cinemast** [LibVNC/libvncserver#256]
Hi!

The last release is from 2016, is there any plan of releasing a new version of this library?
Debian is about to freeze for the next release in a few weeks. Do you think it would be possible to craft a new release until November?

**Comment by bk138** [comment]
yes. i realised this, too. and split out issues for a later 0.9.13, so now there are just a few remaining for 0.9.12. help is, as always, appreciated :-)

**Comment by bk138** [comment]
- [ ] update NEWS

- [ ] update ChangeLog

**Comment by cinemast** [comment]
Any change open security issues might also get fixed? I'll see what I can do

**Comment by cinemast** [comment]
Looks good, thanks!

**Comment by bk138** [comment]
@cinemast I'll do a release today and will try to squeeze as much of https://github.com/LibVNC/libvncserver/milestone/4 into it, hope you can upload this to unstable short-term, before the freeze. Sorry for the delay!
