### ISSUE TITLE
Two inconsistencies in code

### ISSUE THREAD

**Issue by ManSoSec** [LibVNC/libvncserver#279]
Hi

We found two inconsistencies in the code that might lead to bugs:

1) Missing NULL check on return value of SendFramebufferUpdateRequest:
Missed here: 
https://github.com/LibVNC/libvncserver/blob/master/libvncclient/rfbproto.c#L1479
Done here: 
https://github.com/LibVNC/libvncserver/blob/master/libvncclient/vncviewer.c#L412

------------------------------------------------

2) Missing check before calling rfbScaledCorrection:
Missed here: 
https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L3240
Done here: 
https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L2998
https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L3014
https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L3037

**Comment by bk138** [comment]
1. is a non-issue

**Comment by bk138** [comment]
2. does no harm if `from` and `to` args are the same: https://github.com/LibVNC/libvncserver/blob/master/libvncserver/scale.c#L115
