### ISSUE TITLE
libvncserver-0.9.12 SEGVs in Remmina 1.3.1

### ISSUE THREAD

**Issue by joakim-tjernlund** [LibVNC/libvncserver#280]
Connecting to Vino VNC server using libvncserver built with ssl SEGvs or hang the DE.
Switching libvncserver over to gnutls works though.

this is on Gentoo

**Comment by bk138** [comment]
would you please be so kind and provide a backtrace and the build recipe to be able to reproduce this?

**Comment by bk138** [comment]
Mh, anyway, I can't repro without proper build details. Could you provide these?

**Comment by joakim-tjernlund** [comment]
Will this do?

`cmake -C /var/tmp/portage/net-libs/libvncserver-0.9.12/work/libvncserver-LibVNCServer-0.9.12-abi_x86_64.amd64/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DWITH_ZLIB=ON -DWITH_LZO=OFF -DWITH_JPEG=ON -DWITH_PNG=ON -DWITH_SDL=ON -DWITH_THREADS=ON -DWITH_GNUTLS=OFF -DWITH_OPENSSL=ON -DWITH_GCRYPT=OFF -DWITH_SYSTEMD=OFF -DWITH_FFMPEG=OFF -DWITH_24BPP=ON -DWITH_IPv6=ON -DWITH_SASL=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-libs/libvncserver-0.9.12/work/libvncserver-LibVNCServer-0.9.12-abi_x86_64.amd64/gentoo_toolchain.cmake  /var/tmp/portage/net-libs/libvncserver-0.9.12/work/libvncserver-LibVNCServer-0.9.12
loading initial cache file /var/tmp/portage/net-libs/libvncserver-0.9.12/work/libvncserver-LibVNCServer-0.9.12-abi_x86_64.amd64/gentoo_common_config.cmake
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found JPEG: /usr/lib/libjpeg.so (found version "") 
-- Performing Test FOUND_LIBJPEG_TURBO
-- Performing Test FOUND_LIBJPEG_TURBO - Success
-- Found PNG: /usr/lib/libpng.so (found version "1.6.35+apng") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/libSDL2.so;-lpthread  
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2q")  
-- Looking for endian.h
-- Looking for endian.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for sys/endian.h
-- Looking for sys/endian.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/uio.h
-- Looking for sys/uio.h - found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for ws2tcpip.h
-- Looking for ws2tcpip.h - not found
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for vprintf
-- Looking for vprintf - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for fork
-- Looking for fork - found
-- Looking for ftime
-- Looking for ftime - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for gethostname
-- Looking for gethostname - found
-- Looking for inet_ntoa
-- Looking for inet_ntoa - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for memset
-- Looking for memset - found
-- Looking for mkfifo
-- Looking for mkfifo - found
-- Looking for select
-- Looking for select - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strcspn
-- Looking for strcspn - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for htobe64
-- Looking for htobe64 - found
-- Looking for OSSwapHostToBigInt64
-- Looking for OSSwapHostToBigInt64 - not found
-- Building crypto with OpenSSL
-- Check size of pid_t
-- Check size of pid_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of in_addr_t
-- Check size of in_addr_t - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 -pipe -Wno-error -fno-stack-check
C++             -O2 -pipe -Wno-error -fno-stack-check
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed

-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/net-libs/libvncserver-0.9.12/work/libvncserver-LibVNCServer-0.9.12-abi_x86_64.amd64
`

**Comment by joakim-tjernlund** [comment]
@bk138, Have you checked out the above Remmian issue?
Especially the mentioned libvnc commit which appears to introduce the problem?

**Comment by bk138** [comment]
No, not yet.

**Comment by joakim-tjernlund** [comment]
Still no luck ?

**Comment by joakim-tjernlund** [comment]
Still a problem, one needs to use low quality setting though to reproduce

**Comment by joakim-tjernlund** [comment]
This is not an issue for me anymore
