### ISSUE TITLE
Do we can use LibVNCServer as Remote Desktop Control program?

### ISSUE THREAD

**Issue by MasterCna** [LibVNC/libvncserver#282]
Hello,
I'm quite new to this lib and I wanted to know if I can make a remote desktop control program with it (Server and Client). If we can, can you give me more examples? that I can control a remote machine using inputs and stuff

**Comment by bk138** [comment]
Have a look at https://github.com/LibVNC/libvncserver/tree/master/client_examples for clients and https://github.com/LibVNC/libvncserver/tree/master/examples as well as https://github.com/LibVNC/x11vnc for server implementations.
