### ISSUE TITLE
could someone help me out with cross compilation for arm #response needed asap

### ISSUE THREAD

**Issue by deepakk97** [LibVNC/libvncserver#286]
-DCMAKE_TOOLCHAIN_FILE didn't work

**Comment by bk138** [comment]
for a start, please post vyour complete command line. really, we can't all guess :-)

**Comment by deepakk97** [comment]
<img width="1663" alt="screenshot 2019-03-07 at 10 25 56 am" src="https://user-images.githubusercontent.com/46717141/53933252-74917180-40c3-11e9-8ddc-cef8e570b4a7.png">
I need to build the LibVNC for arm platform.I have the arm-cortex_a9-v005 toolchain for this purpose .
according to the readme file ,we got to include the toolchain path (_DCMAKE_TOOLCHAIN_FILE),but the variable is ignored.
[CMakeLists.txt](https://github.com/LibVNC/libvncserver/files/2939578/CMakeLists.txt)
I have attached the modified make file as well.

**Comment by deepakk97** [comment]
Thanks for your reply. I have mentioned the details in the community.

**Comment by deepakk97** [comment]
What modifications are needed in CmakeList.txt in order to build it for arm in a centOS environment.

**Comment by bk138** [comment]
dear @deepakk97 please post, a step-by-step guide in _text_ form to reproduce the problem! imagine someone not familiar with your setup who needs to re--setup it step by step, with all download and stuff.

**Comment by deepakk97** [comment]
Thanks for your reply!,Could you tell me the steps to follow to build libvnc for arm cortex a9 in a centOS environment.

**Comment by bk138** [comment]
Mh, I was hoping to hear this from you - no idea what you are trying to achieve. The README lists build  iunstruction for Android that were tested - other platform I' dont know though it surely is possible.

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists.
