### ISSUE TITLE
How to send partial screen changes to vnc client?

### ISSUE THREAD

**Issue by hhnr** [LibVNC/libvncserver#288]
First of all, thanks for the library.
Do you have any example on how to send partial screen updates to vnc client?
To send screen update to the client, one has to use rfbMarkRectAsModified() function. ` void rfbMarkRectAsModified(rfbScreenInfoPtr screen,int x1,int y1,int x2,int y2) ` But it seems it sends full screen updates to the client. All examples i refer on github or on google search uses rfbMarkRectAsModified(x, y, resolutionx, resolutiony);  

If i know the position x,y where the change has happened and how many rect/tiles have changed, can i send that particular rect/tiles alone to the client?

**Comment by bk138** [comment]
Thanks for the thanks! As for your question: please be aware that RFB works on a client-pull basis via https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#framebufferupdaterequest. If the client always requests non-incremental updates, it'll get those, i.e. it will get full screen updates. Only if the client asks for incremental updates the server will send the modified region(s) only.

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists.
