### ISSUE TITLE
[PATCH] libvncserver-0.9.12 cmake build produces inaccurate pkgconfig files

### ISSUE THREAD

**Issue by ikelos** [LibVNC/libvncserver#290]
Hiya,

libvncserver-0.9.12 has the following in both .pc.cmakein files
```
libdir=@CMAKE_INSTALL_PREFIX@/lib
```

which hardcodes the lib directory to be `<PREFIX>/lib` and breaks under systems that use `<PREFIX>/lib64` for example (such as Gentoo).  These should be changed to the following:

```
libdir=@CMAKE_INSTALL_LIBDIR@
```

Attached is a patch for the issue: [libvncserver-pkgconfig.patch.txt](https://github.com/LibVNC/libvncserver/files/3019062/libvncserver-pkgconfig.patch.txt)

**Comment by bk138** [comment]
That is very true. Would you like to open a pull request to preserve proper author info (and credit ;-) ) or shall I apply this barebones patch?

**Comment by ikelos** [comment]
Happy for you to just apply it.  I'm not in it for credit, I'm just after good software...  5;)
