### ISSUE TITLE
Build error libvncServer on Windows

### ISSUE THREAD

**Issue by springware** [LibVNC/libvncserver#294]
Hello everyone.
I have some trouble building libvnc server on windows.
I followed the guidance from https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml.
Here I used Visual studio 11 2012
But I get errors which is not concern with library link.
check the errors below.

Error	15	error C2065: 'contentType' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	460	1	vncserver
Error	20	error C2065: 'contentType' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	462	1	vncserver
Error	25	error C2065: 'contentType' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	464	1	vncserver
Error	30	error C2065: 'contentType' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	466	1	vncserver
Error	32	error C2065: 'contentType' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	467	1	vncserver
Error	12	error C2065: 'ext' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	459	1	vncserver
Error	17	error C2065: 'ext' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	461	1	vncserver
Error	22	error C2065: 'ext' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	463	1	vncserver
Error	27	error C2065: 'ext' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	465	1	vncserver
Error	2	error C2065: 'host' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\sockets.c	171	1	vncserver
Error	5	error C2065: 'host' : undeclared identifier	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\sockets.c	174	1	vncserver
Error	1	error C2143: syntax error : missing ';' before 'type'	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\sockets.c	170	1	vncserver
Error	10	error C2143: syntax error : missing ';' before 'type'	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	457	1	vncserver
Error	11	error C2143: syntax error : missing ';' before 'type'	G:\Internet\Download\libvncserver-LibVNCServer-0.9.12\libvncserver\httpd.c	458	1	vncserver

Can anyone help me? Thanks.

**Comment by bk138** [comment]
First thing that comes to mind is using the same versions of Visual Studio that are used in CI :-)

**Comment by springware** [comment]
Thanks. I upgrade the VS version 12 to 15, it works. But I am getting error when run example.exe.

08/04/2019 10:46:59 rfbCheckFds: select: An operation was attempted on something that is not a socket.

**Comment by bk138** [comment]
Yes, see #165
