### ISSUE TITLE
Example Server which can be viewed and control.

### ISSUE THREAD

**Issue by springware** [LibVNC/libvncserver#296]
Hello Everyone.
I  successfully build libvncserver thanks to https://github.com/whm200410/libvncserver/ for windows VS2015.
I am new to libvncserver and don't know how to create server application which work similar as realvnc or sth so that I can use noVNC(web client) to view and control it.
Is there any such an server example I can use?
Thanks

**Comment by NIPE-SYSTEMS** [comment]
Maybe: https://github.com/LibVNC/x11vnc
It uses libvncserver and is as a fully featured VNC server. You might hack around in it to get to know libvncserver better?

**Comment by bk138** [comment]
Please have a look at https://github.com/LibVNC/libvncserver/blob/master/examples/example.c

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists.
