### ISSUE TITLE
Fixes for multithreaded Windows applications

### ISSUE THREAD

**Issue by vruppert** [LibVNC/libvncserver#3]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/LibVNC/libvncserver/issues/3)

I have created a patch that adds win32 critical sections as a replacement for the pthread mutex stuff to make libVNCServer more stable when used with multithreaded applications (Bochs with new gui "vncsrv"). Full Windows-style multithreading support is still to do. The patch also includes the existing win32 socket patch by Christian Beyer.

Unfortunately I don't know how to upload a patch here. Please let me know if you are interested and what I can do.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars1.githubusercontent.com/u/40680108?v=4' alt='0maxxam0' width=24 height=24> 0maxxam0](https://issuehunt.io/u/0maxxam0) ($20.00)

### Submitted pull Requests
- [#382 Implement multithreading for win32](https://issuehunt.io/r/LibVNC/libvncserver/pull/382)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/LibVNC/libvncserver/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Hello71** [comment]
a cursory glance at the code appears to disagree with that. many files in libvncserver use rfb.h macros LOCK and UNLOCK which are defined as no-ops if libpthread is not available.

**Comment by bk138** [comment]
Mentioned patch by @vruppert can be found [here](https://sourceforge.net/p/libvncserver/mailman/attachment/5406062D.4060606%40t-online.de/1/)

**Comment by bk138** [comment]
https://stackoverflow.com/questions/800383/what-is-the-difference-between-mutex-and-critical-section

**Comment by bk138** [comment]
https://cmake.org/cmake/help/v3.2/module/FindThreads.html

**Comment by bk138** [comment]
Complicated process, that issuehunt :sweat_smile:
