### ISSUE TITLE
EAGAIN errno is treated as a hard error in websocket decoder

### ISSUE THREAD

**Issue by monitor6** [LibVNC/libvncserver#304]
My setup has a websocket connection between noVNC and x11vnc with an nginx proxy in between. Sometimes when I send a large clipboard from client to server the connection becomes unresponsive or breaks down. 

When this happens x11vnc outputs "hybiReadAndDecode: read; Resource temporarily unavailable". I don't think it's relevant, but this seems to happen due to nginx sitting in between.

The actual issue, in my understanding, is how ws_decode.c handles such connection problems. When `readFunc` in `hybiReadAndDecode` returns any error, the websocket framing state is cleared by `hybiDecodeCleanupComplete`. However when the errno from reading the socket is EAGAIN the server (code from x11vnc I guess) tries again to read from the websocket. Since the framing state is reset, `webSocketsDecodeHybi` tries to parse a new websocket header, but actually reads random data from the payload of the previous frame, since that was being processed at the time of the error.

So I guess the EAGAIN case should be handled differently, except I don't know enough about low level programming to suggest a better way unfortunately...

I'm guessing the same problem can happen inside hybiReadHeader, although a lot less likely to occur.

While debugging I also noticed two smaller issues in ws_decode.c:

 - `##__VA_ARGS` should be `##__VA_ARGS__`
 - a missing newline in `rfbErr("%s: read; %s", __func__, strerror(errno));`

Thanks in advance for looking at this issue!

**Comment by bk138** [comment]
@monitor6  Does this still occur with current master? The code has changed quite a bit since.

**Comment by bk138** [comment]
Tentatively closing, feel free to post here once you have more info.
