### ISSUE TITLE
x11vnc does not bind

### ISSUE THREAD

**Issue by SvetlanaTkachenko** [LibVNC/libvncserver#312]
On Debian buster/sid with x11vnc 0.9.13, running 'x11vnc -forever -display :0 -nopw' in an ssh session shows one line 

30/05/2019 11:51:48 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 13861

Then x11vnc does not listen on port 5900 or any other port.

**Comment by bk138** [comment]
Please try updating to a recent version and check if the issue persists.

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists.
