### ISSUE TITLE
Error in rfbClient->frameBuffer

### ISSUE THREAD

**Issue by tobiasamann** [LibVNC/libvncserver#320]
Hello,

I would like to set up a VNC Test Client to Test our customoized VNC server which runs in a customer application 
(For example check if the Server has sent the right data to the client, transmission time ...). 

For that case I have created a Simple vnc Server and a client. In the Server i write to the frame buffer the data "0xac" in every byte of the frame buffer.
In my client application I want to check that the received frame buffer is equal with my frame buffer which i created in my server. (Every received byte must be "0xac")
After checking my frame buffer unfortunately it is not equal with my server frame buffer.
Has someone a idea wher does it come from?

Difference in client server buffer:
frameBuffer[0] - frameBuffer[1] = 0x0, 0x0, 0x0, 0x0, 0xff, 0xff
frameBuffer[1600] - frameBuffer[1607] = 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0
frameBuffer[3204] - frameBuffer[3209] = 0xff, 0xff, 0x00, 0x00, 0xff, 0xff
frameBuffer[4804] - frameBuffer[4809] = 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
 
The difference is always the same even if i fill up the server buffer with other data.

Simpleserver.c

```
#define BITPSERSAMPEL   16
#define SAMPELSPERPIXEL BITPSERSAMPEL
#define BYTESPERPIXEL   2


int main(int argc,char** argv)
{
  rfbScreenInfoPtr server=rfbGetScreen(&argc,argv,XRES,YRES,BITPSERSAMPEL,SAMPELSPERPIXEL,BYTESPERPIXEL);

  server->frameBuffer= (char*)malloc(XRES*YRES*BYTESPERPIXEL);
  server->serverFormat.bitsPerPixel = 16;
  server->serverFormat.depth = 16;
  server->serverFormat.trueColour = 1;
  server->serverFormat.redMax = 31;
  server->serverFormat.greenMax = 63;
  server->serverFormat.blueMax = 31;
  server->serverFormat.redShift = 11;
  server->serverFormat.greenShift = 5;
  server->serverFormat.blueShift = 0;
  memset(server->frameBuffer,0xac,XRES*YRES*BYTESPERPIXEL);

  server->frameBuffer[XRES*YRES*BYTESPERPIXEL -1] = 0xaf;
  
  rfbInitServer(server);
  rfbRunEventLoop(server,-1,FALSE);
  return(0);
}
```
`

Client.c

```
#define XRES            600
#define YRES            600
#define BITPSERSAMPEL   16
#define SAMPELSPERPIXEL BITPSERSAMPEL
#define BYTESPERPIXEL   2

static void update(rfbClient* cl,int x,int y,int w,int h) {


        uint32_t* dataPointer = (uint32_t*)cl->frameBuffer;
        uint8_t* dataPointer_u8 = (uint8_t*)cl->frameBuffer;
        int i = 0;
        int compare = 0;
        for (int i = 6; i < 800*600*2; i++)
        {
                /* code */
                if(dataPointer_u8[i] == 0xac)
                {

                }
                else
                {
                  /* code */
                  compare++;
                }

                
        }
}

static void cleanup(rfbClient* cl)
{

  if(cl)
    rfbClientCleanup(cl);
}

int main(int argc,char** argv) {
        rfbClient* cl;
        int i, j;
        do {
          cl=rfbGetClient(BITPSERSAMPEL,SAMPELSPERPIXEL,BYTESPERPIXEL);

          cl->GotFrameBufferUpdate=update;
          cl->format.bitsPerPixel = 16;
          cl->format.depth = 16;
          cl->format.trueColour = 1;
          cl->format.redMax = 31;
          cl->format.greenMax = 63;
          cl->format.blueMax = 31;
          cl->format.redShift = 11;
          cl->format.greenShift = 5;
          cl->format.blueShift = 0;
          cl->appData.enableJPEG = FALSE;

          char encodings[] = {"-encodings"};
          char encodingLevel[] = {"raw"};
          char compress[] = {"-compress"};
          char compressLevel = 0;  

          char* initClient[5];
          int numberOfArguments = 5;
          initClient[0] = argv[0];
          initClient[1] = encodings;
          initClient[2] = encodingLevel;
          initClient[3] = compress;
          initClient[4] = &compressLevel;
            
          if(!rfbInitClient(cl,&numberOfArguments,initClient))
            {
              cl = NULL; /* rfbInitClient has already freed the client struct */
              cleanup(cl);
              break;
            }
          while(1) {
              i=WaitForMessage(cl,500);
              if(i<0)
                {
                  cleanup(cl);
                  break;
                }
              if(i)
              {
                if(!HandleRFBServerMessage(cl))
                  {
                    cleanup(cl);
                    break;
                  }
              }
        //     }
          }
        }
        while(1);
        return 0;
}`
```

**Comment by bk138** [comment]
Hi Tobias!
Is the encoding used for communication a lossy one?

**Comment by tobiasamann** [comment]
Hi,

for my client I chossed "raw encoding" and "compress level 0"

**Comment by bk138** [comment]
The snippets you posted don't build. I'd also point out that you chose 600 x 600, but your update comparer has 800x600 hardcoded.

**Comment by tobiasamann** [comment]
I am sorry I have just tested some different Resolution and i Forget tó remove it bevor sending to this Forum.
Here is my full Code:

Server:
`#include <rfb/rfb.h>
#include "stdio.h"

#define XRES 800
#define YRES 600
#define BITPSERSAMPEL 5
#define SAMPELSPERPIXEL 3 // One Sample represents a primary colour in that pixel
#define BYTESPERPIXEL 2

int main(int argc, char **argv)
{

  rfbScreenInfoPtr server = rfbGetScreen(&argc, argv, XRES, YRES, BITPSERSAMPEL, SAMPELSPERPIXEL, BYTESPERPIXEL);
  server->frameBuffer = (char *)malloc(XRES * YRES * BYTESPERPIXEL);
  memset(server->frameBuffer,0xac,XRES*YRES*BYTESPERPIXEL);

  server->serverFormat.depth = 16;
  server->serverFormat.redMax = 31;
  server->serverFormat.greenMax = 63;
  server->serverFormat.blueMax = 31;
  server->serverFormat.redShift = 11;
  server->serverFormat.greenShift = 5;
  server->serverFormat.blueShift = 0;

  rfbInitServer(server);
  rfbRunEventLoop(server, -1, FALSE);
  return (0);
}
`

client:

`
#include <signal.h>
#include <rfb/rfbclient.h>
#include "stdio.h"

#define XRES 800
#define YRES 600
#define BITPSERSAMPEL 5
#define SAMPELSPERPIXEL 3 // One Sample represents a primary colour in that pixel
#define BYTESPERPIXEL 2

static void update(rfbClient *cl, int x, int y, int w, int h)
{

  uint32_t *dataPointer = (uint32_t *)cl->frameBuffer;
  uint8_t *dataPointer_u8 = (uint8_t *)cl->frameBuffer;
  int i = 0;
  int compare = 0;
  int notCompate =0;
  for (int i = 0; i < 800 * 600 * 2; i++)
  {
    /* code */
    if (dataPointer_u8[i] == 0xac)
    {
      compare++;
    }
    else
    {
      notCompate++;
    }
  }
}

static void cleanup(rfbClient *cl)
{

  if (cl)
    rfbClientCleanup(cl);
}

int main(int argc, char **argv)
{
  rfbClient *cl;
  int i, j;
  do
  {
    cl = rfbGetClient(BITPSERSAMPEL, SAMPELSPERPIXEL, BYTESPERPIXEL);

    cl->GotFrameBufferUpdate = update;
    cl->format.bitsPerPixel = 16;
    cl->format.depth = 16;
    cl->format.trueColour = 1;
    cl->format.redMax = 31;
    cl->format.greenMax = 63;
    cl->format.blueMax = 31;
    cl->format.redShift = 11;
    cl->format.greenShift = 5;
    cl->format.blueShift = 0;
    cl->appData.enableJPEG = FALSE;

    char *clientParameters_pch[] = {"", "-encodings", "raw", "-compress", "0"};
    int numberOfArguments = 5;
    clientParameters_pch[0] = argv[0];

    if (!rfbInitClient(cl, &numberOfArguments, clientParameters_pch))
    {
      cl = NULL; /* rfbInitClient has already freed the client struct */
      cleanup(cl);
      break;
    }
    while (1)
    {
      i = WaitForMessage(cl, 500);
      if (i < 0)
      {
        cleanup(cl);
        break;
      }
      if (i)
      {
        if (!HandleRFBServerMessage(cl))
        {
          cleanup(cl);
          break;
        }
      }
      //     }
    }
  } while (1);
  return 0;
}`

**Comment by bk138** [comment]
Seems to work fine as the client does not output anything. If you want help, please make it easy to help you and post a complete example that triggers/exposes the problem you want to solve.

**Comment by tobiasamann** [comment]
Maybe it helps when I repeat my question:
In my server application I am writing at each point of the server frame buffer the same value „0xac“
  memset(server->frameBuffer,0xac,XRES*YRES*BYTESPERPIXEL);

My client application should receive a frame buffer where every byte is „0xac“.
But this is not the case!
In my update function of my client I am checking the content of the received frame buffer.
Please set a breakpoint when I am counting up the notCompate variable.

    /* code */
    if (dataPointer_u8[i] == 0xac)
    {
      compare++;
    }
    else
    {
      notCompate++;
    }

If you do this you will see that the client frame buffer is not equal to „0xac“ 
(This is what I wrote to the entire server frame buffer)

Difference in client server buffer:
frameBuffer[0] - frameBuffer[1] = 0x0, 0x0, 0x0, 0x0, 0xff, 0xff
frameBuffer[1600] - frameBuffer[1607] = 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0xff, 0xff
frameBuffer[3204] - frameBuffer[3209] = 0xff, 0xff, 0x00, 0x00, 0xff, 0xff
frameBuffer[4804] - frameBuffer[4809] = 0xff, 0xff, 0xff, 0xff, 0xff, 0xff

Why is the frame buffer of the client at some places different from the server frame buffer?

**Comment by bk138** [comment]
@tobiasamann my point is that I need a complete test program with outputs connected and stuff. I won't expand your sample program just to help you. It's _your_ duty to make helping you as easy as possible. :-)

**Comment by bk138** [comment]
Tentatively closing, feel free to re-open if issue persists and there is more info.
