### ISSUE TITLE
When the mouse slides

### ISSUE THREAD

**Issue by luchongbin** [LibVNC/libvncserver#326]
rfbProcessClientNormalMessage: unknown message type 54  When the mouse slides

**Comment by bk138** [comment]
where when how what OS? Really, please put in some more info!

**Comment by luchongbin** [comment]
windows 10

**Comment by bk138** [comment]
Please read https://www.softwaretestinghelp.com/how-to-write-good-bug-report/ and write a proper bug report.

**Comment by bk138** [comment]
@luchongbin please provide more detail

**Comment by bk138** [comment]
Tentatively closing, feel free to re-open if issue persists and there is more info.
