### ISSUE TITLE
rfbCheckFds: select: Bad file descriptor 

### ISSUE THREAD

**Issue by avently** [LibVNC/libvncserver#328]
Hello.
x11vnc worked stable for years. Then, maybe two months ago I updated all packages in Manjaro. Since than x11vnc crashes everytime I try to use it. 
These are the steps I do:
```
x11vnc -forever -rfbauth ~/.vnc/passwd -noremote -nevershared
```
Connecting from vnc client (Android). 
Server works fine.
Switching to another app (vnc client now in background)
Returning back to vnc client and getting java.io.EOFExpection
Server writes hundreds of lines of:
```
rfbCheckFds: select: Bad file descriptor
```
Next connection can be successful or not, random behaviour.

I tried with:
```
x11vnc -noxdamage -noxcomposite -nowf -forever -rfbauth ~/.vnc/passwd -noremote -nevershared
```

But in that situation the server crashes after some time:
```
13/05/2019 06:30:38 Got connection from client 192.168.1.36
13/05/2019 06:30:38   other clients:
13/05/2019 06:30:38 Normal socket connection
13/05/2019 06:30:38 incr accepted_client=8 for 192.168.1.36:39395  sock=0
13/05/2019 06:30:38 Client Protocol Version 3.8
13/05/2019 06:30:38 Protocol version sent 3.8, using 3.8
13/05/2019 06:30:38 rfbProcessClientSecurityType: executing handler for type 2
13/05/2019 06:30:39 Pixel format for client 192.168.1.36:
13/05/2019 06:30:39   32 bpp, depth 24, little endian
13/05/2019 06:30:39   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
13/05/2019 06:30:39 no translation needed
13/05/2019 06:30:39 Enabling LastRect protocol extension for client 192.168.1.36
13/05/2019 06:30:39 Enabling NewFBSize protocol extension for client 192.168.1.36
13/05/2019 06:30:39 Using ZRLE encoding for client 192.168.1.36
13/05/2019 06:30:40 client_set_net: 192.168.1.36  0.0360
caught XIO error:
13/05/2019 06:30:42 deleted 50 tile_row polling images.
```

You could say, "Your client is broken". But the client's version is the same as year ago, no changes here. 

What can I do to fix the issue?

**Comment by bk138** [comment]
@avently Can you please try https://github.com/LibVNC/libvncserver/blob/master/examples/example.c and https://github.com/LibVNC/libvncserver/blob/master/examples/blooptest.c to see if the issue happens there as well (and to maybe cut out x11vnc from the problem set?)?

**Comment by bk138** [comment]
Also, what happens if you comment out the 4 lines starting at https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L632 ?

**Comment by avently** [comment]
> Also, what happens if you comment out the 4 lines starting at https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L632 ?

The last commit that has easy detectable bug with `rfbCheckFds: select: Bad file descriptor` is 28a9a39981723502646338beb1ac691540613fca

So:
```
git checkout 28a9a39981723502646338beb1ac691540613fca
yaourt -P --noconfirm && sudo pacman -U /tmp/libvncserver/libvncserver-0.9.11.r126.gc49204c-1-x86_64.pkg.tar.xz
x11vnc -display :0 -rfbauth ~/.vnc/passwd -noremote -forever -nevershared -noxfixes -noxdamage -repeat
```

Then opening my vnc client, hiding the app to background, returning back -> `rfbCheckFds: select: Bad file descriptor`.

If in that commit (28a9a39981723502646338beb1ac691540613fca) I will comment the lines you mentioned  ```#ifdef LIBVNCSERVER_HAVE_LIBPTHREAD .....``` I will NOT get `rfbCheckFds` error. Everything works ok on "short distance". 

After that commit the bug with `rfbCheckFds` doesn't show up to me. So PR you merged really good. Looks like I made `git bisect` on a little bit old codebase, sorry for that, I thought I made a `git pull`` :/

So now first of two bugs from my first post is fixed. 
There is second bug:
`3/05/2019 06:30:40 client_set_net: 192.168.1.36  0.0360
caught XIO error:
13/05/2019 06:30:42 deleted 50 tile_row polling images.
`
But I have been testing the latest commits some days and can't meet the second bug. No crashes at all (got it only on 0.9.11 or 12). I hope it's already fixed.

Anyway, without steps to reproduce we can't do anything. You already made the best VNC server on the planet, thank you for that! And for you support.

I'll close this issue after a week if I don't find the second bug. Again, thank you.

**Comment by bk138** [comment]
@avently So everything is fine as is (wrt the first bug) or does it need the commenting out of https://github.com/LibVNC/libvncserver/blob/master/libvncserver/rfbserver.c#L632  ? For the second bug, please triage it against current x11vnc and open an issue there if the bug persists.

**Comment by avently** [comment]
>So everything is fine as is (wrt the first bug) or does it need the commenting out of

With PR you merged first bug is fixed so yes, this is fine without commenting out. I didn't meet errors about rfbCheck on the latest codebase.


>For the second bug, please triage it against current x11vnc

OK, I'll let you know if I find something

**Comment by bk138** [comment]
OK, closing then

**Comment by profy12** [comment]
Experimenting the bug of bad file descriptor here with libvncserver 0.9.12, there is a release planned to fix this ?

I will pull master and test your fixes.

**Comment by bk138** [comment]
@profy12 This will be in [0.9.13](https://github.com/LibVNC/libvncserver/milestone/5) which still is some way down the road...

**Comment by alechirsch** [comment]
I am running into this same issue. Multiple prints per second of `rfbCheckFds: select: Bad file descriptor` after losing focus or some random timing. I am connecting to the vnc server with noVNC@1.2.0
