### ISSUE TITLE
when client close,server error!msg: close.cpp line 48 fh>0&&(unsigned)fh < (unsigned)_nhandle

### ISSUE THREAD

**Issue by RubberFeng** [LibVNC/libvncserver#329]
**Describe the bug**
when client close the connect,server program will run the code following:
rfbserver.c line 573,574
if(cl->sock>=0)
	close(cl->sock);

**To Reproduce**
Replace with the following code:
if(cl->sock>=0)
	closesocket(cl->sock);

my system is Win10,and VS'Version is VS2015.

**Comment by bk138** [comment]
ACK, can repro with current master.

**Comment by bk138** [comment]
Using `closeseocket` instead of `close` fixes this, still have to find a way to do this cleanly.
