### ISSUE TITLE
How to built server and client on Windows machine?

### ISSUE THREAD

**Issue by tuphampro** [LibVNC/libvncserver#339]
I have some trouble building libvnc server on windows.
I followed the guidance from https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml.

**Environment**

    Windows 10
    cmake 3.15.1    
    Visual Studio 2019
    
But I get errors with: **Berkeley DB** and **Cyrus SASL.**
Can you please give some step by step instructions.

**Comment by bk138** [comment]
You'll have to use _exactly_ the same versions as in  the AppVeyor script.

**Comment by tuphampro** [comment]
I have trouble with **patch -p1 -i ..\sasl-fix-snprintf-macro.patch** and **nmake /f NTMakefile OPENSSL_INCLUDE=c:\OpenSSL-Win32\include ...**
Error: **path, nmake** is not recognized as an internal or external command.

**Comment by bk138** [comment]
https://superuser.com/questions/146577/where-do-i-find-nmake-for-windows-7-x64 and I hope the other one you can google as well :-)

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists.
