### ISSUE TITLE
Dynamic Resolution - support for setdesktopsize in LibVNCClient

### ISSUE THREAD

**Issue by antenore** [LibVNC/libvncserver#341]
Does LibVNC has something like the [RDP dynamic resolution](https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/Resolution-and-Scaling-Level-Updates-in-RDP-8-1/ba-p/248077)? 
Would it be feasible and do you have any interest in implementing it? 

With the dynamic resolution, when the client windows change in size, the size is sent to the server that adapt the resolution, so that it follows the one of the client.

Thanks for your support!

**Comment by antenore** [comment]
Wondering if it's something I can do myself... Maybe I'm just missing something

**Comment by bk138** [comment]
Hi @antenore! Yeah, I think requesting server resolution is possible via https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#setdesktopsize which is in LibVNCServer via 8e41510f4a9d449dd228e5b3e29732882f7f5df6, dunno about client side atm though :-)

**Comment by bk138** [comment]
No, it's only in the server at the moment.

**Comment by antenore** [comment]
Thanks, I'll have a look as well (slowly but hopefully surely )

**Comment by marcofortina** [comment]
Hello there! 

Do you have any update on https://github.com/LibVNC/libvncserver/pull/452?

Thanks,
Marco

**Comment by bk138** [comment]
> Hello there!
> 
> Do you have any update on #452?
> 
> Thanks, Marco

Changes request AFAIR. If someone would be willing to take over that PR, that'd be awesome!

**Comment by marcofortina** [comment]
I wrote some commts on https://github.com/LibVNC/libvncserver/pull/452/files

Could someone take a look?

Thanks

**Comment by MarkLTZ** [comment]
> > Hello there!
> > Do you have any update on #452?
> > Thanks, Marco
> 
> Changes requested AFAIR. If someone would be willing to take over that PR, that'd be awesome!

@bk138 I made a new PR https://github.com/LibVNC/libvncserver/pull/511 for managing Dynamic Resolution Updates. Could you please take a look?

Thanks

**Comment by marcofortina** [comment]
> > Hello there!
> > Do you have any update on #452?
> > Thanks, Marco
> 
> Changes requested AFAIR. If someone would be willing to take over that PR, that'd be awesome!

@bk138 I made a new PR https://github.com/LibVNC/libvncserver/pull/511 for managing Dynamic Resolution Updates. Could you please take a look?

Thanks
