### ISSUE TITLE
libvncserver 0.9.12 patch 8b06f83 broke the ConnectToRFBRepeater functionality.

### ISSUE THREAD

**Issue by KWBerry** [LibVNC/libvncserver#348]
It seems that the patch 8b06f83 has broken the VNC ConnectToRFBRepeater functionality.

Prior to updating my system to libvncserver version 0.9.12, which includes this patch, my VNC repeater configuration was working without problems.  My setup used the perl code implementation of the UltraVNC repeater interface called ultravnc_repeater.pl by Karl J. Runge.  Since upgrading libvncserver my setup no longer works.  I have traced the problem to libvncserver is not sending exactly 250 byte during the repeater connection setup partion of the interface. I also reviewed the offical UltraVNC repeater code found on line 71 of
https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/repeater/mode2_listener_server.cpp

Both sets of code are expecting exactly 250 bytes of characters during the establishment of the connection.

This patch attempts to prevent sending uninitialized data (an appropriate goal) by shorting the message sent to only the characters in the actual message (in my case to "ID:1234"), which breaks the interface design. The appropriate patch should have been to pad the message with null characters out the the full length of the buffer (250 bytes).

Thanks,

Kenneth Berry

**Comment by bk138** [comment]
@KWBerry dupe of #346 ?

**Comment by KWBerry** [comment]
Yes I believe it is a duplicate of #346. 
I did not know it was already reported, and I'm new at this and didn't know how to check.

My apologies !

Kenneth Berry

**Comment by bk138** [comment]
No prob! d87d25516b3992e52cf79e3cd6bd331b0baceecf and d1a134c89742296706327083d7db66c7250dc7d8 should have fixed it!
