### ISSUE TITLE
Does LibVNC server creates a virtual display?

### ISSUE THREAD

**Issue by philippemnoel** [LibVNC/libvncserver#364]
I would like to run a VNC server from a AWS virtual machine (Windows Server) with libVNCserver. However, since there is no monitor, it needs to create a virtual display. I know TightVNC/etc. do this, but I would like to write my own one using libVNCserver. I can't seem to find where it creates a virtual display, does it?

Philippe

**Comment by bk138** [comment]
it does not. you will need a server _application_ that does the interfacing with the os. libvncserver simply takes a memory range and exports this as a frame buffer.

you might want to look at https://github.com/LibVNC/vncterm if you want to export a virtual console.
