### ISSUE TITLE
support LibVncClient MSLogon for UltraVNC servers >= 1.2.0.5

### ISSUE THREAD

**Issue by vieridipaola** [LibVNC/libvncserver#372]
Hi,

I'm using software that's relying on libvnc to connect to UltraVNC servers (with MS Logon).
I verified that an old UltraVNC of 2009 actually works fine.

This is what shows up in the software's log:

VNC server supports protocol version 3.4 (viewer 3.8)
Selected Security Scheme -6
WARNING! MSLogon security type has very low password encryption! Use it only with SSH tunnel or trusted network.
VNC authentication succeeded

However, recent versions such as Ultr@VNC 1.2.0.5 fail with something like this in the software's log:

VNC server supports protocol version 3.8 (viewer 3.8)
We have 2 security types to read
0) Received security type 17
1) Received security type 113
Unknown authentication scheme from VNC server: 17, 113

Using libvnc 0.9.12.

Do you think it would be possible to support MS Logon for recent UltraVNC servers?

Vieri

**Comment by vieridipaola** [comment]
https://forum.ultravnc.net/viewtopic.php?f=4&t=34796#p105447

**Comment by bk138** [comment]
I reckon you are reffering to libvncclient?

**Comment by vieridipaola** [comment]
Yes, libvncclient.
Since UltraVNC is also open-source it may be useful to check the client code here:

https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/

I presume the functions AuthMsLogonII() and AuthMsLogonI() are of interest here.

**Comment by bk138** [comment]
> Yes, libvncclient.
> Since UltraVNC is also open-source it may be useful to check the client code here:
> 
> https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/
> 
> I presume the functions AuthMsLogonII() and AuthMsLogonI() are of interest here.

Thanks! What file are they in?

**Comment by vieridipaola** [comment]
https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/ClientConnection.cpp

**Comment by gitdevmod** [comment]
Hi,
I'm having same issue VNC Server: UltraVNC 1.2.2.4 and MS Logon enabled. When I try to connect to a computer with krdc there is no prompt for user and password. There is no timeout and connection is not closed.
In UltraVNC logs:

Tue Oct 27 13:57:55 2020
vsocket.cpp : VSocket() m_pDSMPlugin = NULL 
vncsockconnect.cpp : accepted connection from XX
vncserver.cpp : AddClient() started
vncclient.cpp : vncClient() executing...
vncserver.cpp : AddClient() done
vncclient.cpp : client connected : XX (1)
vncclient.cpp : DSMPlugin Pointer to socket OK
vncclient.cpp : Send protocolMsg
vncclient.cpp : Send_OK
vncclient.cpp : m_ms_logon set to truevncclient.cpp : negotiated version
Entered InitAuthenticate
vncserver.cpp : client XX verifiedHost 0 prior to adjustment
vncserver.cpp : client XX verifiedHost 0 after adjustment
c:\users\rudi\desktop\ultravnc\winvnc\winvnc\vncpasswd.h : PASSWD : ToText called
vncclient.cpp : loopback connection attempted - client accepted
c:\users\rudi\desktop\ultravnc\winvnc\winvnc\vncpasswd.h : PASSWD : ToText called
vsocket.cpp : zero bytes read2
vncserver.cpp : removing unauthorised client
vncserver.cpp : RemoveClient() done
vncclient.cpp : ~vncClient() executing...
vncclient.cpp : deleting socket
vsocket.cpp : closing socket

It would great to have this support.

By the way disabling MSLogon, I can connect to ultravnc server.

**Comment by takuy** [comment]
Any updates on this? This would be insanely helpful for UltraVNC-based servers where MSLogon is required.

**Comment by bk138** [comment]
I'd be happy to merge a PR. Personally I'm very busy with my day job, so this might take a while to get tackled.

**Comment by silicontrip** [comment]
This might be relevant, gvncviewer can connect to an UltraVNC server using protocol 113, looks like they use libgvnc.  Also UltraVNC is on github; https://github.com/ultravnc/

**Comment by kevans91** [comment]
Hi,

I've pushed PR #480 to address this; any of you folks here able to grab the patch and give it a test spin in a production environment (and report back on the PR)?

Thanks!

**Comment by Neustradamus** [comment]
cc @RudiDeVos.
