### ISSUE TITLE
Lowering bandwidth

### ISSUE THREAD

**Issue by carlonluca** [LibVNC/libvncserver#373]
Hello, to cope with low bandwidth connections, I can currently set the color depth in rfbPixelFormat inside rfbClient. Unfortunately, this is insufficient for my use case. I could also try to ask the server to scale the content (there is no need for a large image), or lower the number of colours used (although I see that minimal color depth is 8 bit). Can this be done with libvnc?

I tried to look for a scaling capability and found https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbclient.h#L131, which seems to be what I need. I tried to set it to 2 after rfbGetClient and before rfbInitClient, and then I also used SendScaleSetting after rfbInitClient. None of these seemed to work. Is it possible to ask the server to scale the content?

I also tried to look for a way to ask for less colours (to increase the compression). This seems to be possible with other clients. I found https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbclient.h#L121, can this be useful in this context? I also see that https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbclient.h#L701 allows to specify the number of samples and the number of bits per each sample, but setting 1 bit per sample, for instance, does not seem to work. It would be useful to be able to get grayscale for instance. Is any of this supported?

Thank you!

**Comment by bk138** [comment]
Do you want to adapt dynamically or just set some low-throughput setting at connection start? Not sure if adapting dynamically would work - maybe it does.

If the latter is the case, I'd try with Tight encoding and specifying compression level and quality. You can see [here](https://github.com/bk138/multivnc/blob/48f1aafd2ea5357dcebeece276c342ffb82492a2/src/gui/MyFrameMain.cpp#L480) how another  vnc client handles this.

**Comment by carlonluca** [comment]
Hello,
thank you for your answer. I already use tight, with compression 9 and quality 1. It works and the result is the same that I have with other VNC clients.
As the frame rate is still pretty low, my idea would be to ask the VNC server to scale down the framebuffer to improve the result even more: I typically connect to high resolution devices (I cannot change it), but I don't clearly need 1080p stream to control it. Far lower resolution would be more than sufficient.
Digging into the sources, I found some parts that seem to indicate that scaling at the source may be possible: is this correct? Doing it before the connection would be perfect. Is this possible? Is there an example somewhere? Is the application you linked able to do it?
Thanks!

**Comment by bk138** [comment]
TBH, I would have to dig into the sources as well - it _might_ be possible. For the low framerate, I have another hint tough: try asking for Framebuffer updates continously, as RFB is server-push per default, not client-pull. I have done this in [here](https://github.com/bk138/multivnc/blob/master/src/VNCConn.cpp#L1112) and it defenitely improves responsiveness.

**Comment by carlonluca** [comment]
Thank you for the last advice. It seems it is improving a bit the responsiveness, but when a large portion of the screen changes, it still takes a lot to arrive entirely.
I also see that tight supports custom palettes (PaletteFilter). In the sources I found this: https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbproto.h#L877. Reducing the number of colours may be useful. I still do not understand though how to use it. Atm I'm setting the encoding via https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbclient.h#L118. Do you know how to set that palette maybe?
Thanks for your help.

**Comment by carlonluca** [comment]
I was able to actually implement transmission with lower number of colours, like 2, 4, 8 etc... This can be done by playing with a suitable palette and values in https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbproto.h#L200. Still don't know how to ask for scaling.

**Comment by bk138** [comment]
> Still don't know how to ask for scaling.

@carlonluca This https://github.com/bk138/droidVNC-NG/commit/482a8610cecff939c1c3586ae8bd13ee40631763 is how I did it for my Android VNC server. Basically scaling outside of LibVNCServer, then feeding the scaled FB in.

**Comment by carlonluca** [comment]
My understanding is that this is simply the server sending a scaled image, is this correct? What would be interesting is to request a specific size from the client and have the server respect that size.

**Comment by bk138** [comment]
> My understanding is that this is simply the server sending a scaled image, is this correct? What would be interesting is to request a specific size from the client and have the server respect that size.

Yeah that should work, but I never actually used it and have no idea in what state it is.

**Comment by bk138** [comment]
> I was able to actually implement transmission with lower number of colours, like 2, 4, 8 etc... This can be done by playing with a suitable palette and values in https://github.com/LibVNC/libvncserver/blob/master/rfb/rfbproto.h#L200. Still don't know how to ask for scaling.

@carlonluca would you be able to post which `rfbGetScreen` arguments worked for you (and especially how you set up palleted mode)? I'm writing up some docs on what to do for 'slow' links and this would be very useful!

**Comment by carlonluca** [comment]
Much time has passed, I do not clearly remember, however rfbGetScreen was called by passing in scaled width and height, where width was aligned up to 32 bit. Something like this:

```cpp
pitch = align_up(BPP * m_modeInfo.width / 2, 32);
width = pitch / BPP;
```

The scaling factor was fixed and decided by the server. I was looking for a way to set it from the client, which would have been more useful.

Palettes were created on the client by using `rfbPixelFormat`, passing proper offsets and storing it into `rfbClient->format`.

All this turned out to work properly back then.
