### ISSUE TITLE
Any plans to meke new release?

### ISSUE THREAD

**Issue by kloczek** [LibVNC/libvncserver#376]
Seems already on top of latest release in git are few CVEs fixed and would be good to have some release without those bugs.

If may as well ask to change tagging convention to just `<version>` without project name as git automatically adds to autogenerated from tag tar balls repo name it generates those tar balls with base dir like `libvncserver-LibVNCServer-<version>/`

**Comment by bk138** [comment]
Yes, progress for 0.9.13 is trackted [here](https://github.com/LibVNC/libvncserver/milestone/5). As you can see, it's slowly moving on, but help is greatly appreciated for the remaining issues.

**Comment by joakim-tjernlund** [comment]
remmina VNC SEGVs against vino now.
libvncserv git master works though

**Comment by bk138** [comment]
# final steps before release

- [ ] remove duplicate info from website

- [ ] remove duplicate info from README

- [ ] update TODO

- [ ] update NEWS

**Comment by bk138** [comment]
Maybe: https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/

**Comment by qmfrederik** [comment]
@bk138 Version 0.9.13 adds some new symbols (e.g. new fields to `rfbClientPtr` and new method such as `rfbDefaultNumberOfExtDesktopScreens` were added in https://github.com/LibVNC/libvncserver/commit/8e41510f4a9d449dd228e5b3e29732882f7f5df6).

Could you please bump the so version number? Since the changes are backward-compatible, just bumping the minor version (e.g. to 1.1) should be sufficient.

This would make sure that:
- Code that links with the newer version of libvncserver cannot run on older versions which do not have these symbols
- Code that dynamically interacts with libvncserver (such as Java or .NET wrappers) can detect the version of libvncserver in use.

I could probably put out a PR for that if you want.

**Comment by bk138** [comment]
Feel free to @qmfrederik :-)

**Comment by kloczek** [comment]
I'm not sure do you know that but if library ABI is changeing only by adding new symbols it makes more sense to use the same SONAME but with listing that new functions under new version.

That will allow to work with updated new library all older executables and DSOs without forcing to recompile all that stuff.
https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html

All what you need is to add sym file on linking with description of versioned sections. This is why so long for exaple glibc libc is not chgangeinG SONAME. You can see that that library has may sections which contaions new symbols added in exact version.

Just try command like `readelf --version-info /usr/lib64/libc.so.6` to see that :)

**Comment by kloczek** [comment]
With all work done by ld.so you don't need to care about detecting in Java or .NET of course :P

**Comment by bk138** [comment]
> I'm not sure do you know that but if library ABI is changeing only by adding new symbols it makes more sense to use the same SONAME but with listing that new functions under new version.

TBH makes more sense to me. How would you do that?

**Comment by kloczek** [comment]
- check list of currently exported symbols of your library (using nm or readelf)
- write sym to put in new versioned section new symbols
- check how to specify sym file with ABI description using cmake (I'm usually using am/ac/lt or meson however it should be plenty examples around of with google it should be pozssile to firnd necessary documentation in few seconds)

.. and that is all :P

Visibility of the DSO public symbol depends on visibility description. LTO for example removes from  that list (and generated DSO) automatically  whatever has no proper visibility marks or is not listed in sym file.

**Comment by bk138** [comment]
>     * check list of currently exported symbols of your library (using nm or readelf)
> 
>     * write sym to put in new versioned section new symbols
> 
>     * check how to specify sym file with ABI description using cmake (I'm usually using am/ac/lt or meson however it should be plenty examples around of with google it should be pozssile to firnd necessary documentation in few seconds)
> 
> 
> .. and that is all :P
> 
> Visibility of the DSO public symbol depends on visibility description. LTO for example removes from that list (and generated DSO) automatically whatever has no proper visibility marks or is not listed in sym file.

Yeah I mean like how exactly with CMake ? ;-) Can you provide a PR?

**Comment by kloczek** [comment]
Just in case please do not use in sym file regexps of the symbols which should be part of the public ABI. It causes at the moment issues with LTO. Just use precise/exact list of symbols which should be in ABI.

Using sym file as well prevents accidental remove some functions from source code (linker will fail if it will be not able to find in object files symbols which should be part of the ABI definition. In other words it is harder to break ABI :P

**Comment by kloczek** [comment]
I think that I found descent example in cmake :)

Please have look on:
https://github.com/openSUSE/libsolv/blob/master/src/CMakeLists.txt
and
https://github.com/openSUSE/libsolv/blob/master/src/libsolv.ver

**Comment by qmfrederik** [comment]
I don't have a strong opinion as to which approach is used - a simple function like `rfbGetLibVNCVersion` which just echos back the package version would also work for me.

**Comment by bk138** [comment]
> I don't have a strong opinion as to which approach is used - a simple function like `rfbGetLibVNCVersion` which just echos back the package version would also work for me.

You can simply use the value of `LIBVNCSERVER_VERSION`. Does this do the job for you @qmfrederik ?
