### ISSUE TITLE
Cross-compilation to iOS broken by eae530696e255389c467f7da7f90ee68789769f9 

### ISSUE THREAD

**Issue by iiordanov** [LibVNC/libvncserver#385]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/libvncserver

**Describe the bug**
When cross-compiling libvncserver to iOS on Mac OS, an error occurs due to commit eae530696e255389c467f7da7f90ee68789769f9. It's a complaint related to the CARBON_LIBRARY.

**To Reproduce**
Clone libvncserver
git clone https://github.com/leetal/ios-cmake.git
git clone https://github.com/LibVNC/libvncserver.git
cd libvncserver
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../ios-cmake/ios.toolchain.cmake

#### At this point, cmake throws the error below.

**Expected Behavior**
I expected cmake to complete successfully.

**Logs/Backtraces**
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CARBON_LIBRARY
    linked by target "examples_simple15" in directory /Users/iiordanov/libvncserver
    linked by target "examples_filetransfer" in directory /Users/iiordanov/libvncserver
    linked by target "examples_blooptest" in directory /Users/iiordanov/libvncserver
    linked by target "examples_vncev" in directory /Users/iiordanov/libvncserver
    linked by target "examples_storepasswd" in directory /Users/iiordanov/libvncserver
    linked by target "examples_camera" in directory /Users/iiordanov/libvncserver
    linked by target "examples_simple" in directory /Users/iiordanov/libvncserver
    linked by target "examples_repeater" in directory /Users/iiordanov/libvncserver
    linked by target "examples_regiontest" in directory /Users/iiordanov/ibvncserver
    linked by target "examples_pnmshow" in directory /Users/iiordanov/libvncserver
    linked by target "examples_colourmaptest" in directory /Users/iiordanov/ibvncserver
    linked by target "examples_pnmshow24" in directory /Users/iiordanov/libvncserver
    linked by target "examples_rotate" in directory /Users/iiordanov/libvncserver
    linked by target "examples_example" in directory /Users/iiordanov/libvncserver
    linked by target "examples_fontsel" in directory /Users/iiordanov/libvncserver
    linked by target "examples_mac" in directory /Users/iiordanov/libvncserver
    linked by target "examples_backchannel" in directory /Users/iiordanov/libvncserver

**Your environment (please complete the following information):**
Mac OS X Mojave
Xcode 11.3.1

**Additional context**
N/A

**Comment by bk138** [comment]
Thanks for reporting! Does https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Write-Platform-Checks#cmake-system yield different values for iOS and macOS and if yes, which ones?

**Comment by bk138** [comment]
or does `if (APPLE AND NOT IOS)` do the trick?

**Comment by iiordanov** [comment]
Looks like CMAKE_SYSTEM and CMAKE_SYSTEM_NAME are different at the very least.
 
Variables with iOS toolchain:

-- CMAKE_C_SYSTEM_FRAMEWORK_SEARCH_FLAG=-iframework 
-- CMAKE_EFFECTIVE_SYSTEM_NAME=Apple
-- CMAKE_HOST_SYSTEM=Darwin-19.3.0
-- CMAKE_HOST_SYSTEM_NAME=Darwin
-- CMAKE_HOST_SYSTEM_PROCESSOR=x86_64
-- CMAKE_HOST_SYSTEM_VERSION=19.3.0
-- CMAKE_INCLUDE_SYSTEM_FLAG_C=-isystem 
-- CMAKE_INCLUDE_SYSTEM_FLAG_CXX=-isystem 
-- CMAKE_SYSTEM=iOS-13.2
-- CMAKE_SYSTEM_APPBUNDLE_PATH=/Users/iiordanov/Applications;/Applications;/Applications/Xcode.app/Contents/Applications;/Applications/Xcode.app/Contents/Developer/Applications
-- CMAKE_SYSTEM_FRAMEWORK_PATH=~/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/Network/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks;/Library/Frameworks;/Network/Library/Frameworks;/System/Library/Frameworks
-- CMAKE_SYSTEM_INCLUDE_PATH=/usr/include/X11
-- CMAKE_SYSTEM_INFO_FILE=Platform/iOS
-- CMAKE_SYSTEM_LIBRARY_PATH=/usr/lib/X11
-- CMAKE_SYSTEM_LOADED=1
-- CMAKE_SYSTEM_NAME=iOS
-- CMAKE_SYSTEM_NAME=iOS
-- CMAKE_SYSTEM_PREFIX_PATH=/usr/local;/usr;/;/usr/local/Cellar/cmake/3.16.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr;/sw;/opt/local
-- CMAKE_SYSTEM_PROCESSOR=aarch64
-- CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED=1
-- CMAKE_SYSTEM_SPECIFIC_INITIALIZE_LOADED=1
-- CMAKE_SYSTEM_VERSION=13.2
-- CMAKE_SYSTEM_VERSION=13.2
-- PRESET_CMAKE_SYSTEM_NAME=TRUE

Variables without iOS toolchain:

-- CMAKE_C_SYSTEM_FRAMEWORK_SEARCH_FLAG=-iframework 
-- CMAKE_EFFECTIVE_SYSTEM_NAME=Apple
-- CMAKE_HOST_SYSTEM=Darwin-19.3.0
-- CMAKE_HOST_SYSTEM_NAME=Darwin
-- CMAKE_HOST_SYSTEM_PROCESSOR=x86_64
-- CMAKE_HOST_SYSTEM_VERSION=19.3.0
-- CMAKE_INCLUDE_SYSTEM_FLAG_C=-isystem 
-- CMAKE_INCLUDE_SYSTEM_FLAG_CXX=-isystem 
-- CMAKE_SYSTEM=Darwin-19.3.0
-- CMAKE_SYSTEM_APPBUNDLE_PATH=/Users/iiordanov/Applications;/Applications;/Applications/Xcode.app/Contents/Applications;/Applications/Xcode.app/Contents/Developer/Applications
-- CMAKE_SYSTEM_FRAMEWORK_PATH=~/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/Network/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks;/Library/Frameworks;/Network/Library/Frameworks;/System/Library/Frameworks
-- CMAKE_SYSTEM_INCLUDE_PATH=/usr/include/X11
-- CMAKE_SYSTEM_INFO_FILE=Platform/Darwin
-- CMAKE_SYSTEM_LIBRARY_PATH=/usr/lib/X11
-- CMAKE_SYSTEM_LOADED=1
-- CMAKE_SYSTEM_NAME=Darwin
-- CMAKE_SYSTEM_PREFIX_PATH=/usr/local;/usr;/;/usr/local/Cellar/cmake/3.16.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr;/sw;/opt/local
-- CMAKE_SYSTEM_PROCESSOR=x86_64
-- CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED=1
-- CMAKE_SYSTEM_SPECIFIC_INITIALIZE_LOADED=1
-- CMAKE_SYSTEM_VERSION=19.3.0
-- PRESET_CMAKE_SYSTEM_NAME=FALSE

**Comment by iiordanov** [comment]
I'm currently testing your other suggestion (APPLE AND NOT IOS)

**Comment by bk138** [comment]
Yeah, please check with https://github.com/LibVNC/libvncserver/commit/c30a5a8de3dae555cf20bd5131debfadbeb0d632 - that should do.

**Comment by iiordanov** [comment]
Confirmed with your commit. Thanks!
