### ISSUE TITLE
Implement remote desktop

### ISSUE THREAD

**Issue by SourceCodeZone** [LibVNC/libvncserver#388]
I am trying to implement remote desktop server using libvnc, I have downloaded the libvnc and build the library and able to run sample code. And in the example code I can see the function rfbGetScreen which display plain background not the desktop. Does that mean I have to find some other library to get desktop and share using vnc, or vnc has some inbuilt function to do this.

**Comment by bk138** [comment]
Yes, you (or your application) has to take care to fill the framebuffer yourself. See https://github.com/LibVNC/x11vnc for a server _application_ using this _library_.
