### ISSUE TITLE
Cross  compile for windows not generating .lib file

### ISSUE THREAD

**Issue by SourceCodeZone** [LibVNC/libvncserver#391]
I am using follwing command to cross compile libarary for windows 

```
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-cross-mingw32-linux.cmake ..
cmake --build .
```

But it's not generating .lib library compatible with windows, I can see the example directory with exe file but the libarary generated is `libvncserver.a` not `libvncserver.lib` what could be the issue.

**Comment by bk138** [comment]
It's generating static libraries ending in .a. You should set the `BUILD_SHARED_LIBS` CMake option to on in order to get shared libraries.

**Comment by SourceCodeZone** [comment]
Thanks for the response, I made BUILD_SHARED_LIBS=ON and now its generate dll file, I migrated the dll to windows and try to run basic example using libvnc server. but getting following error 

```
main.obj:-1: error: LNK2019: unresolved external symbol rfbGetScreen referenced in function main
main.obj:-1: error: LNK2019: unresolved external symbol rfbInitServerWithoutPthreadsButWithZRLE referenced in function main
main.obj:-1: error: LNK2019: unresolved external symbol rfbRunEventLoop referenced in function main
debug\Test.exe:-1: error: LNK1120: 3 unresolved externals
```

IDE: Qt creator
Compiler: Microsoft visual C++ compiler 2012(Amd64)

What could be the reason.

**Comment by bk138** [comment]
Seems you're not correctly linking to the DLL. Try the .a.

**Comment by SourceCodeZone** [comment]
Sorry for the late replay, actually I have linked correctly, but still showing the same error, I have tried with shared library and static library. Also tried with library compiled on windows using VS-2013 and cross compiled from linux, but got same error.

I have uploaded the project here, can you please check it.

https://github.com/SourceCodeZone/Test

**Comment by bk138** [comment]
I am sure you will understand that the priorities for my free time are with other projects, sorry. I can provide general advice, but no debugging of other projects. I provide freelance services for that.

**Comment by SourceCodeZone** [comment]
Ok no problem I understand, do you any reference to pre-built libvnc server for windows.

**Comment by bk138** [comment]
> Ok no problem I understand, do you any reference to pre-built libvnc server for windows.

I can point you at our CI provider: https://ci.appveyor.com/project/bk138/libvncserver/branch/master
