### ISSUE TITLE
[Client] Use per-session mutex for TLS r/w

### ISSUE THREAD

**Issue by gujjwal00** [LibVNC/libvncserver#398]
Currently a global mutex is used for all TLS (OpenSSL) sessions. Thanks @C8LUKA for pointing this out.

For storing per-session mutex, we have two options:
1. Store mutex pointer in `rfbClient`:
:+1: It can be used by both OpenSSL & GnuTLS code.
:+1: Easier implementation.
:-1: ABI change.
2. Store mutex pointer in `SSL` object's extra data:
:+1: No change to `rfbClient`
:-1: Implementation is a bit verbose.

I am in favor of option 1. @bk138 What do you think?

**Comment by bk138** [comment]
Why not use the hooks introduced in 1da7872784a78446284b4e8ef71691458296026c? That code is for applications to use, but we could maybe provide default handlers for OpenSSL?

**Comment by gujjwal00** [comment]
Application hooks are not a suitable solution for this problem IMO:

- Someone will ALWAYS have to implement them ( and correctly) to avoid segfaults/corruption. Multi-threaded apps cannot opt out of them AND have correct behavior. 
- Implementation of these hooks in all applications will look similar (if not exactly same). And if we provide default handlers, I don't thing anyone will ever override them.
- They will add unnecessary complexity because we will have to check for their existence & return value every time we use them. You can already see this in https://github.com/LibVNC/libvncserver/commit/1da7872784a78446284b4e8ef71691458296026c. 
- https://github.com/LibVNC/libvncserver/commit/1da7872784a78446284b4e8ef71691458296026c currently only protects `WriteToTLS`. I am hoping that apps are manually synchronizing all possible `ReadFromTLS` with mutex inside these hooks.

**Comment by bk138** [comment]
The thing is that OpenSSL comes with its own mutex support a library can use whereas GnuTLS does not, hence the hooks.

Status quo:
* Locking for OpenSSL backend uses global OpenSSL mutexes for read/write.
* Locking for GnuTLS backend uses hooks that an application has to fill, only protects writes.

(Correct me if I'm wrong here @gujjwal00 , writing this from memory...)

Some ways to go from here I see:
* Implement all locking in the library. This would need to pull in platform-specific locking frameworks, i.e. pthreads and win32threads. Mhhh :-/
* Use locking hooks for both OpenSSL and GnuTLS and add a big fat warning to the README.  Would not make use of OpenSSL locking but at least not different behaviour between backends. 

I feel there's more to this but I need a night to sleep it over ;-)

**Comment by gujjwal00** [comment]
FWIW, if we want to change status quo, we will need to change ABI in both options.


>The thing is that OpenSSL comes with its own mutex support a library can use whereas GnuTLS does not, hence the hooks.

I don't understand. What do you mean by 'mutex support'?

**Comment by bk138** [comment]
Ah nevermind, I got something wrong. I was referring to https://github.com/LibVNC/libvncserver/blob/9409a6e6aaeaff9dc36f71c21ba5b81b10d44ace/libvncclient/tls_openssl.c#L36 which kinda already implements the mentioned "Implement all locking in the library" approach but only for OpenSSL. Probably this should be factored out (to /common (and the server part, too)) and implemented for GnuTLS as well. If we go for this approach, I can help with unfifying the thread defines from libvnclient/tls_openssl and libvncserver.

**Comment by gujjwal00** [comment]
Can we reuse defines in [rfb.h](https://github.com/LibVNC/libvncserver/blob/master/rfb/rfb.h#L68-L130)? They are equivalent to the ones in tls_openssl.c.  

Only difference is `MUTEX_INIT` in tls_openssl.c which adds `PTHREAD_MUTEX_RECURSIVE` flag. I am not sure if we really need this flag but to preserve current behavior we can add a new macro `INIT_MUTEX_RECURSIVE` to rfb.h which adds this flag.

**Comment by bk138** [comment]
> Can we reuse defines in [rfb.h](https://github.com/LibVNC/libvncserver/blob/master/rfb/rfb.h#L68-L130)? They are equivalent to the ones in tls_openssl.c.

Yeah, kinda, they would need to go into their own header file in common.

> Only difference is `MUTEX_INIT` in tls_openssl.c which adds `PTHREAD_MUTEX_RECURSIVE` flag. I am not sure if we really need this flag but to preserve current behavior we can add a new macro `INIT_MUTEX_RECURSIVE` to rfb.h which adds this flag.

I'll have a look.
