### ISSUE TITLE
utf8 clipboard support

### ISSUE THREAD

**Issue by aiden0z** [LibVNC/libvncserver#399]
The tigervncserver has support unicode clipboard in version [1.10.10](https://github.com/TigerVNC/tigervnc/releases/tag/v1.10.0)。Does the libvncclient support utf8 string?

**Comment by bk138** [comment]
Not yet.

**Comment by arckalsun** [comment]
Do you have plans to support utf8?

**Comment by bk138** [comment]
We would like to have this, but someone would need to implement it.

**Comment by arckalsun** [comment]
I am curious that Unicode encoding is a big problem, but no one has implemented it. This is unbelievable.

**Comment by tsankuanglee** [comment]
Anything we can take from this PR?
https://github.com/TigerVNC/tigervnc/pull/834

**Comment by bk138** [comment]
Closed by 26bf37494a8ca5deaaa79d74cdda2da3af318e06, me thinks.

**Comment by Neustradamus** [comment]
Solved by:
- https://github.com/LibVNC/libvncserver/pull/468
