### ISSUE TITLE
Early cleanup of locking callbacks with OpenSSL

### ISSUE THREAD

**Issue by gujjwal00** [LibVNC/libvncserver#403]
For OpenSSL (< 1.1.0),  we need to provide locking callbacks to get thread safety. 

We are setting up these callbacks in [InitializeTLS()](https://github.com/LibVNC/libvncserver/blob/99307c133c934fb386c47038f50b9b9f82192a4e/libvncclient/tls_openssl.c#L152-L167). This is only done once per application run. 
These callbacks and the mutex buffer is cleaned up in [FreeTLS](https://github.com/LibVNC/libvncserver/blob/99307c133c934fb386c47038f50b9b9f82192a4e/libvncclient/tls_openssl.c#L689-L701). But the cleanup is performed on **first** call to `FreeTLS`. 

So if any app has multiple connections and closes one of them ( or disconnect -> reconnect single connection), rest of them will not be protected by these callbacks. `mutex_rw` is also affected by similar issue.

This would probably be fixed with the work in #401 but I have opened this issue to keep track of this bug.

**Comment by bk138** [comment]
It would probably be ok to just keep them inited during application lifetime and let the OS cleanup on process termination.
