### ISSUE TITLE
LibVNCClient: Question about non-blocking socket

### ISSUE THREAD

**Issue by gujjwal00** [LibVNC/libvncserver#408]
It may be a stupid question but why are we using non-blocking socket for client side?

For client, every IO on socket goes through `ReadFromRFBServer` & `WriteToRFBServer`. Both of them will not return to caller until given data has been sent/received. Furthermore, for TLS, `WriteToTLS` is blocking in itself while `ReadFromTLS` is non-blocking and relies on `ReadFromRFBServer` for it.

We have three ([1](https://github.com/LibVNC/libvncserver/blob/9c0ac92cb162df26a40772af52af440c7b0c01b6/libvncclient/sockets.c#L294-L305), [2](https://github.com/LibVNC/libvncserver/blob/9c0ac92cb162df26a40772af52af440c7b0c01b6/libvncclient/sockets.c#L900-L914), [3](https://github.com/LibVNC/libvncserver/blob/9c0ac92cb162df26a40772af52af440c7b0c01b6/libvncclient/tls_openssl.c#L171-L181)) different implementation of timed blocking for socket read/write. So we are essentially implementing blocking IO on top of non-blocking IO. We are also incurring the cost of extra `select` syscall.

**Comment by bk138** [comment]
That's for the useful timeouts @tobydox added.

**Comment by gujjwal00** [comment]
But we can set the timeout for `read`/`write` on a blocking socket.

**Comment by gujjwal00** [comment]
I have no problem with timeouts. They're useful and we should keep them. But instead of blocking on `select`, we should block directly on `read`/`write`.

**Comment by gujjwal00** [comment]
FWIW I can work on this if required. Otherwise we can close this issue (and I will shut up now)...

**Comment by bk138** [comment]
I see no urgent need of action as the code works as-is.

https://stackoverflow.com/questions/2597608/c-socket-connection-timeout indicates that the approach chosen by b8f2c50136de6c7a2daf594471a18db3a08b8870 is the way to go to achieve timeouts for _connect_ (not talking fo send/recv here!).

To quote an official work, "UNIX Network Programming", Vol 1, 3rd edition also says on p. 382 that SO_RCVTIMEO and SO_SNDTIMEO don't work with connect() and that a nonblockng technique shall be used.

**Comment by gujjwal00** [comment]
>I see no urgent need of action as the code works as-is.

ok.

>SO_RCVTIMEO and SO_SNDTIMEO don't work with connect() and that a nonblocking technique (or one involving alarm()) shall be used.

I know that and that's why none of the three references I linked in first comment refers to nonblocking behavior used by `connect`.

My only motivation was to reduce the number of syscalls and simplify the read/write logic when socket is not ready for IO.
