### ISSUE TITLE
common/threading.h: No such file or directory

### ISSUE THREAD

**Issue by tobydox** [LibVNC/libvncserver#421]
As of 621081f7cbe8ccf513c29794a7ee6e69e34ab5a4 projects using libvncclient or libvncserver fail to build since the common headers are not installed by `make install`:

```
/usr/include/rfb/rfbclient.h:58:10: fatal error: common/threading.h: No such file or directory
 #include <common/threading.h>
```

**Comment by bk138** [comment]
Oh my. What a huge mistake by me :facepalm: I'll fix ASAP - thanks for spotting!
