### ISSUE TITLE
endian problem (bug?)

### ISSUE THREAD

**Issue by davidguichard** [LibVNC/libvncserver#423]
I am playing around with lubuntu on an old powerpc mac; x11vnc does not work: when I try to connect using the realVNC client, the client says that the screen size is illegal, width 3687010 (and similar bad height). The real screen width is 1680. The two numbers are "the same" with the bytes switched. 
(I've also tried xtightvncviewer; it doesn't complain or crash, but it never shows a screen.)

As nearly as I can tell, the code handling this would be in the libvncserver library, not in x11vnc (I've looked at the x11vnc code, though I certainly haven't looked closely enough to understand the program in detail). So it seems pretty likely to me that libvncserver is sending the information with the wrong byte order, yes?

Update: I compiled the simple example 

#include <rfb/rfb.h>

int main(int argc,char** argv)
{
  rfbScreenInfoPtr server=rfbGetScreen(&argc,argv,400,300,8,3,4);
  server->frameBuffer=malloc(400*300*4);
  rfbInitServer(server);
  rfbRunEventLoop(server,-1,FALSE);
  return(0);
}

This has the same problem, so that removes x11vnc from the picture. So it appears libvncserver is not properly taking account of the endianness of the powerpc.

**Comment by bk138** [comment]
I recommended to do some printf debugging to find the exact location of the bug.

**Comment by davidguichard** [comment]
OK, I figured it out. In rfbproto.h is this line:

 define LIBVBNCSERVER_WORDS_BIGENDIAN 1

which should be

 define LIBVNCSERVER_WORDS_BIGENDIAN 1

In otherwords, it was misspelled.

**Comment by bk138** [comment]
Oh, but that is a grave bug then.

**Comment by bk138** [comment]
But apparently [not on our side](https://github.com/LibVNC/libvncserver/blob/395fb0d6cbfdd4547ee5183c3442e6421e25d7d1/rfb/rfbproto.h#L83).
