### ISSUE TITLE
not accepting Windows VNC viewer connections

### ISSUE THREAD

**Issue by br6** [LibVNC/libvncserver#429]
Describe the bug
Unable to connect from Windows 10/2019 vnc viewer (real, tight ultravnc)

To Reproduce
connect to the server, does not connect , the x11vnc.log in the server shows this
15/06/2020 23:11:10 Got connection from client 192.168.0.2
15/06/2020 23:11:10 0 other clients
15/06/2020 23:11:11 Normal socket connection
15/06/2020 23:11:11 Disabled X server key autorepeat.
15/06/2020 23:11:11 to force back on run: 'xset r on' (3 times)
15/06/2020 23:11:11 incr accepted_client=27 for 192.168.0.2:21728 sock=10
15/06/2020 23:11:11 Client Protocol Version 3.8
15/06/2020 23:11:11 Protocol version sent 3.8, using 3.8

Expected Behavior
Works perfectly fine on mac catalina, real vnc viewer on raspberrypi, ios and android, vnc on manjaro, ubuntu x64. even centos on windows 10 vmware image is connecting so windows is not blocking the address to local server in question, just the vnc server is not accepting vnc connetion from windows clients.

I am using X11VNC and os is manjaro arm 64bit raspberry pi4.
Ive tried libvncserver-git also via pamac no joy.

**Comment by bk138** [comment]
Please try example/example or, if this is really about x11vnc, file a bug there.

**Comment by br6** [comment]
Ive filed a bug there, but I think its related to libvncserver has that has had more changes recently, 
essentially any vnc viewer client running in Windows os will just hang, is there way to debug libvncserver output to a log? I am using aarch64 build,

**Comment by bk138** [comment]
I recommend building x11vnc with libvncserver 0.9.12 and then 0.9.13 and see if there are differences in behaviour.

**Comment by br6** [comment]
Ive tried both versions, using pamac build in manjaro (arch) nor sure what is happening,
linux ios android macos viewers all connect with varios viewers,but not Windows (10,2019, 2016).
it gets to 
22/06/2020 11:17:24 Got connection from client 192.168.0.2
22/06/2020 11:17:24   0 other clients
22/06/2020 11:17:25 Normal socket connection
22/06/2020 11:17:25 Disabled X server key autorepeat.
22/06/2020 11:17:25   to force back on run: 'xset r on' (3 times)
22/06/2020 11:17:25 incr accepted_client=11 for 192.168.0.2:23525  sock=10
22/06/2020 11:17:25 Client Protocol Version 3.8
22/06/2020 11:17:25 Protocol version sent 3.8, using 3.8

**Comment by br6** [comment]
ssh tunnel is working fine

**Comment by bk138** [comment]
Let's close this one in favour of https://github.com/LibVNC/x11vnc/issues/135

**Comment by br6** [comment]
[2020-07-04T12:52:24+0100] [ALPM] upgraded curl (7.71.0-1 -> 7.71.1-1)
[2020-07-04T12:52:25+0100] [ALPM] upgraded librsvg (2:2.48.7-1 -> 2:2.48.8-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded python-setuptools (1:47.3.1-1 -> 1:48.0.0-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded flatpak (1.7.2-1 -> 1.8.1-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded libappindicator-gtk3 (12.10.0-14 -> 12.10.0.r296-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded libuv (1.38.0-1 -> 1.38.1-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded tslib (1.21-2 -> 1.22-1)
[2020-07-04T12:52:29+0100] [ALPM] upgraded qt5-base (5.15.0-3 -> 5.15.0-4)

these updates fixed things for me
