### ISSUE TITLE
Missing dependency for turbojpeg test

### ISSUE THREAD

**Issue by DerDakon** [LibVNC/libvncserver#430]
Adding the test is wrapped behind

https://github.com/LibVNC/libvncserver/blob/b2ede8d5f5192171c79a736e1764f1b2ce5e53c6/CMakeLists.txt#L685

However the creation of the test executable is wrapped with this:

https://github.com/LibVNC/libvncserver/blob/b2ede8d5f5192171c79a736e1764f1b2ce5e53c6/CMakeLists.txt#L644

**Comment by bk138** [comment]
Thanks for spotting!
