### ISSUE TITLE
VNC Server for android

### ISSUE THREAD

**Issue by jerald-jacob** [LibVNC/libvncserver#433]
I like to know how can I implement vnc server for the android platform.

**Comment by bk138** [comment]
Next time please take the time to search the repo: https://github.com/LibVNC/libvncserver/blob/master/examples/androidvncserver.c :-)

Pecularities:
* quite old code, might not work on newer devices at all
* requires root

This is all we have.

**Comment by jerald-jacob** [comment]
Thanks for the response.

**Comment by bk138** [comment]
A working Android server app can now be found at https://github.com/bk138/droidVNC-NG and is open for contributions.
