### ISSUE TITLE
LibVNCServer and commercial products

### ISSUE THREAD

**Issue by clh5** [LibVNC/libvncserver#437]
Hi, our commercial product wants to make use of LibVNCServer to create our own VNC server and distribute. Will this be considered derivative work in the GPLv2 context?  

Does modifying LibVNCServer code or not make any difference in determining whether our VNC server will be considered derivative work?

Thanks for your help.

**Comment by bk138** [comment]
> Hi, our commercial product wants to make use of LibVNCServer to create our own VNC server and distribute. Will this be considered derivative work in the GPLv2 context?

Yes.

> Does modifying LibVNCServer code or not make any difference in determining whether our VNC server will be considered derivative work?

No.

> Thanks for your help.

You're very welcome! Please note that while you would have to stick to the GPL, you do not have to make your code public in case you use the derivative work internally in your organisation, see https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic

Hope this helps!
