### ISSUE TITLE
support for SetDesktopSize

### ISSUE THREAD

**Issue by snmishra** [LibVNC/libvncserver#44]
I tried in the docs and source code, but did not find any reference to SetDesktopSize . Could I request this as an enhancement? The relevant protocol specification seems to be at https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#id48

**Comment by thrix** [comment]
I would love to work on this feature, but currently I am currently interested only in client support. Will you accept patches only for client for the start?

**Comment by sequoiar** [comment]
+1

**Comment by bk138** [comment]
For a start, that is okay with me.

**Comment by bk138** [comment]
Added by 8e41510f4a9d449dd228e5b3e29732882f7f5df6 :-)
