### ISSUE TITLE
Bell (\a) causes hang in VNC client

### ISSUE THREAD

**Issue by gw1urf** [LibVNC/libvncserver#441]
**Describe the bug**

I've been using remmina, with VNC for the past few months. Several times a day, it would hang (completely unresponsive - no screen updates, nothing) and I'd have to kill it from outside my desktop environment. I was attributing this to network glitches. About 4 weeks ago I noticed that the hangs were always associated with beeps (e.g. bash completion, hitting ESC in vim too many times) generated by the remote end. I reconfigured my xterm to use visual beeps and disabled beeping in gvim and, since then, have not had a single hang.

**To Reproduce**

As an experiment, I opened an xterm with bell enabled (xterm +vb) and, inside that,
ran:

    while true ; do echo -ne "\a"; sleep 1 ; done

After a few minutes, using the desktop normally (and being driven slowly mad by the beeps), my remmina session hung.

**Expected Behavior**

Remmina session shouldn't hang!

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - OS and version: Debian Bullseye, kernel 5.7.0-2-amd64
 - Compiler and version: gcc 10.2.0 (Debian 10.2.0-5) but this is not a self-compiled copy of the code. I'm using the Debian packages for remmina (1.4.8+dfsg-1) and libvncvlient1 (0.9.13+dfsg-1). I'd rather not build everything from scratch to try to reproduce the bug, if possible, but can do if necessary.

**Additional context**

I've been asked by the remmina folks to report this as an issue with libvnc. The bug report over there is: 

[https://gitlab.com/Remmina/Remmina/-/issues/2261](https://gitlab.com/Remmina/Remmina/-/issues/2261)

**Comment by abemud** [comment]
Thanks for this report. I encounter this problem as well.

**Comment by bk138** [comment]
Hi guys, which VNC server with what version are you using?

**Comment by gw1urf** [comment]
Hi,

The problem was present when using TigerVNC on Debian Bullseye (tigervnc-standalone-server-1.10.1+dfsg-2).

The issue completely hung remmina. Not just the session, but all its icons became unresponsive. Killing remmina and reconnecting to the server resumed things just fine (i.e. all my existing windows at the remote end were still present and
responsive). 

However... I now can't reproduce the problem. Looking at my logs, I can see that, server-side, tigervnc-standalone-server
was updated to 1.10.1+dfsg-9 in September and, client-side, remmina-plugin-vnc was updated to 1.10.1+dfsg-9 in October.
libvncclient remains on version  0.9.13+dfsg-1

I'm quite happy to see this closed at present, since it no longer affects me. If you want me to do some more digging (downgrading packages) to try to reproduce it, that's also OK.

Thanks,
Alun.

**Comment by bk138** [comment]
Hi Alun,
If it's working for you now, feel free to close the issue :-)

**Comment by gw1urf** [comment]
OK, will do. If it comes back I'll re-open with more details.

Thanks,
Alun.
