### ISSUE TITLE
fails to cross-compile for android due to libz.a

### ISSUE THREAD

**Issue by 1000283** [LibVNC/libvncserver#457]
I'm trying to cross-compile for android, targeting armeabi-v7a, arm64-v8a, x86 and x86_64 but always get the same libz.a error and can't seem to disable libz in cmake.

My CmakeLists.txt currently has:
`option(WITH_ZLIB "Search for the zlib compression library to support additional encodings" OFF)`

My command line is:
```
cmake \
-DANDROID_NDK:PATH=${ANDROID_NDK_ROOT} \
-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake \
-DANDROID_NATIVE_API_LEVEL:STRING="16" \
-DBUILD_SHARED_LIBS:BOOL="0" \
-DWITH_ZLIB:BOOL="0" \
-DWITH_OPENSSL:BOOL="1" \
-DWITH_GCRYPT:BOOL="0" \
-DWITH_GNUTLS:BOOL="0" ..
```
I've tried many combinations, such as `-DWITH_ZLIB:BOOL="OFF"` and `-DWITH_ZLIB=OFF` but it just keeps being included.

In the end, i always get this result:
```
[ 50%] Linking C static library libvncclient.a
[ 50%] Built target vncclient
Scanning dependencies of target test_copyrecttest
[ 51%] Building C object CMakeFiles/test_copyrecttest.dir/test/copyrecttest.c.o
[ 52%] Linking C executable test/copyrecttest
ld: error: undefined symbol: arm_cpu_enable_crc32
>>> referenced by deflate.c:0 (external/zlib/deflate.c:0)
>>>               deflate.o:(deflateInit2_) in archive /home/myuser/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a

ld: error: undefined symbol: x86_cpu_enable_simd
>>> referenced by deflate.c:0 (external/zlib/deflate.c:0)
>>>               deflate.o:(deflateInit2_) in archive /home/myuser/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/test_copyrecttest.dir/build.make:105: recipe for target 'test/copyrecttest' failed
make[2]: *** [test/copyrecttest] Error 1
CMakeFiles/Makefile2:147: recipe for target 'CMakeFiles/test_copyrecttest.dir/all' failed
make[1]: *** [CMakeFiles/test_copyrecttest.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
```

It does build the static libs, but fails to build the shared libs.

### environment
Host: x86_64 Ubuntu Xenial
NDK: 22.0.7026061
toolchain: included clang 11.0.5 et al
Cmake: 3.19.2

**Comment by bk138** [comment]
So you want/need to build w/ WITH_ZLIB to OFF?

**Comment by 1000283** [comment]
Unless zlib is mandatory, i may not need it.
If i can build with zlib, ok.
If my build is failing because of zlib, i would like to disable it unless there is a quick fix.

**Comment by bk138** [comment]
It's not mandatory. OTOH, you can build with zlib. Your build is likely failing because of something else because I know builds that work, for example https://github.com/bk138/multivnc/blob/master/android/app/src/main/cpp/CMakeLists.txt#L43

**Comment by bk138** [comment]
Tentatively closing, feel free to re-open is issue persists.
