### ISSUE TITLE
x11vnc showing double mouse cursor #157

### ISSUE THREAD

**Issue by navinp0304** [LibVNC/libvncserver#459]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/libvncserver

**Describe the bug**
I'm running an aws ec2 ubuntu instance . I'm trying to play a game under wine/playonlinux in the ubuntu instance. On my laptop there are no double mouse cursor when i start the game under wine. I don't have the double pointer under wine for things like opening control panel on aws ec2 instance.

So i tried few vnc server like x2go,tightvncserver and others. I was not even able to start the game. Then i tried x11vnc with options x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :0 -auth /var/run/lightdm/root/:0 -usepw but in this case i couldn't move mouse . So i did add -xkbd and -xptr to give x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :0 -auth /var/run/lightdm/root/:0 -usepw -grabkbd -grabptr -grabalways.
Now when i move mouse i can see there are 2 mouse pointers and i can start the game. I tried -overlay but it also doesn't fix the double mouse cursor.

The top mouse pointer belongs to the game and you can click options like new game /load game etc but the below mouse pointer is confusing and when you click it on the options it does nothing.

**Expected Behavior**
There shouldn't be 2 mouse pointers.

**Screenshots**
![double_mouse](https://user-images.githubusercontent.com/74448943/105134914-251c8900-5b15-11eb-991f-21b129c5fe71.jpg)

**Your environment (please complete the following information):**
aws ec2 ubuntu instance 20.04 focal.

**Comment by bk138** [comment]
Let's keep it at the one issue https://github.com/LibVNC/x11vnc/issues/157
