### ISSUE TITLE
compile Windows dll

### ISSUE THREAD

**Issue by josej69git** [LibVNC/libvncserver#460]
hi. Sorry if this is not the place for this question but i can´t found right place.
I'm trying to cross compile libvnc server in Linux for use dll in visual basic under Windows but i get some errors and can't compile it. Search in google for dll binaries but not found in any site... There are pre-compiled dll for direct download and use under Windows?
Thanks

**Comment by bk138** [comment]
No, there aren't any. You can have a look at https://github.com/LibVNC/libvncserver/blob/master/.travis.yml#L17 and its output at https://travis-ci.org/github/LibVNC/libvncserver/jobs/749595834 to get an idea on how to cross-compile with MinGW.

**Comment by bk138** [comment]
Also, there is https://github.com/LibVNC/libvncserver#crosscompiling-from-linux-to-windows
