### ISSUE TITLE
Dropped pixels in tight vnc encoding

### ISSUE THREAD

**Issue by peda-r** [LibVNC/libvncserver#461]
Hi!

I'm seeing strange effects with what appears to be forgotten pixels when I use x11vnc. The below "100" (only part of the whole screen) is rendered like this with both TigerVNC, TightVNC and an own RFB client implementation, so I went looking for the issue server side.
![100](https://user-images.githubusercontent.com/8825182/109003238-79340380-76a7-11eb-9999-34e6711b35fa.png)

My X11 server is using 32 bpp, a depth of 24 bits and I have verified that the problem areas are encoded with the Tight encoder, specifically (in RFB spec terminology) BasicCompression, PaletteFilter and has more than two colors (but other areas might also have problems).

The libvncserver code is unfamiliar territory for me, but I think I have an explanation right about here in the tight encoder.
https://github.com/LibVNC/libvncserver/blob/242fda806d16f06890fb61339aa0a585443af8bb/libvncserver/tight.c#L1499

What if there is "garbage" in the unused bits? Then the bitwise comparison, which is not masking out the unused "garbage" bits, will simply step past the pixel, not finding any matching entry in the palette. And after looking at FastFillPalette (32) it certainly looks like the "garbage" bits can be stripped from the entries in the palette in case no translation for the wire pixel format is needed.

Cheers,
Peter

**Comment by bk138** [comment]
Thanks for that very nice bug report and PR! I'll have a look ASAP!

**Comment by peda-r** [comment]
Big sigh. I have been juggling too many versions and must have been thoroughly confused. After checking and rechecking everything the following is what I found.

With x11vnc 0.9.11 there is a problem, and I have a reproducer.
With x11vnc 0.9.13 I see no problem, if I do exactly the same thing.

To reproduce I swap the contents of a file that x11vnc reads with -rawfb map:/some/file@32x32x32 such that sometimes there is garbage in the bits outside the RGB mask, sometimes not.

I have verified that 0.9.13 is not using something entirely different to encode the rect, so it really looks like the problem has been fixed, but looking at what has changed between 0.9.11 and 0.9.13, I find nothing that looks relevant in libvncserver/tight.c, so this problem must have been cleared up by some change external to tight.c. Or, I'm missing something...

Sorry for wasting time.

**Comment by peda-r** [comment]
Digging in the history, the bug starts to appear if I go back long enough for there to be autoconf support in libvncserver, and also build the package using autoconf. If I build those old versions with cmake, the bug is no more. Wierd.

**Comment by bk138** [comment]
Huh, indeed. But anyway, thanks so much for clearing this up and investing time.Very much appreciated! Ok to close then?

**Comment by bk138** [comment]
Closing now, feel free to re-open if there's more to add.
