### ISSUE TITLE
Accessing LibVNC

### ISSUE THREAD

**Issue by Evilsmaher** [LibVNC/libvncserver#463]
I apologize if this is not the correct location, but I am having an issue utilizing LibVNC. I simply want to utilize the features of LibVNC such as rfb.h/c etc. I tried pulling the code using the .zip feature on Github, then running the commands below, but I get weird errors such as <rfb/rfb.h> doesn't exist. I changed it to "rfb/rfb.h" so it was the local version, but then I was getting the 
> no CMakeLists.txt

```
mkdir build
cd build
cmake ..
cmake --build .
```

Nonetheless, I was having issues pulling this. I'm sure I am doing it wrong. How would I go about correctly utilizing LibVNC and running the simple example?

**Comment by bk138** [comment]
The commands you list are correct and work. Please think about what a person trying to help you with your issue might need in terms of information.

**Comment by Evilsmaher** [comment]
In essence, I was hoping to get a breakdown of exactly how to compile and run the `simple.c` in step form -- obviously I shouldn't have had to change `<rfb/rfb.h>` to `"rfb/rfb.h", I only did it as a quick fix; What is the appropriate way to compile and get an executable working using the `<rfb/rfb.h>` inclusion?

For example: (This is obviously not correct, just for example purposes)

"""
1. Download the Zip from https://github.com/LibVNC/libvncserver where it says "Code"
2. ...
3. ...

Great, now you can use <rfb/rfb.h>.

If you decide to create a folder say, c:\...\desktop\testVNC, you can utilize <rfb/rfb.h> by making sure you have ...
"""

Does this make sense?

**Comment by bk138** [comment]
Well, still unclear is:
* what OS are you on?
* what compiler are you using?
* what error message do you face?

I kinda guess that you're on some Windows version?

**Comment by Evilsmaher** [comment]
1. Windows
2. GCC
3. When I do `gcc -o example.exe example.c` I get the below error. Note: I don't have it in front of me, that was the concept. 
> CMakeLists.txt doesn't exist in this folder

**Comment by bk138** [comment]
Well I can only point you at https://github.com/LibVNC/libvncserver#how-to-build and https://github.com/LibVNC/libvncserver/blob/master/.appveyor.yml as well as https://github.com/LibVNC/libvncserver/blob/master/.travis.yml for how scripted builds work. Maybe you can come up with a suggestions to improve the docs when you've found a solution.

Sorry, can't help you unless you provide a detailed step-by-step description :-/

**Comment by Evilsmaher** [comment]
Here are the steps I have:

1. Pull Code From Github
2. Unzip as - C:\Users\...\Desktop\libvncserver-master\libvncserver-master\
3.
```
mkdir build
cd build
cmake ..
```

I get the error:
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/bratl/Downloads/libvncserver-master/libvncserver-master/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/bratl/Downloads/libvncserver-master/libvncserver-master/build/CMakeFiles/CMakeError.log".

**CMakeOutput.log:**
>The system is: Windows - 10.0.18363 - AMD64

**CMakeError.log:**

> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags:  

> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: -c 
> 
> The output was:
> The system cannot find the file specified
> 

> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: -Aa 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: -D__CLASSIC_C__ 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags:  
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: -c 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: -Aa 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: -D__CLASSIC_C__ 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: cl 
> Build flags: 
> Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
> 
> The output was:
> The system cannot find the file specified
> 
> 
> Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>

**Comment by bk138** [comment]
Well it says it
 ```Tell CMake where to find the compiler by setting either the environment
variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
the compiler, or to the compiler name if it is in the PATH.```

You should ask over at https://cmake.org/discourse-forum/ for instance - this is a CMake thing, not a LibVNCServer one.
