### ISSUE TITLE
Pixel width 1 short?

### ISSUE THREAD

**Issue by jaggzh** [LibVNC/libvncserver#464]
It looks like the vnc server (krfb in multiple new debian testing systems) is sending a desktop that's 1px too short.

It seems older vnc viewers don't handle this well -- all of them will "wrap" the display rows (writing directly to a memory buffer, so each row is one off?  It results in a slanted display).

xtigervncviewer is the only one in Debian Stable that I've found that still shows the screen rectangular, and it reports:
```
 PlatformPixelBuffer: Using shared memory XImage
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using Tight encoding
 DesktopWindow: Requesting framebuffer resize from 1599x1200 to 1780x916
 DesktopWindow: 1 screen(s)
```
krdc (also debian stable) shows this (not sure how useful it is):
```
QWidget::setMaximumSize: (/VncView) Negative sizes (-2147483648,-2147483648) are not possible
```

**To Reproduce**
1. Use one Debian Stable system (client), one Debian Testing system (server (krdc in my case))
2. Connect from client.  You should see slanted display. (See attached).

I'm guessing new clients ensure rows are written as rows, so they don't fail (Debian testing -> testing works fine).  However, the 1599 coming through seems like it's the actual source of the problem.

The server is using official nvidia drivers from Debian's non-free component(s).
It also has a monitor (1600x1200 and a TV attached (1920x1080).  Note that the monitor (1600) is currently off, but it's the primary and the 1599 would seemingly then be coming just from the linux desktop reporting of.. something.

**Expected Behavior**
New servers should be compatible with all clients, as much as possible.  I'm not sure where this 1599 is coming from though.

**Your environment (please complete the following information):**
Linux debian testing (server),
Linux debian stable (client),
libvncserver1 0.9.11+dfsg-1.3+deb10u4

libvncclient1 (from debian-stable): 
0.9.11+dfsg-1.3+deb10u4
![Screenshot_20210302_090627](https://user-images.githubusercontent.com/20318973/109685904-93059880-7b36-11eb-9269-f72305b65c1e.png)

**Comment by bk138** [comment]
This looks like an integer overflow issue and might be fixed in newer LibVNCServer versions - please try with the current release 0.9.13.

**Comment by jaggzh** [comment]
The server itself is already 0.9.13.
(That's the version that comes from the current debian testing repository).

**Comment by bk138** [comment]
If LibVNCServer on the server side is alreay 0.9.13, please try with one of the [basic examples](https://github.com/LibVNC/libvncserver/tree/master/examples), `camera` or `example` might be good fits. If the bug is reproducible with those, I should be able to repro as well. Otherwise, I think it's a server _app_ issue, not a _library_ one.

**Comment by bk138** [comment]
Tentatively closing this, feel free to post more info once it's there.
