### ISSUE TITLE
repeater example broken since v0.9.11

### ISSUE THREAD

**Issue by BerryCol** [LibVNC/libvncserver#465]
repeater example just show how to connet an UltraVNC Repeater，then，how to send data？ I used UltraVNC Viewer  to connect the Repeater，it didn't show anything.

**Comment by BerryCol** [comment]
![image](https://user-images.githubusercontent.com/40679211/110195372-a5a20980-7e77-11eb-85f4-fe13dab3f4d4.png)
just this!

**Comment by bk138** [comment]
Yes, that needs better documentation. TBH, I also don't really know how it's supposed to work. Would need some trying out and then documenting.

**Comment by bk138** [comment]
Just got info from another user that with the LibVNCServer version 0.9.10 the repeater works.

**Comment by giodegio** [comment]
Yes @bk138, as I anticipated you, the latest version (I downloaded the master release on 2022, January 13th)
presents the problem as described by BerryCol:

if you configure and start a VNC server to use the repeater (I used the source examples\repeater.c),
and you start a client connection to connect to that server (with ultraVNC client), 
on the repeater web interface you see both client and server associated to each other,
but on the client interface you see permanently the message "Negotiate Protocol Version..." and the
VNC connection will never fully complete.

I tried to checkout backward in the sources until I obtained a working version:
with the LibVNCServer version 0.9.10 the repeater works.
Using the same example examples\repeater.c, you can connect to that server through the repeater
and you see the server test frame buffer.

Evidently from version 0.9.11, correcting some other bugs, the repeater functionality has been broken.
I tried to understand where the problem is, but it's not easy: I don't master the sources of libVNCserver so deeply.

Greetings

**Comment by bk138** [comment]
@giodegio can you describe your exact setup and what commands you use to connect to which instance? That'd be super nice!

**Comment by giodegio** [comment]
Of course @bk138. Following is my setup with comments, so you can reproduce the problem.

1) A Windows Machine running the ultravnc repeater
To install the repeater:
. Instructions and Download: https://uvnc.com/downloads/repeater/83-repeater-downloads.html
. Install: extract and double click on the .exe
When it starts, windows firewall will ask to allow traffic for it: confirm on the base of your network configuration 
(private / public interfaces). Moreover the default listening port is 80: if it is in use it will use the first free 
consecutive port. Take note of the used one, notified through a MessageBox (in my case is 81).

![immagine](https://user-images.githubusercontent.com/3766315/151878231-6853c355-f496-4169-bedb-6928a0d2165a.png)

Then you can open a browser to the url http://localhost:YOUR_LISTENING_PORT
As the documentation explains, the default user is: admin
the default password is: adminadmi2

You will see the web console with configurations and status.
![immagine](https://user-images.githubusercontent.com/3766315/151881658-ede6e368-9dc5-4ac2-a9ac-52512e18b303.png)
Default Listening port for VNC viewers: 5901
Default Listening port for VNC servers: 5500

2) A Windows Machine running the ultravnc server to test the repeater (to be sure it's working properly)
I used the same machine where the repeater is running.
To configure the VNC server to use the repeater follow the instructions at:
https://uvnc.com/docs/uvnc-repeater.html
"Setting Up VNC Server For Repeater"
. Go to C:\Program Files\uvnc bvba\UltraVNC and open up ultravnc.ini
. Under the section [admin] add the following setting: 

		service_commandline = -autoreconnect ID:123456789 -connect YOUR_REPEATER_IP_ADDRESS:5500
		
NOTE: 
MANDATORY: to allow the VNC server to make use of the repeater, the VNC server must be installed and started as service!
I don't know why, but if you don't do this it will not work!
		
When the VNC server starts you will see on the repeater console the VNC server connection status with its ID (123456789).
![immagine](https://user-images.githubusercontent.com/3766315/151879868-48813fa5-1990-4b71-811a-d5c63b1b1157.png)

Try to connect to it with any VNC viewer  (I used ultravnc viewer for simplicity) from another machine on your network.
In the viewer window:

			Computer: ID:123456789
			Flag "Use repeater"  and as address write: YOUR_REPEATER_IP_ADDRESS:5901

![immagine](https://user-images.githubusercontent.com/3766315/151879980-4d4191bb-9752-4800-946d-4fdc3a8a47ee.png)

Then, you should connect to your test server and control its desktop.
On the repeater web console you will see the server and the viewer associated to each other:

![immagine](https://user-images.githubusercontent.com/3766315/151880082-6533f2dd-14d6-4c88-8bc8-db7e125faa18.png)

3) Then you need a Linux Machine where you can clone the LibVNCserver repository: try first with the actual master (or any release greater or equal to 0.9.11).
Compile it: you will obtain the library and the examples.
	
NOTE: for simplicity you can compile it using as target an ubuntu x86 machine and your local gcc,
but I can assure you that the results are exactly the same also cross-compiling the sources for my armv7 linux embedded board.

4) Now you can launch the repeater example using the LibVncServer library:

		./repeater 111222333 YOUR_REPEATER_IP_ADDRESS 5500
		
You will see it in the repeater console (ID = 111222333):
![immagine](https://user-images.githubusercontent.com/3766315/151880373-f3b767b9-70e6-4146-88ae-6cf106e87c9a.png)

I added comments in the repeater console to help recognize my VNC servers.

5) Start an ultravnc viewer and connect to the libVncServer example server.

		Computer: ID:111222333
		Flag "Use repeater"  and as address write: YOUR_REPEATER_IP_ADDRESS:5901

![immagine](https://user-images.githubusercontent.com/3766315/151880555-7a256687-1d76-4b28-94ef-e418175c836a.png)

You will see server and viewer associated in the repeater web console:
![immagine](https://user-images.githubusercontent.com/3766315/151880615-b772d2cc-37f6-42ee-af5f-ddb82f0d66b2.png)

6) You wil obtain that the client start to connect to the server, but…
![immagine](https://user-images.githubusercontent.com/3766315/151880704-1fa4798b-6ac6-4b93-9c4e-dc2b94c60b54.png)

…the connection never completes: you will see permanently the message "Negotiate Protocol Version…".
You have to cancel to close the viewer window.

7) If you use the version 0.9.10, doing the same steps described above, you obtain the remote example framebuffer:
The viewer connected to the libVNCserver repeater example: 
![immagine](https://user-images.githubusercontent.com/3766315/151880901-2369018a-fb6a-4e93-bb50-66074fe95557.png)

Be careful, when the viewer disconnects from the working server, the server will terminate, so you have to relaunch it (it's configured in this way in the example sources).

NOTE: I didn't specify the various steps needed to build sources using cmake, but I only emphasize that to build the 0.9.10 version you have to install the libgcrypt20-dev package:

		sudo apt-get install libgcrypt20-dev

Sorry for the verbose description, I hope it wiil be useful.

Cheers

**Comment by bk138** [comment]
@giodegio thanks, that will be super helpful!

**Comment by bk138** [comment]
Alright, can confirm it works with 0.9.10  and fails with 0.9.11.

**Comment by bk138** [comment]
Bisecting gives me: cdd81bd479e228724ef03bf94c42a34feb42145a is the first bad commit

**Comment by giodegio** [comment]
That's Wonderful! Now it works! @bk138 You are a great man! ;) Thanks!
