### ISSUE TITLE
crash at function rfbClientCleanup

### ISSUE THREAD

**Issue by tfzxyinhao** [LibVNC/libvncserver#47]
<pre>

static void Cleanup(_rfbClient* cl){
    if (cl){
        ClientDataEx* data = (ClientDataEx*)rfbClientGetClientData(cl, (void*)CLIENTDATAKEY);
        if (data){
            SDL_DestroyWindow(data->win);
            delete data;
        }
        rfbClientCleanup(cl);
    }
}

int _tmain(int argc, char* argv[])
{
    SDL_Event e;
    char result = 0;
    rfbClient *client = rfbGetClient(8,3,4);

    if (client){
        client->serverHost = "192.168.0.59";
        client->serverPort = 5901;
        client->canHandleNewFBSize = TRUE;

        client->Bell = Bell;
        client->GetPassword = GetPassword;
        client->MallocFrameBuffer = MallocFrameBuffer;
        client->FinishedFrameBufferUpdate = FinishedFrameBufferUpdate;
        client->GotFrameBufferUpdate = GotFrameBufferUpdate;
        client->GotCopyRect = GotCopyRect;
        client->GotCursorShape = GotCursorShape;
        client->GotXCutText = GotXCutText;
        client->HandleCursorPos = HandleCursorPos;
        client->HandleKeyboardLedState = HandleKeyboardLedState;
        client->HandleTextChat = HandleTextChat;
        client->HandleXvpMsg = HandleXvpMsg;
        client->SoftCursorLockArea = SoftCursorLockArea;
        client->SoftCursorUnlockScreen = SoftCursorUnlockScreen;

        if (!rfbInitClient(client, &argc, argv)){
            Cleanup(client);
        }
        else{
            initSDL(client);
            while (1)
            {
                if (SDL_PollEvent(&e)){
                    if(!handleSDLEvent(client, &e))
                        break;
                }
                else{
                    int ret = WaitForMessage(client, 500);
                    if (ret < 0){
                        Cleanup(client);
                        break;
                    }
                    else if (ret  > 0){
                        if (!HandleRFBServerMessage(client)){
                            Cleanup(client);
                            break;
                        }
                    }
                }
            }
        }
    }
    return 0;
}
</pre>

when call function "rfbClientCleanup" my program was crash,
carsh at follow code

<pre>
if (client->sock >= 0)
    close(client->sock);
</pre>

**Comment by zni** [comment]
If `rfbInitClient` is returning false, it might be because inside `rfbInitClient` the call to `rfbInitConnection` is failing. If that happens, `rfbClientCleanup` is called by `rfbInitClient`, which might be why your program is crashing when you try to call `rfbClientCleanup` again.

**Comment by willbprog127** [comment]
I know this is an old issue, but still a troublesome one.  Checking the client to see if it's null is not really a good test for choosing to run `rfbClientCleanup`.  

Can you add a flag to the client that indicates that it's been cleaned up already?  The flag could be cleared when initializing the client, then set when it can't be initialized or when cleanup has happened.

Or perhaps some other _definite_ method for determining if a client has been cleaned up?  I've looked at what is freed in the `rfbClientCleanup` method and none of those appear to allow for consistent cleanup checking.  I've had a few un-fun crashes in my app because of this gotcha.

Thanks! :smile:

**Comment by bk138** [comment]
Is this still happening with  current master?

**Comment by willbprog127** [comment]
> Is this still happening with current master?

This does happen from time to time.  It's very frustrating.  Seems like it happens more on macOS than Linux, but it's possible Linux is doing something right with the system calls while macOS just throws up its hands and crashes.

**Comment by bk138** [comment]
@willbprog127 can this be closed in the wake of #330?

**Comment by willbprog127** [comment]
> @willbprog127 can this be closed in the wake of #330?

In my case, yes, it can be closed. 👍

**Comment by bk138** [comment]
well then 😉
