### ISSUE TITLE
BUG: CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by KangLin** [LibVNC/libvncserver#474]
**Describe the bug**

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LZO_LIBRARIES
    linked by target "vncclient" in directory C:/Source/libvncserver
    linked by target "vncserver" in directory C:/Source/libvncserver

**To Reproduce**

1. vcpkg install zlib  libssh pixman libjpeg-turbo freerdp libdatachannel
2. mkdir build
    cmake ..  -DCMAKE_TOOLCHAIN_FILE=[vcpkg installation path]/scripts/buildsystems/vcpkg.cmake
    
**Logs/Backtraces**

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
Could NOT find LZO
Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR) 
Some or all of the gtk libraries were not found. (missing: GTK2_GTK_LIBRARY GTK2_GTK_INCLUDE_DIR GTK2_GDK_INCLUDE_DIR GTK2_GDKCONFIG_INCLUDE_DIR GTK2_GDK_LIBRARY GTK2_GLIB_INCLUDE_DIR GTK2_GLIBCONFIG_INCLUDE_DIR GTK2_GLIB_LIBRARY) 
Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) 
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
Could NOT find FFMPEG (missing: FFMPEG_INCLUDE_DIRS FFMPEG_LIBRARIES avformat avcodec avutil swscale) (Required is at least version "3.1.0")
Building crypto with builtin functions, only including SHA1 and D3DES
Threads support is using win32 threads
Building without TLS
Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LZO_LIBRARIES
    linked by target "vncclient" in directory C:/Source/libvncserver
    linked by target "vncserver" in directory C:/Source/libvncserver

Generating done

**My environment (please complete the following information):**
 - OS and version: Windows 10.0.19042.
 - Compiler and version:   
 - Cmake version: 3.20.4
 - vcpkg version: c5ac711fefa6cacbd6bb6335349e36a765babf87

**Comment by bk138** [comment]
Tentatively closing as Windows builds [work](https://ci.appveyor.com/project/bk138/libvncserver/branch/master/job/cx2im421lo2ncbo2?fullLog=true), feel free to post some new info once you have it available.
