### ISSUE TITLE
Receiving wrong data

### ISSUE THREAD

**Issue by marshal2111** [LibVNC/libvncserver#478]
Hello! I’m trying to implement VNC client into my Qt application, but after successful initializtion client starting to recieve some kind of invalid data: 

_29/07/2021 12:51:42 VNC server supports protocol version 3.8 (viewer 3.8)
29/07/2021 12:51:42 We have 2 security types to read
29/07/2021 12:51:42 0) Received security type 2
29/07/2021 12:51:42 Selecting security type 2 (0/2 in the list)
29/07/2021 12:51:42 1) Received security type 16
29/07/2021 12:51:42 Selected Security Scheme 2
29/07/2021 12:51:42 VNC authentication succeeded
29/07/2021 12:51:42 Desktop name "fpl1007-101104"
29/07/2021 12:51:42 Connected to VNC server, using protocol version 3.8
29/07/2021 12:51:42 VNC server default format:
29/07/2021 12:51:42   32 bits per pixel.
29/07/2021 12:51:42   Least significant byte first in each pixel.
29/07/2021 12:51:42   TRUE colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
29/07/2021 12:51:42 Unknown encoding 'tight'
29/07/2021 12:51:42 Unknown encoding 'zrle'
29/07/2021 12:51:42 Unknown encoding 'zlib'
29/07/2021 12:51:42 Got new framebuffer size: 1280x800
29/07/2021 12:51:42 Unknown message type 255 from VNC server
29/07/2021 12:51:42 Unknown message type 50 from VNC server
29/07/2021 12:51:42 Unknown message type 255 from VNC server
29/07/2021 12:51:42 Unknown message type 159 from VNC server
29/07/2021 12:51:42 Rect too large: 9593x109 at (220, 30)
29/07/2021 12:51:42 Rect too large: 30x9593 at (39508, 141)
29/07/2021 12:51:42 Unknown message type 255 from VNC server
29/07/2021 12:51:42 Unknown message type 253 from VNC server_ 
....and so on.

I’v tested connection in VNCviewer application and all was ok there.
 I will appreciate if someone tells the reason of this unexectable behaviour. Thank you!

**Comment by bk138** [comment]
Hi! Please note that the issue tracker is for bugs and feature requests, you might reach more people in the chat over at https://gitter.im/LibVNC/libvncserver
