### ISSUE TITLE
Presence of libva does not mean we have X11

### ISSUE THREAD

**Issue by maxnet** [LibVNC/libvncserver#48]
Compiling libvncserver for an embedded system that does have libva, but does not have X11, results in:

```
In file included from rfbproto.c:2406:0:
h264.c: At top level:
h264.c:22:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
```

Think that if libvncserver can only work with the X11 version of libva, it should check for the presence of libva-x11 instead of just checking if libva has vaInitialize.

**Comment by dverbeir** [comment]
I have no objection to the removal as I have no plans to update this code and you are correct that the server side patch I had provided for qemu/vnc was never merged into mainline qemu. Also, the actual data format was too dependent on the libva implementation details, being only slice data with some implementation and full H.264 bitstream with some other.

**Comment by bk138** [comment]
Mhh, so h264 encoded VNC is dead everywhere?

**Comment by dscho** [comment]
My 2 cents: it would be more appropriate to add a check whether the detected libva version can be used, and disable libva support if the code would not compile. That way, you keep things working for those who rely on it, but you fix the compile issues for those who experience them. Just my 2 cents, @bk138 you are the boss now!

**Comment by maxnet** [comment]
Did got it to a point where it does *compile* now with newer libva versions by including va_compat.h (7b6243157f042a7bde353abc6fb22aadad6d9e2d)
However I still think that including code that compiles, but none of us have actually tested, and may crash upon use for all we know, is wrong.
Also the moment libva retires the compatibility glue provided by va_compat.h, it will break again.

**Comment by bk138** [comment]
Removed the H.264 stuff as per https://github.com/LibVNC/libvncserver/commit/612de004c47586d74d5a93901a2d94ca1fc3f5e3
