### ISSUE TITLE
libwinpthread-1.dll

### ISSUE THREAD

**Issue by MarlikAlmighty** [LibVNC/libvncserver#482]
When launched under windows 7, backchannel.exe says that there is no libwinpthread-1.dll. Can add instruction to cmake for statics?

**Comment by bk138** [comment]
Hi! Are you building with MSVC or MinGW?

**Comment by MarlikAlmighty** [comment]
MinGW

**Comment by bk138** [comment]
https://www.google.com/search?q=mingw+libwinpthread should help but we can add this to the docs as well ;-)

**Comment by MarlikAlmighty** [comment]
Tnx.

**Comment by MarlikAlmighty** [comment]
I still haven't found how to compile this on Linux for Windows.

Has anyone resolved this issue?

**Comment by MarlikAlmighty** [comment]
```
set ( COMPILER_PREFIX "i686-w64-mingw32" )
# set ( COMPILER_PREFIX "x86_64-w64-mingw32" )

set ( CMAKE_CXX_STANDARD_LIBRARIES "-static-libgcc -static-libstdc++ -lwsock32 -lws2_32 ${CMAKE_CXX_STANDARD_LIBRARIES}" )
set ( CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive" )
```

It's work.
