### ISSUE TITLE
Handle of Ultra MSLogonIIAuth does not work when library is compiled with OpenSSL only

### ISSUE THREAD

**Issue by qunying** [LibVNC/libvncserver#493]
With UltraVNC server 1.3.4.2, enable MSLogonII auth, if compiled the library with OpenSSL only, SDLvncviewer could not connect, got "VNC connection failed: authentication rejected". If compiled the library with GCRYPT and GNUTLS, it works.

The test is on the main trunk code.

**Comment by bk138** [comment]
Can confirm this. Looks like there's something wrong in https://github.com/LibVNC/libvncserver/blob/master/common/crypto_openssl.c

**Comment by bk138** [comment]
Closed by #550.
