### ISSUE TITLE
include header for calling rfbssl_init()

### ISSUE THREAD

**Issue by derekschrock** [LibVNC/libvncserver#501]
I don't know if this info is old but based off the recommendation here https://github.com/LibVNC/libvncserver/issues/91#issuecomment-149641057 it seems that you're asking servers to set the cert and key then execute `rfbssl_init()` when they want to init an SSL server.

However, `rfbssl_init()` isn't in a .h file provided by the project.  Should the prototype for `rfbssl_init()` be included in `rfb.h` or another file `rfb_ssl.h` be installed?

It seems that if websockets support is fully enabled then just setting the cert and key would be enough setup for SSL then `rfbRunEventLoop` will init ssl in time.

I guess the alt. is to just extern `rfbssl_init()` however it seems that function should be in a .h if you expecting servers to execute the function.

**Comment by bk138** [comment]
IIRC the function is for internal use only, we got several implementations (OpenSSL, GnuTLS) which are exposed by rfbssl.h, the only user right now is websockets.c, though this will hopefully change with #396 some time. The user/developer documentation is [here](https://github.com/LibVNC/libvncserver#using-secure-websockets) so it boils down to setting key and cert and the library will take over the rest internally.

**Comment by derekschrock** [comment]
Ok I couldn't tell if it was internal.  Thanks for the update.
