### ISSUE TITLE
Error in README file

### ISSUE THREAD

**Issue by madscientist159** [LibVNC/libvncserver#52]
The README file states the defaultPtrAddEvent() function should be called for proper mouse cursor updates, but the defaultPtrAddEvent() function was renamed to rfbDefaultPtrAddEvent() at some point.

The README should be upated with the new function name to reduce confusion.

**Comment by bk138** [comment]
PR welcome!

**Comment by madscientist159** [comment]
I'm not sure if the pull request was done correctly as I normally use a vastly different GIT infrastructure, but the pull request *should* be available for your review.

Let me know if you need anything changed.

Thanks!

**Comment by bk138** [comment]
Fixed by e8f6ddeddf7992560811e06b4fa3fb58ea172e17
