### ISSUE TITLE
Using VNC Viewer to connect failed

### ISSUE THREAD

**Issue by pzh2386034** [LibVNC/libvncserver#523]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/libvncserver

I try to make a connection to BMC embeded VNC server from my laptop VNC viewer, but it's failed.If I change to tight vnc client, it is ok.
vnc viewer client display:`Protocol error: unknown rect encoding 7`

**Logs/Backtraces**
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Got connection from client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 0 other clients
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Client Protocol Version 3.8
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Protocol version sent 3.8, using 3.8
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientSecurityType: executing handler for type 1
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000018)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000016)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x0000000F)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC6)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Enabling full-color cursor updates for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Enabling NewFBSize protocol extension for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Using ZRLE encoding for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Pixel format for client 172.16.91.16:
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 8 bpp, depth 6
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 true colour: max r 3 g 3 b 3, shift r 4 g 2 b 0
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000018)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000016)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x0000000F)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC6)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Enabling full-color cursor updates for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Enabling NewFBSize protocol extension for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Switching from ZRLE to raw Encoding for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000018)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000016)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x0000000F)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC6)
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Enabling full-color cursor updates for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Enabling NewFBSize protocol extension for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Switching from raw to ZRLE Encoding for client 172.16.91.16
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 Pixel format for client 172.16.91.16:
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 32 bpp, depth 24, little endian
Feb 11 11:10:19 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:19 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
Feb 11 11:10:20 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:20 rfbProcessClientNormalMessage: read: Connection reset by peer
Feb 11 11:10:20 0000000000000001 obmc-ikvm[30775]: 11/02/2022 11:10:20 Client 172.16.91.16 gone

**Your environment (please complete the following information):**
 - OS and version:windows 10; vncviewer 6.22.315; 

**Additional context**
![image](https://user-images.githubusercontent.com/9897310/171604581-15d2ba44-d94b-4463-86cd-35b59285c2c4.png)

**Comment by bk138** [comment]
You should file a bug with the client as it's failing.

**Comment by bk138** [comment]
Tentatively closing until more info is provided. Feel free to post here.
