### ISSUE TITLE
How to install LibVNCServer/LibVNCCLient in Ubuntu

### ISSUE THREAD

**Issue by cybersecurity99** [LibVNC/libvncserver#526]
Hi 
I am trying install LibVNC but there is no guide . How to build didn't work
I download the source and run the following commands:
```mkdir build
cd build
cmake ..
cmake --build .```

But when I try to run this sample program 
```
#include <rfb/rfb.h>

int main(int argc,char** argv)
{
  rfbScreenInfoPtr server=rfbGetScreen(&argc,argv,400,300,8,3,4);
  server->frameBuffer=malloc(400*300*4);
  rfbInitServer(server);
  rfbRunEventLoop(server,-1,FALSE);
  return(0);
}
```
I get the issue rfb/rfb.h not found.
Is there any solution to this

**Comment by bk138** [comment]
You need to read up on the basics :-) 

See https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html for how to specify the include path.

Also, libvncserver is available prepackaged in Ubuntu, you need to install https://packages.ubuntu.com/focal/libvncserver-dev
