### ISSUE TITLE
[Question] Get the client keyboard layout

### ISSUE THREAD

**Issue by workgroupengineering** [LibVNC/libvncserver#538]
Is there any way to retrieve the vnc client keyboard layout information? eg: de,pc105

**Comment by RokerHRO** [comment]
Not in the standard VNC protocol, and not in the extensions specified in https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst so far. Maybe there is a proprietary VNC implementation that support this feature, but I doubt that.

What is the usecase for the VNC server to know the keyboard layout of the VNC client?

**Comment by workgroupengineering** [comment]
Thanks for the reply.

> What is the usecase for the VNC server to know the keyboard layout of the VNC client?

to make sure the keyboard key pressed on the client side match on the server.
