### ISSUE TITLE
[Question]By not providing "FindLibSSH2.cmake" in CMAKE_MODULE_PATH this project has   asked CMake to find a package configuration file provided by "LibSSH2", but   CMake did not find one.

### ISSUE THREAD

**Issue by JivinDotL** [LibVNC/libvncserver#539]
How to solve the following problems?

CMake Warning at CMakeLists.txt:139 (find_package):
  By not providing "FindLibSSH2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibSSH2", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibSSH2" with any
  of the following names:

    LibSSH2Config.cmake
    libssh2-config.cmake

  Add the installation prefix of "LibSSH2" to CMAKE_PREFIX_PATH or set
  "LibSSH2_DIR" to a directory containing one of the above files.  If
  "LibSSH2" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by bk138** [comment]
Please tell us something about your LibVNCServer version and environment.

**Comment by JivinDotL** [comment]
I just git clone the last.

commit 0121f6d35fd433d0c2dae22ee8689637f9b40fc8 (HEAD -> master, origin/master, origin/HEAD)

**Comment by bk138** [comment]
Yeah seems the file was forgotten, I'll have a look

**Comment by JivinDotL** [comment]
Thank you for your quick reply. @bk138

**Comment by bk138** [comment]
89a03f014f7517094d04442632f7896e1d06e606 apparently missed it :-/
