### ISSUE TITLE
Bundled novnc version has hextile decoding issues

### ISSUE THREAD

**Issue by maxnet** [LibVNC/libvncserver#54]
Bundled novnc client version has issues when hextile encoding is being used.
To illustrate:

![hextile](https://cloud.githubusercontent.com/assets/1123701/5769144/e1f5c4d2-9d17-11e4-8d8d-0c9d13033d7c.png)

Has been fixed upstream ( https://github.com/kanaka/noVNC/issues/411 )

Don't know if you prefer to stick to the novnc version you currently have, and would like to cherry pick fixes for bugs like this, or prefer simply copying latest novnc code shortly before the next libvncserver release.
So didn't submit pull request.

**Comment by bk138** [comment]
Am Thu, 15 Jan 2015 16:02:17 -0800
schrieb maxnet <notifications@github.com>:

> Bundled novnc client version has issues when hextile encoding is
> being used. To illustrate:
> 
> ![hextile](https://cloud.githubusercontent.com/assets/1123701/5769144/e1f5c4d2-9d17-11e4-8d8d-0c9d13033d7c.png)
> 
> Has been fixed upstream ( https://github.com/kanaka/noVNC/issues/411 )
> 
> Don't know if you prefer to stick to the novnc version you currently
> have, and would like to cherry pick fixes for bugs like this, or
> prefer simply copying latest novnc code shortly before the next
> libvncserver release. So didn't submit pull request.
> 

last option.

**Comment by Hello71** [comment]
afaict, novnc is just static files; if this is true, why bundle it at all?

**Comment by bk138** [comment]
mhh, don't get your point here.

**Comment by Hello71** [comment]
why bundle novnc if you make no changes and need to update it manually?

**Comment by bk138** [comment]
Because we want to have a working web client in the release tarball. That's about it.
