### ISSUE TITLE
novnc view_only mode does not work when connected to libvncserver

### ISSUE THREAD

**Issue by maxnet** [LibVNC/libvncserver#55]
With both the novnc version currently bundled with libvncserver, and the latest one, novnc does not seem to  display the screen content until one either moves the mouse over the display area, or holds a key.
And when using view_only mode, by appending to "&view_only=1" to the URL, it does not display the content at all.

E.g. connected to libvncserver's example.c:

![novnc-viewonly](https://cloud.githubusercontent.com/assets/1123701/5777822/46426fe8-9d96-11e4-918c-5c4412a89772.png)

Tested with both Firefox and Chrome.

**Comment by bk138** [comment]
If this happens with other servers as well, it is a novnc bug... 

Am 16. Januar 2015 15:46:27 MEZ, schrieb maxnet <notifications@github.com>:
>With both the novnc version currently bundled with libvncserver, and
>the latest one, novnc does not seem to  display the screen content
>until one either moves the mouse over the display area, or holds a key.
>And when using view_only mode, by appending to "&view_only=1" to the
>URL, it does not display the content at all.
>
>E.g. connected to libvncserver's example.c:
>
>![novnc-viewonly](https://cloud.githubusercontent.com/assets/1123701/5777822/46426fe8-9d96-11e4-918c-5c4412a89772.png)
>
>Tested with both Firefox and Chrome.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LibVNC/libvncserver/issues/55

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by maxnet** [comment]
Don't know whether the bug is in novnc or libvncserver, however it only happens when connected to libvncserver.

Do get visual with qemu, although it is not instant either, and can take about 5 seconds.
Tested by:

- leaving example.c running, so I could use its webserver.
- entering `qemu-system-x86_64 -vnc :1,websocket` 
- going to: http://127.0.0.1:5800/novnc/vnc_auto.html?host=127.0.0.1&port=5701&true_color=1&view_only=1

![novnc-qemu](https://cloud.githubusercontent.com/assets/1123701/5778648/1f455638-9d9d-11e4-97b7-cc6874e10b32.png)

**Comment by bk138** [comment]
Can you ask @kanaka  about it?

**Comment by bk138** [comment]
Ok, I've checked. There's simply no FramebufferUpdateRequest coming in when I just connect with novnc, only after some input.

**Comment by maxnet** [comment]
>There's simply no FramebufferUpdateRequest coming in when I just connect with novnc, only after some input.

Seems it does is supposed to send it combined with SetPixelFormat and SetEncodings

https://github.com/kanaka/noVNC/blob/master/include/rfb.js#L959

**Comment by maxnet** [comment]
I think the problem is that libvncserver does not handle the case correctly when more than a single VNC command is received inside a websockets frame.

In main.c clientInput() you have a loop that tests sockets for pending data:

```
n = select(cl->sock + 1, &rfds, &wfds, &efds, &tv);
[...]
if (FD_ISSET(cl->sock, &rfds) || FD_ISSET(cl->sock, &efds))
  rfbProcessClientMessage(cl);
```

It calls rfbProcessClientMessage() which only processes a single VNC command.

Without websockets this will work.
If there is more bytes to be read after processing a single VNC command, on the next round of the loop, select() will indicate there is pending data again, and rfbProcessClientMessage() will be called again.


However I think that when using websockets, the entire frame is read in, and stored in an internal buffer in the websockets handling code. In that case select() will not indicate the pending data being there...

While it may be possible to modify the novnc code so that it sends every client command in a separate websockets frame as a workaround, I suspect there may be similar problems with the SSL handling code and this code needs to be refactored.

**Comment by bk138** [comment]
Mhh, who added websockets? Me thinks it was @tenchman, he can possibly shed some light on this!

**Comment by maxnet** [comment]
After replacing in novnc's rfb.js:

```
var response = RFB.messages.pixelFormat(this._fb_Bpp, this._fb_depth, this._true_color);
response = response.concat(
	RFB.messages.clientEncodings(this._encodings, this._local_cursor, this._true_color));
response = response.concat(
	RFB.messages.fbUpdateRequests(this._display.getCleanDirtyReset(),
		this._fb_width, this._fb_height));
this._timing.fbu_rt_start = (new Date()).getTime();
this._timing.pixels = 0;
this._sock.send(response);
```

With:

```
this._sock.send(RFB.messages.pixelFormat(this._fb_Bpp, this._fb_depth, this._true_color));
this._sock.send(RFB.messages.clientEncodings(this._encodings, this._local_cursor, this._true_color));
this._sock.send(RFB.messages.fbUpdateRequests(this._display.getCleanDirtyReset(),
	this._fb_width, this._fb_height));
this._timing.fbu_rt_start = (new Date()).getTime();
this._timing.pixels = 0;
```

So that it sends the setPixelFormat, setClientEncoding, and FramebufferUpdateRequest in 3 seperate websocket frames, it indeed does work properly.
Confirming my theory.

But again, I believe the problem in libvncserver may be more extensive than just limited to novnc and websockets.
OpenSSL has internal buffers as well, which you normally have to check with SSL_pending(), because data pending in there does not trigger select() either.
