### ISSUE TITLE
Unexpected high traffic with tight and  compressLevel 1

### ISSUE THREAD

**Issue by donob4n** [LibVNC/libvncserver#560]
I'm running an application with vglrun on a  tigerVNC/X11 server.

At the moment the application appars the server starts to upload near ~1.5Mbytes/s altought the screen is absolutely static.

After doing some test I changed the compressLevel to 2 and the traffic goes near 0 while the app remains iddle.

What are the differences with 1 and 2 levels that could cause this huge difference?

I feel that the problem also happens if I disable 'tight' encoding regardless the compressLevel.

**Comment by bk138** [comment]
I don't know about the details of the compression levels - you might want to ask at https://app.gitter.im/#/room/#LibVNC_libvncserver:gitter.im (more recent) or https://lists.sourceforge.net/lists/listinfo/libvncserver-common (rather outdated).
