### ISSUE TITLE
Segfault with 2 display stream  

### ISSUE THREAD

**Issue by sdikshit786** [LibVNC/libvncserver#564]
I need some help the vncserver is getting crashed with segfault.
Currently 2 displays are connected to my board and vncserver is running to stream HDMI on 5900 port & LVDS on 5901 port 
Everything works well when only connected to HDMI but when I tried to connect to LVDS vncserver crashed with following backtrace.

Also I am using touch emulation for LVDS.

Resolution of display: 
HDMI 1280x720
LVDS 1920x720

Backtrace:
EXH /usr/lib64/libvncserver.so.0.9.14(rfbSendCompressedDataTight+0x2290)[0xffffa92e19f0]
EXH /usr/lib64/libvncserver.so.0.9.14(rfbSendCompressedDataTight+0x2de8)[0xffffa92e2548]
EXH /usr/lib64/libvncserver.so.0.9.14(rfbSendCompressedDataTight+0x346c)[0xffffa92e2bcc]
EXH /usr/lib64/libvncserver.so.0.9.14(rfbSendFramebufferUpdate+0x80c)[0xffffa92c101c]
EXH /usr/lib64/libvncserver.so.0.9.14(rfbDefaultPtrAddEvent+0x200)[0xffffa92b8d90]
EXH /lib64/libpthread-2.27.so(__pthread_get_minstack+0x13a0)[0x3e85c46f78]

**Comment by bk138** [comment]
Hi, for questions please use the chat, you'll get more audience there: https://app.gitter.im/#/room/#LibVNC_libvncserver:gitter.im - also, please post your code, otherwise it's just guesswork ;-)

**Comment by bk138** [comment]
@sdikshit786 I saw you posted on the chat, closing this then :-)
