### ISSUE TITLE
Can screen->framebuffer can be in use after sending displayFinishedHook ?

### ISSUE THREAD

**Issue by sdikshit786** [LibVNC/libvncserver#569]
I am facing an issue with VNC server a yes/no answer to the following question will help.

If displayFinishedHook call implies libvncserver is finished using the buffer supplied as screen->framebuffer?

Thanks!

**Comment by bk138** [comment]
No.

**Comment by sdikshit786** [comment]
Thanks!
Kindly, guide the usage of the displayFinishedHook what is the purpose and what the call to this indicates?

**Comment by bk138** [comment]
You can see in 09f7c684a2b7eb43f283dcd938f0ccad891724e8 what it does.
