### ISSUE TITLE
Memory leak in rfbClientConnectionGone when using websockets

### ISSUE THREAD

**Issue by JorisHansMeijer** [LibVNC/libvncserver#571]
When using websockets the wsctx context is not freed after a disconnect. 

To solve this, in rfbserver.c add to rfbClientConnectionGone:

  if (cl->wsctx != NULL)
  {
      free(cl->wsctx);
      cl->wsctx = NULL;
  }

**Comment by bk138** [comment]
Thanks for finding out! Could you be so kind and file a pull request? This way, we can also have proper author credits :-)

**Comment by JorisHansMeijer** [comment]
Done
