### ISSUE TITLE
LibVNC server asks for password for the VNC authentication while connecting via http

### ISSUE THREAD

**Issue by jharajan** [LibVNC/libvncserver#58]
Hi,

I have LibVNC 0.9.7 and I am trying to connect the server through web browser. after connection, java applet throws a pop up window which asks for the password for the vnc authentication. I don't know what is the default password for my server as I just built the code and start the server.If I click on ok without entering any password, It doesn't close and doesn't even give any message. No clue what is going on as server side also doesn't show any messages. Please help if anybody has already faced this issue and knows the solution.
thanks.. :)

**Comment by bk138** [comment]
Mhh which server are you running? The example or x11vnc or ... ?

**Comment by rj2015** [comment]
hi bk138,
sorry for the delayed response. as I have mentioned I am using Libvnc-0.9.10 and running the same server. now I have one update that If I give a blank password or any wrong password and click on ok,
it shows me a error message like"Error: access denied("java.net.SocketPermission""ip-address:port_no""connect,resolve")". If I set even a password for my VNC server, while connecting via any vnc viewer it asks for the password and authenticate with the same password what I have set, but while providing the same password to the http connection it again throws the same pop up error message. 
![image](https://cloud.githubusercontent.com/assets/10768242/5971496/1bdd4ef8-a86d-11e4-83ca-6aeb112134f8.png)

**Comment by bk138** [comment]
Sry, but which server exactly?

**Comment by rj2015** [comment]
its tightVNC I suppose..

**Comment by bk138** [comment]
Sry but then you have to ask the TightVNC guys...
