### ISSUE TITLE
Which VNC encoding consumes the least CPU and bandwidth, and is best for both CPU and bandwidth?

### ISSUE THREAD

**Issue by yuhmvp** [LibVNC/libvncserver#588]
I have a question regarding VNC encodings. I would like to know which encoding option in the VNC protocol is the least CPU-intensive, which one consumes the least bandwidth, and which one is considered the best choice for optimizing both CPU and bandwidth usage.

Could you please provide some insights or recommendations on which encoding method would be most suitable for minimizing CPU usage and conserving bandwidth? I would like to understand which encoding method offers the best balance between CPU performance and bandwidth efficiency.

**Comment by bk138** [comment]
If you have a general question, it's best to [ask in the community chat](https://gitter.im/LibVNC/libvncserver).

That being said:

* least bandwidth: Tight
* least CPU: Raw
* good compromise IMHO: Ultra (but this is just a guesstimate)
