### ISSUE TITLE
Can I reduce image quality and change the encoding in the given code snippet?

### ISSUE THREAD

**Issue by yuhmvp** [LibVNC/libvncserver#589]
In the provided code snippet, I want to modify the image quality and encoding settings to suit my requirements. Specifically, I aim to reduce the image quality by 80% to save bandwidth and change the encoding to a more compressed format, such as "tight." I would appreciate guidance on the necessary code modifications to achieve these adjustments

    server = rfbGetScreen(&argc, &agv, maxx, maxy, 8, 3, bpp);
    server->frameBuffer= (char*)malloc(maxx*maxy*bpp);
    server->alwaysShared = TRUE;
    server->newClientHook = newClient;
    server->ptrAddEvent = mouseCallback;
    server->kbdAddEvent = keyCallback;
    rfbInitServer(server);

**Comment by bk138** [comment]
Please use the [community chat](https://gitter.im/LibVNC/libvncserver) for questions in the future :pray: 

As for your question: it's the client who asks for an encoding and quality settings, not the server, see https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst :-)
