### ISSUE TITLE
README.md indicates LibVNCServer supports Zlibhex, but it doesn't

### ISSUE THREAD

**Issue by jcaselman-keysight** [LibVNC/libvncserver#609]
**Describe the bug**
The Encodings table in the readme indicates that libvncserver supports ZlibHex:
![image](https://github.com/LibVNC/libvncserver/assets/116232122/0eadd06d-b73b-4ccb-a54d-b8e298c5e81c)
but I have not been able to get the examples to to use it with our client, and looking through the code, `rfbEncodingZlibHex` doesn't appear to really be used (recognized in a few places, but I don't see any processing for it)

**Comment by bk138** [comment]
Thanks for spotting, fixed.
