### ISSUE TITLE
non-free common/sha1.*

### ISSUE THREAD

**Issue by cinemast** [LibVNC/libvncserver#61]
Hi!

It appears that the common/sha1.* code taken from the [RFC3174](https://tools.ietf.org/html/rfc3174) which as stated in the Full copyright statement section is forbidden to modify. Well extracting parts of it is probably interpretable as a modification. 

This makes it difficult packaging it for Debian (see [here](https://wiki.debian.org/NonFreeIETFDocuments)). 

Which license do you think is applicable to the common/sha1.* files?

Would it be possible to exchange those with a DFSG compatible implementation?

**Comment by bk138** [comment]
Maybe @kanaka can provide some insights?

**Comment by bk138** [comment]
Something like https://github.com/LibVNC/libvncserver/tree/sha1rework ?

**Comment by cinemast** [comment]
Looks good. I patched that into the new debian package.

**Comment by bk138** [comment]
Merged with #63.
