### ISSUE TITLE
sock_set_nonblocking函数中block好像反了

### ISSUE THREAD

**Issue by source00** [LibVNC/libvncserver#613]
https://github.com/LibVNC/libvncserver/blob/master/src/common/sockets.c
```c++
rfbBool sock_set_nonblocking(rfbSocket sock, rfbBool non_blocking, void (*log)(const char *format, ...))
{
#ifdef WIN32
  unsigned long block = non_blocking ? 0 : 1;
  if(ioctlsocket(sock, FIONBIO, &block) == SOCKET_ERROR) {
```

**Describe the bug**

期望异步通信，但ioctlsocket中block是0，实际为阻塞通信

**Comment by bk138** [comment]
Come on, please try to use a translation service.

**Comment by source00** [comment]
Expected non blocking communication, but block in ioctlsocket is 0, actual blocking communication

**Comment by source00** [comment]
> Come on, please try to use a translation service.

Expected non blocking communication, but block in ioctlsocket is 0, actual blocking communication
