### ISSUE TITLE
How to use LibVNCServer in .Net C#?

### ISSUE THREAD

**Issue by NilsHoyer** [LibVNC/libvncserver#629]
I was able to compile the LibVNCServer with the result of a .lib file and several .obj files.

How can I use them in .Net C#?

**Comment by bk138** [comment]
How to use a C library from .NET is not really a LibVNCServer-specific question :-)

A quick google attack yielded https://stackoverflow.com/questions/11425202/is-it-possible-to-call-a-c-function-from-c-net - you'll probly find more.

**Comment by NilsHoyer** [comment]
You are right: My question does not belong to LibVNCServer only, but I need an answer to use it. 😉

I know the [DllImport(...)] feature for importing a .dll file. (On the linked page, also a .so is mentioned, but I believe, this is a Linux file format only.)

But after compiling LibVNCServer via CMAKE with Visual Studio 2022, I got a .lib and several .obj files. And somewhere, I read, .lib files are not supported by Visual Studio.

So at the moment, I don't have an idea, how or where I can forward my search for a solution how to use LibVNCServer in my .Net C# project.

**Comment by bk138** [comment]
I think .lib files are simply static libraries which you can link to your program. If it has to be shared libraries, I suggest you look into the CMake documentation how to build these on Windows.

**Comment by NilsHoyer** [comment]
Thanks a lot, you made me happy. With your hint, I was able to generate a .dll file.
