### ISSUE TITLE
How to customize authentication flow in libvncserver?

### ISSUE THREAD

**Issue by flyqie** [LibVNC/libvncserver#634]
Hello, I noticed that libvncserver only supports two limited authentication methods, but libvncclient supports many authentication methods, so I want to implement a certain authentication method that libvncclient supports but libvncserver  does not support based on my business.

Basically, what I mean is that I want to use SASL authentication in my project, which libvncserver doesn't currently support, and it seems like I can reverse-code the server side from libvncclient, but I don't know if there's an elegant way to handle it in my project code with as little modification to libvncserver as possible (perhaps something like a hook?).

Is this possible? How should I do it?

Thank you!

**Comment by bk138** [comment]
Hi! 
Please use the community chat https://app.gitter.im/#/room/#LibVNC_libvncserver:gitter.im for future questions :-)

Regarding your question: There are no hooks whatsoever, this mainly boils down to extending LibVNCServer code itself (and contributing back to the project ;-) ).

HTH!
