### ISSUE TITLE
libvncserver should not advertize ExtendedClipboard support if server app doesn't supoort it 

### ISSUE THREAD

**Issue by gujjwal00** [LibVNC/libvncserver#638]
**Describe the bug**

libvncserver always [enables](https://github.com/LibVNC/libvncserver/blob/5279158585920b8558bf9f04861e390e174be427/src/libvncserver/rfbserver.c#L2467-L2476) ExtendedClipboard encoding if client supports it. When client sends cut text, it is reported to server app via `setXCutTextUTF8()` callback, which is [no-op](https://github.com/LibVNC/libvncserver/blob/5279158585920b8558bf9f04861e390e174be427/src/libvncserver/main.c#L752) by default. If app doesn't support UTF-8 cut text, it will not set this callback. As a result, client to server clipboard transfer will be completely broken.

To my knowledge, x11vnc and Gnome Remote Desktop are affected by this.

libvncserver should check whether the callback is set before enabling ExtendedClipoard encoding. This is how libvncclient does it.

**Comment by bk138** [comment]
Yes, clipboard cleanup is the last missing bit for v0.9.15 - I just need to find some time to tackle this ;-)

**Comment by bk138** [comment]
Closed via #639
