### ISSUE TITLE
Missing VERSION and SONAME

### ISSUE THREAD

**Issue by cinemast** [LibVNC/libvncserver#64]
Between 0.9.9 and 0.9.10 the ABI has been broken. This usually requires a version bump in the SONAME. Also the resulting *.so files all have version 0.0.0

Could you fix that?

Aside that, packaging of 0.9.10 for debian is almost done.

**Comment by bk138** [comment]
Mhh sure. Can you point me at the docs describing how to do this properly?
Am 07.02.2015 22:47 schrieb "Peter Spiess-Knafl" <notifications@github.com>:

**Comment by cinemast** [comment]
Maybe this will help you: https://autotools.io/libtool/version.html

I am no expert in autotools, have only done it in CMake.

**Comment by cinemast** [comment]
```
diff --git a/libvncclient/Makefile.am b/libvncclient/Makefile.am
index 76bed21..d458aa2 100644
--- a/libvncclient/Makefile.am
+++ b/libvncclient/Makefile.am
@@ -25,5 +25,5 @@ EXTRA_DIST=corre.c hextile.c rre.c tight.c zlib.c zrle.c ultra.c tls_gnutls.c tl
 $(libvncclient_la_OBJECTS): ../rfb/rfbclient.h
 
 lib_LTLIBRARIES=libvncclient.la
-
+libvncclient_la_LDFLAGS = -version-info 1:0:0
 
diff --git a/libvncserver/Makefile.am b/libvncserver/Makefile.am
index 38426af..e3e7c11 100644
--- a/libvncserver/Makefile.am
+++ b/libvncserver/Makefile.am
@@ -61,7 +61,7 @@ libvncserver_la_SOURCES=$(LIB_SRCS)
 libvncserver_la_LIBADD=$(WEBSOCKETSSSLLIBS)
 
 lib_LTLIBRARIES=libvncserver.la
-
+libvncserver_la_LDFLAGS = -version-info 1:0:0
 if HAVE_RPM
 $(PACKAGE)-$(VERSION).tar.gz: dist

```

**Comment by cinemast** [comment]
This should be sufficient for now.

**Comment by bk138** [comment]
https://github.com/LibVNC/libvncserver/commit/344264da2facfd2ffba4e2f567be6d2c14b6d63b

**Comment by cinemast** [comment]
For future releases, please keep ABI/API compatibility in mind. 

I asked the guy from rosalinux to add your project to his ABI compat tracker.

http://upstream.rosalinux.ru/versions/libvncserver.html

There you can see if the HEAD of master is ABI compatible to your latest release.

**Comment by bk138** [comment]
Nice, thanks!
