### ISSUE TITLE
Signing releases

### ISSUE THREAD

**Issue by cinemast** [LibVNC/libvncserver#65]
Please consider signing releases with a GPG/PGP key.

.g. using

`gpg --armor --detach-sign LibVNCServer-0.9.10.tar.gz`

The resulting file `LibVNCServer-0.9.10.tar.gz.asc` can then easily be added to the release via the file upload to attach "binaries" provided by github.

**Comment by bk138** [comment]
Fixed, see 1f8c443cbc439e79d9e2c8b92643b65b7332db89
