### ISSUE TITLE
Using libvncserver with an external event loop

### ISSUE THREAD

**Issue by federicotdn** [LibVNC/libvncserver#66]
One of the items of the 0.9.9 release notes is:
```
- Split two event-loop related functions out of the rfbProcessEvents() mechanism.
This is required to be able to do proper event loop integration with Qt. Idea was
taken from Vino's libvncserver fork.
```

Is there any documentation available on how to use these new functions, or a short example?

**Comment by bk138** [comment]
A simple look into git history would have revealed 9f8d8d4ef38951767aa428796df127ff80de9b6e.
