### ISSUE TITLE
rfbssl_gnutls.c:55: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [LibVNC/libvncserver#68]
rfbssl_gnutls.c:55:27: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]

```
if (!GNUTLS_E_SUCCESS == (ret = gnutls_init(&session, GNUTLS_SERVER))) {
```

Many duplicates in the same file.

**Comment by bk138** [comment]
Thanks for reporting, please file a pull request!

**Comment by dcb314** [comment]
>please file a pull request!

Not sure what you are asking for here, but I leave fixing bugs to others.

>PS: compiler, version?

gcc trunk and clang trunk.

**Comment by bk138** [comment]
Thank you for you help in true open source spirit. As we're on github: https://help.github.com/articles/using-pull-requests/

**Comment by dscho** [comment]
From the conversation, it appears to this developer that the issue is not important enough for the bug reporter to require a fix.

**Comment by Hello71** [comment]
looks to me like they want confirmation whether this is or is not the intended behavior.

**Comment by bk138** [comment]
who?

**Comment by Hello71** [comment]
the reporter.

**Comment by bk138** [comment]
It's not.

**Comment by dcb314** [comment]
Maybe

if (GNUTLS_E_SUCCESS != (ret = gnutls_init(&session, GNUTLS_SERVER))) {

would be closer to the original programmer's intention.

**Comment by bk138** [comment]
As I pointed out earlier, PRs are always welcome!
