### ISSUE TITLE
Need build guide

### ISSUE THREAD

**Issue by whyka** [LibVNC/libvncserver#71]
Hi guys,
Thank you for your cool lib.
Could you please show me an easy way to build libvncserver on Windows or Linux?
Seem your build instruction on main page http://libvnc.github.io/#building is out of date and I'm not familiar with Linux's build tools. Do I need to use CMake or Autotool at all?

**Comment by bk138** [comment]
Nope, autotools should be just fine. What in the instructions is outdated?

**Comment by whyka** [comment]
You can see part `./configure`, I can not run it directly in repository root.
I think that I must run some steps first to generate properly configure file.
Because you said it is autotools, I will try to invoke autotools to generate this though...
Thank you

**Comment by bk138** [comment]
Updated build instructions with https://github.com/LibVNC/LibVNC.github.io/commit/878602ccb08eff41db4dee460bbb34819cdd42b5.
