### ISSUE TITLE
Black screen on client

### ISSUE THREAD

**Issue by whyka** [LibVNC/libvncserver#73]
Hi, I have built the server successfully without SSL on Ubuntu and Android, server can write out connection information.
On client window size is correct but only shows black screen.
What should I deal with this problem?
I am using RealVNC/TightVNC viewers on Windows.

P/S: I have run executables in `examples` directory. `example.c` shows custom rich cursor and I can draw line on it. `simple.c` just shows black screen and `android/jni/fbvncserver.c` shows black screen too.

**Comment by bk138** [comment]
Well that's the way they are supposed to work - read the code! - the latter ones simply show a memory region. If you don't put anything there, well...

**Comment by whyka** [comment]
Actually Android example is able to streaming screen to client.
I have tested on other device and can partly seen its screen.
I think this problem caused by difference resolutions between client and sever:
Server => Nexus 7 resolution: 1200 x 1900 (See nothing. Too large?)
Client => My desktop: 1366 x 768
Another Server => Samsung Galaxy: 720 x 1280 (Visible half of screen)
My question is if resolution affect how VNC streaming screen?

**Comment by bk138** [comment]
Ok, for android framebuffer reading, you most probably need root access. Also, the android server sample code should print out the detected frame buffer size.

**Comment by wangzj053617** [comment]
hi whyka
     have you resolve this issue on Server => Nexus 7 resolution: 1200 x 1900 ? I tried to use libvncserver on lenovo yoga book(anroid6.0 1200x1920) also meet this issue ,hope you give some advise . thanks!
