### ISSUE TITLE
Getting access to rfb device & KeyMode handling

### ISSUE THREAD

**Issue by andrey-sitsko** [LibVNC/libvncserver#78]
Hi!
I have feeling that my issues is very trivial but I can't solve it((((
At libvnc android example access to rfb devise is getting by using next command:
```
open("/dev/fb0", O_RDONLY);
```
Ubuntu also have same file in /dev directory, but I can't have access on it, open() function return mistake accessing file. I cannot find in Google any valuable advice how to open rfb device at Ubuntu, or I'am mistaking in using this way, and I need another issue to grab screen image from server computer?

And my another question is in sending keymode event to server. rfbScreenInfoPtr data structure have an field kbdAddEvent which takes function pointer that handle keyboards events coming from client.  kbdAddEvent field have next prototype:
```
typedef void (*rfbKbdAddEventProcPtr) (rfbBool down, rfbKeySym keySym, struct _rfbClientRec* cl)
```
It takes only one keyboard button code at a time. How can I handle such keyboards event such as "alt+tab", "shift+cntrl" and etc. 

Sorry for my silly questions, you're my last hope, my course project of remote desktop control are totally firing, and it takes me in real trouble(((

**Comment by bk138** [comment]
1. is a permissions issue. 2. alt-tab is not a single key event, it's two: alt down, tab down. HTH!

**Comment by andrey-sitsko** [comment]
Thank you very much, in first issue you are right, problem was in permission rights, multikey handling work nice, I just make too fast conclusion about it, cause I don't have any ability to test it before, but I do it now and everything work nice. Thank's a lot for your answers and for your awesome lib!
P.S. Please, don't close this issue, maybe I will have some trouble in future, your answers really save me a lot time.

**Comment by bk138** [comment]
No problem! But for general coding questions, the Mailinglist sure is a better place! You'll find it at the Main LibVNC site!
