### ISSUE TITLE
--with-ssl --without-gcrypt --without-pthread: undefined reference to `pthread_mutexattr_settype'

### ISSUE THREAD

**Issue by Hello71** [LibVNC/libvncserver#80]
https://bugs.gentoo.org/show_bug.cgi?id=550916

caused by tls_openssl.c unconditionally using pthread mutexes which causes undefined symbols downstream.

**Comment by bk138** [comment]
Patches welcome! ;-)

**Comment by Hello71** [comment]
why don't we use the macros in rfb.h? or are those inapplicable?

**Comment by bk138** [comment]
which ones?

**Comment by Hello71** [comment]
MUTEX/LOCK/UNLOCK?

**Comment by bk138** [comment]
PR welcome!

**Comment by Hello71** [comment]
that... didn't answer my question. "is it correct to use the macros from rfb.h?"

**Comment by bk138** [comment]
Nope. The LOCK defines in tls_openssl.c should go into rfbclient.h though...

**Comment by Hello71** [comment]
this bug seems difficult to fix because it is unclear what thread safety guarantees libvncclient provides. there seems to be some attempt at thread safety based on the use of pthread mutexes, but tls_gnutls.c for example calls gnutls_global_init without a mutex which means that it is not safe to simultaneously initialize multiple rfb connections.

**Comment by bk138** [comment]
@Hello71 Since the move to CMake the check for OpenSSL pulls in threads as well. So this is kinda fixed in that you'll always have threading in the lib if you want OpenSSL. If you explicitly want OpenSSL without threads, this should be a new issue, feel free to open if you feel this needs to be addressed.
