### ISSUE TITLE
Websockets-Connection closes after receiving some mouse events

### ISSUE THREAD

**Issue by plettix** [LibVNC/libvncserver#81]
I use libvncserver and noVNC.
Connecting with a common vnc client to my server works fine and has no problems.
The connection through websockets works fine if "View Only" is set.
If I don't use "View Only", mouse and keyboard events were transmitted - as expected.
After several seconds the connection closes (sometimes immediately after moving the mouse, sometimes after 20 seconds). The reasons are 
"webSocketsDecodeHybi: got frame without mask
rfbProcessClientNormalMessage: read: Input/output error"
or
"got closure, reason 1002
rfbProcessClientNormalMessage: read: Connection reset by peer"
I used Chrome and Firefox on WIndows 7, noVNC Version of the "master" branch and the version from www.novnc.com.
My libvncserver runs under OSX 10.10 and Windows.

Does anyone know if thats a noVNC issue or a libvncserver issue?

**Comment by bk138** [comment]
Thanks for #84, I will test this soonish(tm).

**Comment by bk138** [comment]
Fixed by #84
