### ISSUE TITLE
listen6sock is checked on -1, even though under windows it has the type u_int.

### ISSUE THREAD

**Issue by SjefvLoo** [LibVNC/libvncserver#82]
listen6sock can have the special value -1, indicating it is not assigned. However on windows we have:
typedef u_int           SOCKET;

So the the value can never be -1. The statement:
if(rfbScreen->listen6Sock >= 0) {
Will always yield true, since assigning -1 to an u_int will result in a positive value.

This is problematic when trying to disable ipv6 by setting the port to 0. Listen6sock will not be assigned (as expected). However if statements like above will still result in true. (especially in the function rfbProcessNewConnection).

**Comment by bk138** [comment]
Fixed by #257.
