### ISSUE TITLE
noVNC: Failed to connect to server (code: 1006)

### ISSUE THREAD

**Issue by schlegea** [LibVNC/libvncserver#85]
Hi,

I'm using libvncserver version 0.9.9 on an embedded linux device and try to get noVNC to work.

If I try to connect direct with host:5800 the noVNC shows "Failed to connect to server (code: 1006)".

The libvncserver shows the following messages and is configured without a password at the moment:

25/08/2015 07:37:23 Got connection from client 192.168.101.26
25/08/2015 07:37:23   other clients:
25/08/2015 07:37:23 Got 'ws' WebSockets handshake
25/08/2015 07:37:23 Got protocol: binary, base64
25/08/2015 07:37:23   - webSocketsHandshake: using binary/raw encoding
25/08/2015 07:37:23   - WebSockets client version hybi-13
25/08/2015 07:37:24 rfbProcessClientProtocolVersion: client gone
25/08/2015 07:37:24 Client 192.168.101.26 gone
25/08/2015 07:37:24 Statistics             events    Transmit/ RawEquiv ( saved)
25/08/2015 07:37:24  TOTALS              :      0 |         0/        0 (  0.0%)
25/08/2015 07:37:24 Statistics             events    Received/ RawEquiv ( saved)
25/08/2015 07:37:24  TOTALS              :      0 |         0/        0 (  0.0%)

Other clients like the thight-vnc applet or UltraVNC work.

Is it possible that I have to setup a password to use noVNC and how can I setup a password for libvncserver. I've not found any example code for this.

Thanks a lot
Andreas

**Comment by bk138** [comment]
tried current master?

**Comment by schlegea** [comment]
Not until now, I must first include it into the embedded device.

**Comment by schlegea** [comment]
Can you give me an example or something else how to implement password auth and encryption?

**Comment by schlegea** [comment]
I've tried the current master now and noVNC works without password. Thank you for your answer.

**Comment by bk138** [comment]
Ok to close @schlegea ?

**Comment by schlegea** [comment]
Yes, can be closed.

Am 24.06.2016 um 12:19 schrieb Christian Beier:
