### ISSUE TITLE
Advise needed for libvncserver with C

### ISSUE THREAD

**Issue by schlegea** [LibVNC/libvncserver#86]
Hi,

I'm using libvncserver in a C program. The server works and I can connect to the server with several clients. But I need some programming/configuration advice for setting up the following points:

- password authentication
- set up encryption, perhaps ssl or something else
- Is there a possibility to set up a connection which tunnels the firewall, e.g. UDP or reverse connection from the server to a specific address which allows to connect through NAT?

I've searched long time for examples or something like this and tried a lot, but nothing worked. :-(. 

Thanks a lot
Andreas

**Comment by bk138** [comment]
See libvncserver/cargs.c - you simply pass CLI arguments or set the vars directly in-code.

**Comment by saurabhverma999** [comment]
Hello, Did you do the password authentication part?? If yes, could you share with me the steps which you followed to achieve the same ??

Thanks in advance!!
