### ISSUE TITLE
Unclear license for modified D3DES source files

### ISSUE THREAD

**Issue by mappu** [LibVNC/libvncserver#88]
The original D3DES was released into the public domain, but the copy in this repository is marked as follows:

    /*
     * This is D3DES (V5.09) by Richard Outerbridge with the double and
     * triple-length support removed for use in VNC.
     *
     * These changes are:
     *  Copyright (C) 1999 AT&T Laboratories Cambridge.  All Rights Reserved.
     *
     * This software is distributed in the hope that it will be useful,
     * but WITHOUT ANY WARRANTY; without even the implied warranty of
     * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     */

I don't think the disclaimer counts as a full license, so all that's left here is "All Rights Reserved" for AT&T. Under what terms can this file actually legally be used?

Was it part of the original GPL'd source drop? If so, can the GPL preamble be added to the file header to clarify this?

**Comment by mappu** [comment]
There is a mirror of the original, public-domain D3DES available at 

- http://docs.camlcity.org/docs/godisrc/cryptokit-1.3.tar.gz/cryptokit-1.3/d3des.h 
- http://docs.camlcity.org/docs/godisrc/cryptokit-1.3.tar.gz/cryptokit-1.3/d3des.c

The salient change is only in the ordering of the `bytebit` array, which has been reversed (presumably for big-endianness optimization).

I would recommend porting to the public domain release to clarify this murky license issue.

**Comment by dscho** [comment]
> Was it part of the original GPL'd source drop?

Your guess is as good as mine. As you can see in the initial revision (757fdc2454a97890c119cca8662b8d1763265e9a), back then I did not think of leaving a record on which source code this was based. So you will have to take the date as an indicator and hunt down the source code package (I believe that they were called `Xrfb` back then) corresponding to August 1st 2001.

**Comment by dscho** [comment]
Oh, and just to clarify: I did *not*, *ever* tamper with any file headers or licenses, so I hope you did not try to imply that.

**Comment by mappu** [comment]
Debian have a copy of `vnc_3.3.1.orig.tar.gz` as the upstream for their vncserver package, dated 1998-02-24, available from http://archive.debian.org/debian/dists/hamm/main/source/x11/vnc_3.3.1.orig.tar.gz .

This archive contains the `d3des.c` basically unmodified to the current libvncserver repo, although, the copyright back then was "Copyright (C) 1998 Olivetti & Oracle Research Laboratory" instead of AT&T. It is interesting to note that other source files in this same archive (e.g. `vncviewer/vncviewer.c`) do have the full GPL preamble at the start of each file.

The whole archive does include a GPLv2 LICENSE.TXT so I think the `d3des.c` file is clearly intended to be either PD or GPLv2. I am no longer concerned about the legality of using this file, you can close this issue if you agree.

**Comment by dscho** [comment]
> I am no longer concerned about the legality of using this file, you can close this issue if you agree.

I was never concerned about the legality of using this file. You raised the concern, and as you are placated now, you could have closed the ticket right away.
