### ISSUE TITLE
LibVNCServer and SSL?

### ISSUE THREAD

**Issue by schlegea** [LibVNC/libvncserver#91]
Hi,

how can I activate SSL for LibVNCServer?

Is there any sample or something else? I know I have to activate websocket support and I think I have to copy the path of a sslkeyfile to the rfbScreenInfo->sslkeyfile structure.

Is there something else to do for using ssl?

Thanks a lot
Andreas

**Comment by rj2015** [comment]
hi,
you can use the rfbssl_init() method from rfbssl_openssl.c to enable the SSL for libvncserver. of course you need to have the key and certiifcate which should be assigned to rfbScreenInfo->sslkeyfile and rfbScreenInfo->sslcertfile respectively.

**Comment by schlegea** [comment]
Sorry for the late answer.

I cannot set rfbScreenInfo->sslkeyfile and rfbScreenInfo->sslcertfile, because they are greyed out by the define LIBVNCSERVER_WITH_WEBSOCKETS. How can I set this define?

**Comment by rj2015** [comment]
what I remember, LIBVNCSERVER_WITH_WEBSOCKETS is already set. you need not to do that.

**Comment by schlegea** [comment]
The libvncserver binaries are configured and build for the embedded device with a make file which contains a lot of parameters (not written by me).

Can you give me the needed parameters for the configure command?

At the moment it looks like follows:
./configure \
		--host=$(TARGET_BUILD) --build=i686-pc-linux-gnu  --prefix=$(PRJROOT)/syslibs/usr/local/$(TARGET_BUILD)/sysroot/usr \
		--disable-static --enable-shared \
		--with-crypto --with-ssl --without-gnutls --without-gcrypt \
		--with-sdl-config=/bin/false \
		--without-v4l --with-libz --with-zlib --with-pic \
		--with-jpeg --with-png --without-avahi --without-ipv6 )

**Comment by bk138** [comment]
This #defines LIBVNCSERVER_WITH_WEBSOCKETS to 1 on my boxx...

**Comment by schlegea** [comment]
Thank you for the answer, it seems that there was an Eclipse highlighting issue, which need to reindex all files. I test the ssl connection the next days.

Thx

**Comment by schlegea** [comment]
I tried to enable websockets to establish a secure connection as follows:

I use the following configure command:
./configure \
        --host=$(TARGET_BUILD) --build=i686-pc-linux-gnu
--prefix=$(PRJROOT)/syslibs/usr/local/$(TARGET_BUILD)/sysroot/usr \
        --disable-static --enable-shared \
        --with-crypto --with-ssl --without-gnutls --without-gcrypt \
        --with-sdl-config=/bin/false \
        --without-v4l --with-libz --with-zlib --with-pic \
        --with-jpeg --with-png --without-avahi --without-ipv6 )

After changing the configure script the define LIBVNCSERVER_WITH_WEBSOCKETS
is not defined in my project. Eclipse greyed out the following part:

#ifdef LIBVNCSERVER_WITH_WEBSOCKETS
    char *sslkeyfile;
    char *sslcertfile;
#endif
Which libraries (attributes) are needed to enable websockets or is there
another option to use openssl to make a secure connection?

2015-10-29 11:46 GMT+01:00 Christian Beier <notifications@github.com>:

**Comment by schlegea** [comment]
What is preferable: a ssl keyfile or a cert?
How can I create such a file?

2015-11-12 16:17 GMT+01:00 Andreas Schlegel <schlegel.andreas@gmail.com>:

**Comment by schlegea** [comment]
Hi,

I've set up the server, but something is wrong.

The VNC SSL Repeater (vncssld) logged the following message:
vncssld[1713]: New connection from 192.168.101.22:42123
vncssld[1713]: Could not start SSL connection: SSL accept attempt failed with unknown errorerror:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol

The log of the libVNCserver shows the following message:
webSocketsHandshake: unknown connection error

Someone an idea?
