### ISSUE TITLE
building for android (apk)

### ISSUE THREAD

**Issue by velasta** [LibVNC/libvncserver#95]
Hey folks thank you so much for this open source. I'm trying to build and Android .apk VNC client using the build steps here (bottom): http://libvnc.github.io/#building

I'm doing this on a Linux Ubuntu host but I'm stuck on this step:

3. Execute
./configure --host=arm-eabi CC=arm-linux-androideabi-gcc

In which directory do I do this cause I keep getting that the "configure" command is not found. An then where do I do the $make .... 

The results should be an apk file right? That I can upload/install onto an Android device? 

Thank you so much for a pointer :)

**Comment by bk138** [comment]
Pls read https://libvnc.github.io/#building carefully. 
>   Or, if you checked out the source code repository directly instead of using a release tarball:
>       ./autogen.sh

Also, this does not build an .apk, but a simple ELF binary and it's a server binary ;-)

If you're looking for an open-source Android VNC client, there's https://github.com/bk138/multivnc

**Comment by velasta** [comment]
Thank you so much for that idea :) I've tried it out today and works like a charm (the VNC client). Do you know however how to make an android vnc SERVER?

I can't find any. Only this one: https://play.google.com/store/apps/details?id=org.onaips.vnc&hl=en
which isn't working.

Is there a way to use the source code and build and android VNC server like apk and install it on my android device so I can VNC into it :)

THANK YOU :)

**Comment by bk138** [comment]
LibVNCServer contains an Android VNC server, see https://github.com/LibVNC/libvncserver/blob/master/examples/android/README. However, this is not an .apk but a simple binary.

**Comment by velasta** [comment]
ahh I'm sorry I'm very new to this but how do I use a simple binary and put it on my android and use the server to VNC into it? 
Thank you, last question and I really appreciate the help you've given me here.

**Comment by bk138** [comment]
https://github.com/LibVNC/libvncserver/blob/master/examples/android/README last paragraph ;-)

**Comment by velasta** [comment]
Man your the best thanks so much! I guess going back to my very first question since I have to do these steps anyways for the Server (originally asked it for the client). 

I'm using libvnc0.9.10 and android NDK r10e on a Ubuntu host. 
I've set up my tool-chain (for android-5 and arm-linux-androideabi-4.9 .... no reason just randomly picked). 

1.) I can't figure out how to "Building with autotools" -- since in which directory (gives me error that "configure" is not a command which makes sense) do I execute $./configure --host=arm-eabi CC=arm-linux-androideabi-gcc & then $make

2.) So I tried (would prefer the top step to get to work so in the future it'll be easier) "Building with the NDK build system" -- I made a copy of my "libvnc 0.9.10" since I have to modify files in this step. I'm trying to modify the "rfbconfig.h.cmake" file in 0.9.10/rfb/... to match my android target but not sure what to do? 


Also after I build and install it onto my android. Is the server automatically turned on to default port 5901 or I have to turn the server on everytime? :)))

--Happy winter holidays

**Comment by bk138** [comment]
1.) rtfm
2.) also, please read https://github.com/LibVNC/libvncserver/blob/master/examples/android/README

**Comment by velasta** [comment]
Dear Christian 
Attached image shows my screen shot of what I see in the libvnc0.9.10 folder. It says in the manual to run them in "in the LibVNCServer root directory" but where is that exactly? :/ I can't find it when I look in the vncserver folder and when I run "locate" or "find" it doesn't find "configure" or "make"

![christian-rtfm](https://cloud.githubusercontent.com/assets/16232805/11985635/b8640022-a97b-11e5-977d-66b43986b04f.jpg)

**Comment by velasta** [comment]
Dear bk138,

I'm trying to build the VNCserver binary files but when I run the configure command (./configure --host=arm-eabi CC=arm-linux-androideabi-gcc) in the root directory, I keep getting this error, might you know how to fix that (I had to run 
$./autogen.sh
$autoreconf -f -i -Wall,no-obsolete 
before-hand too):


root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# 
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# ./configure --host=arm-eabi CC=arm-linux-androideabi-gcc
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-eabi-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for arm-eabi-gcc... arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10#

**Comment by velasta** [comment]
Here is the config.log output :/

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by LibVNCServer configure 0.9.10, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --host=arm-eabi CC=arm-linux-androideabi-gcc

## --------- ##
## Platform. ##
## --------- ##

hostname = ip-172-31-35-74
uname -m = x86_64
uname -r = 3.13.0-48-generic
uname -s = Linux
uname -v = #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2612: checking for a BSD-compatible install
configure:2680: result: /usr/bin/install -c
configure:2691: checking whether build environment is sane
configure:2746: result: yes
configure:2805: checking for arm-eabi-strip
configure:2835: result: no
configure:2845: checking for strip
configure:2861: found /usr/bin/strip
configure:2872: result: strip
configure:2897: checking for a thread-safe mkdir -p
configure:2936: result: /bin/mkdir -p
configure:2943: checking for gawk
configure:2959: found /usr/bin/gawk
configure:2970: result: gawk
configure:2981: checking whether make sets $(MAKE)
configure:3003: result: yes
configure:3032: checking whether make supports nested variables
configure:3049: result: yes
configure:3185: checking whether make supports nested variables
configure:3202: result: yes
configure:3241: checking for arm-eabi-gcc
configure:3268: result: arm-linux-androideabi-gcc
configure:3537: checking for C compiler version
configure:3546: arm-linux-androideabi-gcc --version >&5
./configure: line 3548: arm-linux-androideabi-gcc: command not found
configure:3557: $? = 127
configure:3546: arm-linux-androideabi-gcc -v >&5
./configure: line 3548: arm-linux-androideabi-gcc: command not found
configure:3557: $? = 127
configure:3546: arm-linux-androideabi-gcc -V >&5
./configure: line 3548: arm-linux-androideabi-gcc: command not found
configure:3557: $? = 127
configure:3546: arm-linux-androideabi-gcc -qversion >&5
./configure: line 3548: arm-linux-androideabi-gcc: command not found
configure:3557: $? = 127
configure:3577: checking whether the C compiler works
configure:3599: arm-linux-androideabi-gcc    conftest.c  >&5
./configure: line 3601: arm-linux-androideabi-gcc: command not found
configure:3603: $? = 127
configure:3641: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "LibVNCServer"
| #define PACKAGE_TARNAME "libvncserver"
| #define PACKAGE_VERSION "0.9.10"
| #define PACKAGE_STRING "LibVNCServer 0.9.10"
| #define PACKAGE_BUGREPORT "https://github.com/LibVNC/libvncserver"
| #define PACKAGE_URL ""
| #define PACKAGE "libvncserver"
| #define VERSION "0.9.10"
| #define VERSION_MAJOR 0
| #define VERSION_MINOR 9
| #define VERSION_PATCHLEVEL 10
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3646: error: in `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10':
configure:3648: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_CC_set=set
ac_cv_env_CC_value=arm-linux-androideabi-gcc
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_GNUTLS_CFLAGS_set=
ac_cv_env_GNUTLS_CFLAGS_value=
ac_cv_env_GNUTLS_LIBS_set=
ac_cv_env_GNUTLS_LIBS_value=
ac_cv_env_GTK_CFLAGS_set=
ac_cv_env_GTK_CFLAGS_value=
ac_cv_env_GTK_LIBS_set=
ac_cv_env_GTK_LIBS_value=
ac_cv_env_JPEG_LDFLAGS_set=
ac_cv_env_JPEG_LDFLAGS_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=arm-eabi
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_CC=arm-linux-androideabi-gcc
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/missing aclocal-1.14'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
ANDROID_FALSE=''
ANDROID_TRUE=''
AR=''
AS=''
AUTOCONF='${SHELL} /home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/missing autoconf'
AUTOHEADER='${SHELL} /home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/missing autoheader'
AUTOMAKE='${SHELL} /home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/missing automake-1.14'
AWK='gawk'
CC='arm-linux-androideabi-gcc'
CCDEPMODE=''
CFLAGS=''
CONFIG_LIBVA_FALSE=''
CONFIG_LIBVA_TRUE=''
CPP=''
CPPFLAGS=''
CRYPT_LIBS=''
CYGIPC_FALSE=''
CYGIPC_TRUE=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GNUTLS_CFLAGS=''
GNUTLS_LIBS=''
GREP=''
GTK_CFLAGS=''
GTK_LIBS=''
HAVE_GNUTLS_FALSE=''
HAVE_GNUTLS_TRUE=''
HAVE_LIBGTK_FALSE=''
HAVE_LIBGTK_TRUE=''
HAVE_LIBJPEG_FALSE=''
HAVE_LIBJPEG_TRUE=''
HAVE_LIBPNG_FALSE=''
HAVE_LIBPNG_TRUE=''
HAVE_LIBPTHREAD_FALSE=''
HAVE_LIBPTHREAD_TRUE=''
HAVE_LIBSDL_FALSE=''
HAVE_LIBSDL_TRUE=''
HAVE_LIBSSL_FALSE=''
HAVE_LIBSSL_TRUE=''
HAVE_LIBZ_FALSE=''
HAVE_LIBZ_TRUE=''
HAVE_MP3LAME_FALSE=''
HAVE_MP3LAME_TRUE=''
HAVE_RPM_FALSE=''
HAVE_RPM_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JPEG_LDFLAGS=''
LD=''
LDFLAGS=''
LIBGCRYPT_CFLAGS=''
LIBGCRYPT_CONFIG=''
LIBGCRYPT_LIBS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LINUX_FALSE=''
LINUX_TRUE=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/missing makeinfo'
MANIFEST_TOOL=''
MINGW_FALSE=''
MINGW_TRUE=''
MKDIR_P='/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OSX_FALSE=''
OSX_TRUE=''
OTOOL64=''
OTOOL=''
PACKAGE='libvncserver'
PACKAGE_BUGREPORT='https://github.com/LibVNC/libvncserver'
PACKAGE_NAME='LibVNCServer'
PACKAGE_STRING='LibVNCServer 0.9.10'
PACKAGE_TARNAME='libvncserver'
PACKAGE_URL=''
PACKAGE_VERSION='0.9.10'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
RANLIB=''
RPMSOURCEDIR=''
SDL_CFLAGS=''
SDL_LIBS=''
SED=''
SET_MAKE=''
SHELL='/bin/bash'
SSL_LIBS=''
STRIP='strip'
VA_LIBS=''
VERSION='0.9.10'
WITH_FFMPEG_FALSE=''
WITH_FFMPEG_TRUE=''
WITH_TIGHTVNC_FILETRANSFER_FALSE=''
WITH_TIGHTVNC_FILETRANSFER_TRUE=''
WITH_WEBSOCKETS_FALSE=''
WITH_WEBSOCKETS_TRUE=''
WSOCKLIB=''
ac_ct_AR=''
ac_ct_CC=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='arm-eabi'
host_alias='arm-eabi'
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''
with_ffmpeg=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "LibVNCServer"
#define PACKAGE_TARNAME "libvncserver"
#define PACKAGE_VERSION "0.9.10"
#define PACKAGE_STRING "LibVNCServer 0.9.10"
#define PACKAGE_BUGREPORT "https://github.com/LibVNC/libvncserver"
#define PACKAGE_URL ""
#define PACKAGE "libvncserver"
#define VERSION "0.9.10"
#define VERSION_MAJOR 0
#define VERSION_MINOR 9
#define VERSION_PATCHLEVEL 10

configure: exit 77

**Comment by velasta** [comment]
Dear bk138,

I ran the command 

$./configure --host=arm-eabi CC=/tmp/my-android-toolchain/bin/arm-linux-androideabi-gcc

gave me ''exit O" in config.log so it means it was successful :) YAY  But when i run

$make

it gives me an error :/ (make[2]: *** [rfbcrypto_included.lo] Error 1) might you know what the problem is cause it doesn't seem to be a problem on my side but something with the code ..... or it DUE TO SOMETHING WITH THE WAY THE ENVIRONMENT IS SET UP::

root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# 
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# make
make  all-recursive
make[1]: Entering directory `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10'
Making all in libvncserver
make[2]: Entering directory `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/libvncserver'
  CC       main.lo
  CC       rfbserver.lo
rfbserver.c: In function 'rfbProcessFileTransfer':
rfbserver.c:1690:69: warning: pointer targets in passing argument 1 of 'gmtime' differ in signedness [-Wpointer-sign]
               strftime(timespec, sizeof(timespec), "%m/%d/%Y %H:%M",gmtime(&statbuf.st_ctime));
                                                                     ^
In file included from rfbserver.c:87:0:
/tmp/my-android-toolchain/sysroot/usr/include/time.h:76:20: note: expected 'const time_t *' but argument is of type 'long unsigned int *'
 extern struct tm*  gmtime(const time_t *timep);
                    ^
  CC       rfbregion.lo
  CC       auth.lo
  CC       sockets.lo
  CC       websockets.lo
  CC       rfbssl_none.lo
  CC       rfbcrypto_included.lo
In file included from rfbcrypto_included.c:25:0:
../common/md5.h: In function '__md5_init_ctx':
../common/md5.h:101:50: error: expected declaration specifiers before '__THROW'
 extern void __md5_init_ctx (struct md5_ctx *ctx) __THROW;
                                                  ^
../common/md5.h:108:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
                  struct md5_ctx *ctx) __THROW;
                                       ^
../common/md5.h:115:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
                  struct md5_ctx *ctx) __THROW;
                                       ^
../common/md5.h:124:67: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
 extern void *__md5_finish_ctx (struct md5_ctx *ctx, void *resbuf) __THROW;
                                                                   ^
../common/md5.h:133:71: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
 extern void *__md5_read_ctx (const struct md5_ctx *ctx, void *resbuf) __THROW;
                                                                       ^
../common/md5.h:139:56: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
 extern int __md5_stream (FILE *stream, void *resblock) __THROW;
                                                        ^
../common/md5.h:146:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
                void *resblock) __THROW;
                                ^
In file included from rfbcrypto_included.c:26:0:
../common/sha1.h:62:1: warning: empty declaration
 enum
 ^
../common/sha1.h:89:3: error: storage class specified for parameter 'SHA1Context'
 } SHA1Context;
   ^
../common/sha1.h:94:17: error: expected declaration specifiers or '...' before 'SHA1Context'
 int SHA1Reset(  SHA1Context *);
                 ^
../common/sha1.h:95:17: error: expected declaration specifiers or '...' before 'SHA1Context'
 int SHA1Input(  SHA1Context *,
                 ^
../common/sha1.h:98:17: error: expected declaration specifiers or '...' before 'SHA1Context'
 int SHA1Result( SHA1Context *,
                 ^
rfbcrypto_included.c:30:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^
rfbcrypto_included.c:41:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^
In file included from rfbcrypto_included.c:25:0:
../common/md5.h:101:13: error: old-style parameter declarations in prototyped function definition
 extern void __md5_init_ctx (struct md5_ctx *ctx) __THROW;
             ^
rfbcrypto_included.c:49:1: error: expected '{' at end of input
 }
 ^
make[2]: *** [rfbcrypto_included.lo] Error 1
make[2]: Leaving directory `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/libvncserver'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10'
make: *** [all] Error 2
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10#

**Comment by velasta** [comment]
The problem seems to be here: make[2]: ** [rfbcrypto_included.lo] Error 1 :( and there are no solutions online

thank you very much in advance for your assistance :)
