### ISSUE TITLE
$make command fails during building (Android)

### ISSUE THREAD

**Issue by velasta** [LibVNC/libvncserver#96]
Dear folks

(wanted to make a separate issue since it isn't related to my previous one)

I'm using a 14.04 Ubuntu Machine.
The following command is successful

$./configure --host=arm-eabi CC=arm-linux-androideabi-gcc

I then run

$make

and get the following error ($make clean ... doesn't help. Seems there are errors in the actual C code or it's due to some missing libraries maybe?):

root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# 
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# make
make  all-recursive
make[1]: Entering directory `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10'
Making all in libvncserver
make[2]: Entering directory`/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/libvncserver'
  CC       main.lo
  CC       rfbserver.lo
rfbserver.c: In function 'rfbProcessFileTransfer':
rfbserver.c:1690:69: warning: pointer targets in passing argument 1 of 'gmtime' differ in signedness [-Wpointer-sign]
               strftime(timespec, sizeof(timespec), "%m/%d/%Y %H:%M",gmtime(&statbuf.st_ctime));
                                                                     ^
In file included from rfbserver.c:87:0:
/tmp/my-android-toolchain/sysroot/usr/include/time.h:76:20: note: expected 'const time_t _' but argument is of type 'long unsigned int *'
 extern struct tm_  gmtime(const time_t *timep);
                    ^

  CC       rfbregion.lo
  CC       auth.lo
  CC       sockets.lo
  CC       websockets.lo
  CC       rfbssl_none.lo
  CC       rfbcrypto_included.lo
In file included from rfbcrypto_included.c:25:0:
../common/md5.h: In function '**md5_init_ctx':
../common/md5.h:101:50: error: expected declaration specifiers before '__THROW'
 extern void __md5_init_ctx (struct md5_ctx *ctx) __THROW;
                                                  ^
../common/md5.h:108:39: error: expected '=', ',', ';', 'asm' or '__attribute**' before '**THROW'
                  struct md5_ctx *ctx) __THROW;
                                       ^
../common/md5.h:115:39: error: expected '=', ',', ';', 'asm' or '__attribute**' before '**THROW'
                  struct md5_ctx *ctx) __THROW;
                                       ^
../common/md5.h:124:67: error: expected '=', ',', ';', 'asm' or '__attribute**' before '**THROW'
 extern void *__md5_finish_ctx (struct md5_ctx *ctx, void *resbuf) __THROW;
                                                                   ^
../common/md5.h:133:71: error: expected '=', ',', ';', 'asm' or '__attribute**' before '**THROW'
 extern void *__md5_read_ctx (const struct md5_ctx *ctx, void *resbuf) __THROW;
                                                                       ^
../common/md5.h:139:56: error: expected '=', ',', ';', 'asm' or '__attribute**' before '**THROW'
 extern int __md5_stream (FILE *stream, void *resblock) __THROW;
                                                        ^
../common/md5.h:146:32: error: expected '=', ',', ';', 'asm' or '__attribute**' before '**THROW'
                void *resblock) __THROW;
                                ^
In file included from rfbcrypto_included.c:26:0:
../common/sha1.h:62:1: warning: empty declaration
 enum
 ^
../common/sha1.h:89:3: error: storage class specified for parameter 'SHA1Context'
 } SHA1Context;
   ^
../common/sha1.h:94:17: error: expected declaration specifiers or '...' before 'SHA1Context'
 int SHA1Reset(  SHA1Context *);
                 ^
../common/sha1.h:95:17: error: expected declaration specifiers or '...' before 'SHA1Context'
 int SHA1Input(  SHA1Context *,
                 ^
../common/sha1.h:98:17: error: expected declaration specifiers or '...' before 'SHA1Context'
 int SHA1Result( SHA1Context *,
                 ^
rfbcrypto_included.c:30:1: error: expected '=', ',', ';', 'asm' or '__attribute**' before '{' token
 {
 ^
rfbcrypto_included.c:41:1: error: expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
 {
 ^
In file included from rfbcrypto_included.c:25:0:
../common/md5.h:101:13: error: old-style parameter declarations in prototyped function definition
 extern void __md5_init_ctx (struct md5_ctx _ctx) __THROW;
             ^
rfbcrypto_included.c:49:1: error: expected '{' at end of input
 }
 ^
make[2]: *_\* [rfbcrypto_included.lo] Error 1
make[2]: Leaving directory `/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10/libvncserver'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/ubuntu/Desktop/libvncserver-LibVNCServer-0.9.10'
make: **\* [all] Error 2
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10# 
root@ip-172-31-35-74:~/Desktop/libvncserver-LibVNCServer-0.9.10#

**Comment by velasta** [comment]
Also if anyone has the Binary Library files for Android that would be great so I can just insert them into Android and do the building process. Unless I'm the only one having this problem then I know it's a problem on my side and I can fix it. Any pointer would be SUPER great :) nothing online about this sadly

**Comment by velasta** [comment]
Hello,

It looks like the libvncserver source code expects system C header files that define __THROW appropriately for C usage and the android compiler/headers you are trying to use don't do that. You can try defining it away yourself or finding out what, potentially more appropriate, value it should have for your target platform

(Is the source code not ready for compiling and I need to write it out or is it ready to be used? Please correct me if I'm wrong since I thought this code was complete and ready for EVERYONE to use :) )

**Comment by bk138** [comment]
Closed by 80ad74f7613d7d790a5152ee377af361ecd3ff9b
