### ISSUE TITLE
check for NullPointer in FillRectangle() ?

### ISSUE THREAD

**Issue by spaceone** [LibVNC/libvncserver#98]
Hello,
I saw the following commit which checks for a null pointer in CopyRectangle():
https://github.com/LibVNC/libvncserver/commit/7c7e8e765c06a8af13c1f2662f1c7084c937738a

Wouldn't it make sense to add this also to FillRectangle() as well as CopyRectangleFromRectangle()?
See:
https://github.com/spaceone/italc/commit/369c806ea52df841cf05c76bc0c36235099ae52e

**Comment by bk138** [comment]
yep, indeed

**Comment by spaceone** [comment]
Okay, I will create a PR.
